--REVELA OS NOMES DOS MANDANTES CADASTRADOS
--AUTOR: KELSEN LIMA

SELECT RODEMP.*,G.DESCRI AS GRUPO FROM RODEMP  LEFT OUTER JOIN RODEMP G  ON RODEMP.CODGRU = G.CODEMP  WHERE RODEMP.CODEMP <> 0 


--ATUALIZA A NOMENCLATURA DOS MANDANTES, COLOCANDO TREINAMENTO, HOMOLOGAÇÃO E AFINS
UPDATE RODEMP
SET DESCRI = 'QA HOMOLOGACAO - GAT TRANSPORTES EIRELI'
WHERE CODEMP = 1

UPDATE RODEMP
SET DESCRI = 'QA HOMOLOGACAO - MJDS TRANSPORTES EIRELI'
WHERE CODEMP = 2

UPDATE RODEMP
SET DESCRI = 'QA HOMOLOGACAO - GAT LOGISTICA LTDA'
WHERE CODEMP = 6

UPDATE RODEMP
SET DESCRI = 'QA HOMOLOGACAO - NOVA LOGISTICA'
WHERE CODEMP = 10

UPDATE RODEMP
SET DESCRI = 'QA HOMOLOGACAO - GAT LOGISTICA'
WHERE CODEMP = 100