-- CAD. PARCEIRO COMERCIAL, FLAG TAXA FRETE
-- AUTOR: KELSEN LIMA

 SELECT TOP 10 * FROM RODCON_VADI
 WHERE CODDOC=4904

 SELECT TOP 10 * FROM RODCON


SELECT RODCON_VADI.TIPDOC, RODCON_VADI.CODDOC, RODCON_VADI.SERDOC, RODCON_VADI.FILDOC, RODCON_VADI.DESCRI FROM RODCON_VADI

SELECT RODCON_VADI.CODDOC, RODCON_VADI.TIPDOC, RODCON_VADI.SERDOC, RODCON_VADI.FILDOC, RODCON_VADI.VLRADI, RODCON_VADI.DESCRI FROM RODCON_VADI
INNER JOIN RODCON ON RODCON_VADI.CODDOC = RODCON.CODCON
WHERE RODCON.CODPAG=46975
 --AND RODCON.CODCON=4904

 SELECT RODCON_VADI.CODDOC, RODCON_VADI.TIPDOC, RODCON_VADI.SERDOC, RODCON_VADI.FILDOC, RODCON_VADI.VLRADI, RODCON_VADI.DESCRI, RODCON.CODPAG  FROM RODCON_VADI
INNER JOIN RODCON ON RODCON_VADI.CODDOC = RODCON.CODCON
WHERE RODCON.CODPAG=46975
 --AND RODCON.CODCON=4904


