--SELECT RODCON.FILMAN, RODCON.SERMAN, RODCON.CODMAN FROM RODCON WHERE RODCON.CODCON = 444443
-- CONSULTA SITUACAO DO CTRC
-- AUTOR: KELSEN LIMA

SELECT              
    'CTRC' AS TIPDOC,  
	TIPSER = CASE CON.TIPCON

		WHEN 'R' THEN 'REENTREGA'
		WHEN 'O' THEN 'TRANSF OST'
		WHEN 'A' THEN 'TRANSF ACT'
		WHEN 'N' THEN 'NORMAL'
		WHEN 'C' THEN 'COMPLEMENTAR'
		WHEN 'P' THEN 'PARCIAL'
		WHEN 'D' THEN 'DEVOLUCAO TOTAL'
		WHEN 'P' THEN 'DEVOLUCAO PARCIAL'
		WHEN 'H' THEN 'REDESPACHO TOTAL'
		WHEN 'I' THEN 'REDESPACHO INTERMODAL'
		WHEN 'U' THEN 'SUBCONTRATACAO'
		WHEN 'M' THEN 'MULTIMODAL'
		WHEN 'V' THEN 'VINCULADO A MULTIMODAL'

	END,
	CON.SITUAC AS SITUAC,              
    CON.DATCAD AS DATA,  
 FORMAT(CONVERT(TIME,CON.DATEMI),N'hh\:mm') AS HORA_EMISSAO,  
 CON.CODFIL AS COD_FILIAL,               
    CON.SERCON AS SERIE,              
    CON.CODCON AS DOCUMENTO,              
    CPAG.CODCLIFOR AS COD_PAGADOR,               
    UPPER(CPAG.RAZSOC)+' ('+(select RODMUN.DESCRI FROM RODMUN (NOLOCK) WHERE CPAG.CODMUN= RODMUN.CODMUN)+')' AS PAGADOR,               
    CREM.CODCLIFOR AS COD_REMETENTE,              
    UPPER(CREM.RAZSOC) AS REMETENTE,              
    CDES.CODCLIFOR AS COD_DESTINATARIO,              
 CASE              
  WHEN CDES.FISJUR = 'F' THEN              
   CDES.CODCPF              
  WHEN CDES.FISJUR = 'J' THEN              
   CDES.CODCGC              
    END DES_CNPJ,              
    UPPER(CDES.RAZSOC) AS DESTINATARIO,              
    CON.LOCENT AS MUN_DESTINATARIO,       
  
 IIF(ISNULL( (SELECT TOP 1 RODMUN.DESCRI FROM RODMUN (NOLOCK) , RODIMA (NOLOCK), RODMAN (NOLOCK), RODFIL (NOLOCK)  
    WHERE RODMAN.CODMAN = RODIMA.CODMAN   
    AND RODMAN.CODFIL = RODIMA.FILMAN   
    AND RODIMA.SERMAN = RODMAN.SERMAN  
                AND RODIMA.CODDOC = CON.CODCON   
    AND RODIMA.FILDOC = CON.CODFIL   
    AND RODIMA.SERDOC = CON.SERCON  
    AND RODMAN.FILDES = RODFIL.CODFIL  
    AND RODMUN.CODMUN = RODFIL.CODMUN ORDER BY RODMAN.DATEMI DESC),'') = ''   
      
 , /*Se verdadeiro para MUNICIPIO DO MANIFESTO = VAZIO*/  
  
  IIF(ISNULL(MTENT.DESCRI,'') = ''   
    
  , /*Se verdadeiro para MUNICIPIO DO TERMINAL DE ENTREGA = VAZIO*/   
      
   IIF(ISNULL((SELECT TOP 1 RODMUN.FILRES FROM RODMUN (NOLOCK) WHERE MUNDES.CODMUN = RODMUN.CODMUN),0) = 0   
     
   , /*Se verdadeiro para Municipio da Filial Responsavel pelo atendimento = VAZIO*/  
     
    (SELECT TOP 1 RODMUN.DESCRI FROM RODMUN (NOLOCK) INNER JOIN RODFIL (NOLOCK) ON RODFIL.CODFIL = CON.CODFIL AND RODMUN.CODMUN = RODFIL.CODMUN)  
      
   , /*Se falso*/   
      
    (SELECT TOP 1 RODMUN.DESCRI FROM RODMUN (NOLOCK) INNER JOIN RODFIL (NOLOCK) ON RODFIL.CODFIL = MUNDES.FILRES AND RODFIL.CODMUN = RODMUN.CODMUN)  
      
   )   
      
  , /*Se falso para o municipio do terminal de entrega*/  
  
--    MTENT.DESCRI  
  
   IIF(ISNULL((SELECT TOP 1 RODMUN.FILRES FROM RODMUN (NOLOCK) WHERE MTENT.CODMUN = RODMUN.CODMUN),0) = 0   
     
   , /*Se verdadeiro para Municipio da Filial Responsavel pelo atendimento = VAZIO*/  
     
    (SELECT TOP 1 RODMUN.DESCRI FROM RODMUN (NOLOCK) INNER JOIN RODFIL (NOLOCK) ON RODFIL.CODFIL = CON.CODFIL AND RODMUN.CODMUN = RODFIL.CODMUN)  
      
   , /*Se falso para o municipio do terminal de entrega = vazio*/   
      
    (SELECT TOP 1 RODMUN.DESCRI FROM RODMUN (NOLOCK) WHERE RODMUN.CODMUN = FILRES.CODMUN)  
      
   )   
    
  )   
       
 , /*Se falso, Utiliza o Municipio da filial de destino do Manifesto, dependendo do tipo do manifesto  
    Se o manifesto for = 1 'LOTACAO' ou 6 'DISTRIBUICAO' - Envia a filial de destino */  
   
  IIF(MAN.TIPMAN NOT IN ('6','1')   
    
  , /*Se o manifesto não for de '6-distribuicao' OU '1-Lotacao', envia o código da filial de destino*/   
  
   (SELECT TOP 1 RODMUN.DESCRI FROM RODMUN (NOLOCK), RODIMA(NOLOCK), RODMAN(NOLOCK), RODFIL(NOLOCK)  
    WHERE RODMAN.CODMAN = RODIMA.CODMAN   
    AND RODMAN.CODFIL = RODIMA.FILMAN   
    AND RODIMA.SERMAN = RODMAN.SERMAN  
    AND RODIMA.CODDOC = CON.CODCON   
    AND RODIMA.FILDOC = CON.CODFIL   
    AND RODIMA.SERDOC = CON.SERCON  
    AND RODMAN.FILDES = RODFIL.CODFIL  
    AND RODMUN.CODMUN = RODFIL.CODMUN ORDER BY RODMAN.DATEMI DESC)  
   
  , /*Caso contrário, envia o código da filial de emissão*/  
  
    (SELECT TOP 1 RODMUN.DESCRI FROM RODMUN (NOLOCK), RODIMA(NOLOCK), RODMAN(NOLOCK), RODFIL(NOLOCK)  
    WHERE RODMAN.CODMAN = RODIMA.CODMAN   
    AND RODMAN.CODFIL = RODIMA.FILMAN   
    AND RODIMA.SERMAN = RODMAN.SERMAN  
    AND RODIMA.CODDOC = CON.CODCON   
    AND RODIMA.FILDOC = CON.CODFIL   
    AND RODIMA.SERDOC = CON.SERCON  
    AND RODMAN.CODFIL = RODFIL.CODFIL  
    AND RODMUN.CODMUN = RODFIL.CODMUN ORDER BY RODMAN.DATEMI DESC)  
  
  )  
  
 ) AS FILRES_DESTINO  
  
 ,  
   
 IIF(ISNULL((SELECT TOP 1 RODMUN.ESTADO FROM RODMUN(NOLOCK), RODIMA(NOLOCK), RODMAN(NOLOCK), RODFIL(NOLOCK)  
    WHERE RODMAN.CODMAN = RODIMA.CODMAN   
    AND RODMAN.CODFIL = RODIMA.FILMAN   
    AND RODIMA.SERMAN = RODMAN.SERMAN  
                AND RODIMA.CODDOC = CON.CODCON   
    AND RODIMA.FILDOC = CON.CODFIL   
    AND RODIMA.SERDOC = CON.SERCON  
    AND RODMAN.FILDES = RODFIL.CODFIL  
    AND RODMUN.CODMUN = RODFIL.CODMUN ORDER BY RODMAN.DATEMI DESC),'') = ''   
      
 , /*Se verdadeiro para MUNICIPIO DO MANIFESTO = VAZIO*/  
  
  IIF(ISNULL(MTENT.ESTADO,'') = ''   
    
  , /*Se verdadeiro para MUNICIPIO DO TERMINAL DE ENTREGA = VAZIO*/   
      
   IIF(ISNULL((SELECT TOP 1 RODMUN.FILRES FROM RODMUN (NOLOCK) WHERE MUNDES.CODMUN = RODMUN.CODMUN),0) = 0   
     
   , /*Se verdadeiro para Municipio da Filial Responsavel pelo atendimento = VAZIO*/  
     
    (SELECT TOP 1 RODMUN.ESTADO FROM RODMUN (NOLOCK) INNER JOIN RODFIL (NOLOCK) ON RODFIL.CODFIL = CON.CODFIL AND RODMUN.CODMUN = RODFIL.CODMUN)  
      
   , /*Se falso*/   
      
    (SELECT TOP 1 RODMUN.ESTADO FROM RODMUN (NOLOCK) INNER JOIN RODFIL (NOLOCK) ON RODFIL.CODFIL = MUNDES.FILRES AND RODFIL.CODMUN = RODMUN.CODMUN)  
      
   )   
      
  , /*Se falso*/  
  
   IIF(ISNULL((SELECT TOP 1 RODMUN.FILRES FROM RODMUN (NOLOCK) WHERE MTENT.CODMUN = RODMUN.CODMUN),0) = 0   
     
   , /*Se verdadeiro para Municipio da Filial Responsavel pelo atendimento = VAZIO*/  
     
    (SELECT TOP 1 RODMUN.ESTADO FROM RODMUN (NOLOCK) INNER JOIN RODFIL (NOLOCK) ON RODFIL.CODFIL = CON.CODFIL AND RODMUN.CODMUN = RODFIL.CODMUN)  
      
   , /*Se falso*/   
      
    (SELECT TOP 1 RODMUN.ESTADO FROM RODMUN (NOLOCK) WHERE RODMUN.CODMUN = FILRES.CODMUN)  
      
   )   
    
  )   
       
 , /*Se falso, Utiliza o Municipio da filial de destino do Manifesto*/  
  
  IIF(MAN.TIPMAN <> '6'  
  
  , /*Se o tipo do manifesto não for = 'distribuicao', envia o codigo da filial de destino */  
    
  (SELECT TOP 1 RODMUN.ESTADO FROM RODMUN(NOLOCK), RODIMA(NOLOCK), RODMAN(NOLOCK), RODFIL(NOLOCK)  
   WHERE RODMAN.CODMAN = RODIMA.CODMAN   
   AND RODMAN.CODFIL = RODIMA.FILMAN   
   AND RODIMA.SERMAN = RODMAN.SERMAN  
   AND RODIMA.CODDOC = CON.CODCON   
   AND RODIMA.FILDOC = CON.CODFIL   
   AND RODIMA.SERDOC = CON.SERCON  
   AND RODMAN.FILDES = RODFIL.CODFIL  
   AND RODMUN.CODMUN = RODFIL.CODMUN ORDER BY RODMAN.DATEMI DESC)  
  
  , /*Caso contrário, envia o código da filial de emissao*/  
  
  (SELECT TOP 1 RODMUN.ESTADO FROM RODMUN(NOLOCK), RODIMA(NOLOCK), RODMAN(NOLOCK), RODFIL(NOLOCK)  
   WHERE RODMAN.CODMAN = RODIMA.CODMAN   
   AND RODMAN.CODFIL = RODIMA.FILMAN   
   AND RODIMA.SERMAN = RODMAN.SERMAN  
   AND RODIMA.CODDOC = CON.CODCON   
   AND RODIMA.FILDOC = CON.CODFIL   
   AND RODIMA.SERDOC = CON.SERCON  
   AND RODMAN.CODFIL = RODFIL.CODFIL  
   AND RODMUN.CODMUN = RODFIL.CODMUN ORDER BY RODMAN.DATEMI DESC)  
    
  )  
       
 ) AS EST_DESTINATARIO ,  
  
       NFC.NOTFIS AS NOTA_01,               
       NFC.SERIEN AS SERIE_NF,              
       CONVERT (CHAR(10),NFC.DATNOT,103) AS DT_NOTA_01,                    
       NFC.PESOKG AS PESO,               
    NFC.QUANTI AS QTD_VOL,               
       NFC.PESCAL AS PESO_CALC,              
       NFC.VLRMER AS VLR_MERC,     
      
  DATATIME_ENTREGA = CASE  
      
  WHEN   
  
   (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) = 0   
    
  THEN   
   
   CON.DATLME  
    
  ELSE  
  
   (SELECT dbo.adjustedDate(CONVERT(DATE,CON.DATLME),(SELECT CODITN FROM dbo.RODMUN (NOLOCK),dbo.RODLIN (NOLOCK) WHERE CON.CODLIN = RODLIN.CODLIN AND RODLIN.PONFIM = RODMUN.CODITN),CONVERT(TIME,CON.DATLME)))   
  
  END    ,  
  
  CON.DATLME AS LEAD_TIME_ORIGINAL,  
    (SELECT top 1 isnull(NFC.DATENT,OCH.DATOCO)          
        FROM RODOCH AS OCH(NOLOCK)              
        INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')  
        ORDER BY isnull(NFC.DATENT,OCH.DATOCO) DESC) AS DATA_ENTREGA,           
    CON.TOTFRE AS VLR_TOTAL_FRETE,               
    FRA.CODCMO,              
    CMO.DESCRI,              
    REG_O.DESCRI AS REGIAO_ORIGEM,  
 REG_D.DESCRI AS REGIAO_DESTINO,  
    CON.DATLME AS PRAZO_ENTREGA,              
       (SELECT TOP 1 IFR.METDIA              
       FROM RODIFR IFR(NOLOCK)              
       WHERE CON.TABPAD=IFR.CODFRE              
       AND CON.ID_RODIIF=IIF.ID_RODIIF              
       AND IIF.ID_RODIFR=IFR.ID_RODIFR) AS METDIA,              
       (SELECT top 1 datediff(day,CON.DATLME,OCH.DATOCO)            
                   FROM RODOCO AS OCO(NOLOCK)            
                    INNER JOIN RODOCH AS OCH(NOLOCK)            
                    ON OCO.CODIGO = OCH.CODOCO            
                    AND NFC.ID_NFC = OCH.ID_NFC            
             WHERE            
     OCO.CODIGO IN(1)  
     OR OCO.REPAGE = 'S'  
     OR OCO.FINENT = 'S'  
     ORDER BY OCH.ID_OCH DESC) AS DIAS_ATRASOS,    
      (SELECT top 1 OCO.CODIGO            
        FROM RODOCO AS OCO (NOLOCK)            
        INNER JOIN RODOCH AS OCH(NOLOCK)   
  ON OCO.CODIGO = OCH.CODOCO            
        AND NFC.ID_NFC = OCH.ID_NFC  
        WHERE (OCO.CODIGO = 1)  
  OR (OCO.FINENT = 'S')  
  --OR (OCO.ISEPER = 'S')  
  ORDER BY OCH.ID_OCH DESC) AS  COD_OCO_FINALIZ,                  
       (SELECT top 1 OCO.DESCRI            
        FROM RODOCO AS OCO (NOLOCK)            
        INNER JOIN RODOCH AS OCH (NOLOCK)  
  ON OCO.CODIGO = OCH.CODOCO            
        AND NFC.ID_NFC = OCH.ID_NFC   
        WHERE  (OCO.CODIGO = 1)  
  OR (OCO.FINENT = 'S')  
  --OR (OCO.ISEPER = 'S')  
        ORDER BY OCH.ID_OCH DESC) AS  OCORRENCIA_FINALIZ,   
   ISNULL((SELECT top 1 OCO.ISEPER       
                FROM             
                    RODOCH AS OCH(NOLOCK)            
                    INNER JOIN RODOCO AS OCO(NOLOCK)            
                           ON OCO.CODIGO = OCH.CODOCO            
                           AND NFC.ID_NFC = OCH.ID_NFC   
                order by OCH.DATATU desc),'N') AS ISENTA_PERFORMACE,  
             DBO.F_DIAS_UTEIS(CON.DATCAD,(SELECT top 1 OCH.DATOCO        
                FROM RODOCH AS OCH(NOLOCK)            
                    INNER JOIN RODOCO AS OCO(NOLOCK)            
                           ON OCO.CODIGO = OCH.CODOCO            
                           AND NFC.ID_NFC = OCH.ID_NFC   
             WHERE            
    (OCO.CODIGO IN (1))  
    OR (OCO.FINENT = 'S')          
    OR (OCO.REPAGE = 'S')  
    ORDER BY OCH.ID_OCH DESC)) AS D_PRAZO_REALIZADO,                
 coalesce((SELECT DISTINCT CAST(H1.CODOCO AS VARCHAR(003)) +'-' + O.DESCRI +'/' AS [text()]  
  from RODOCH H1(NOLOCK),RODOCO O(NOLOCK) WHERE H1.ID_NFC = NFC.ID_NFC   
  AND O.CODIGO = H1.CODOCO        
  FOR XML PATH(''),TYPE).value('.[1]','Varchar(max)'),'') as Ocorrencias_da_NF  
 ,  
  
 (SELECT TOP 1 MANT.CODMAN  
        FROM RODMAN MANT (nolock), RODIMA IMA_T (nolock)  
          WHERE MANT.CODFIL = IMA_T.FILMAN   
          AND MANT.SERMAN = IMA_T.SERMAN  
          AND MANT.CODMAN = IMA_T.CODMAN  
    AND IMA_T.FILDOC = CON.CODFIL   
          AND IMA_T.SERDOC = CON.SERCON  
          AND IMA_T.CODDOC = CON.CODCON  
    AND MANT.TIPMAN = '2') AS MANIFESTO_TRANSF,   
  (SELECT TOP 1 MAN.CODFIL  
        FROM RODMAN MANT (nolock), RODIMA IMA_T (nolock)  
          WHERE MANT.CODFIL = IMA_T.FILMAN   
          AND MANT.SERMAN = IMA_T.SERMAN  
          AND MANT.CODMAN = IMA_T.CODMAN  
    AND IMA_T.FILDOC = CON.CODFIL   
          AND IMA_T.SERDOC = CON.SERCON  
          AND IMA_T.CODDOC = CON.CODCON  
    AND MANT.TIPMAN = '2') AS FILIAL_MANIFESTO_TRANSF,  
  (SELECT TOP 1 MANT.SERMAN  
        FROM RODMAN MANT (nolock), RODIMA IMA_T (nolock)  
          WHERE MANT.CODFIL = IMA_T.FILMAN   
          AND MANT.SERMAN = IMA_T.SERMAN  
          AND MANT.CODMAN = IMA_T.CODMAN  
    AND IMA_T.FILDOC = CON.CODFIL   
          AND IMA_T.SERDOC = CON.SERCON  
          AND IMA_T.CODDOC = CON.CODCON  
    AND MANT.TIPMAN = '2') AS SERIE_MANIFESTO_TRANSF,  
  
 STATUS = CASE  
  
  WHEN   
  
   (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) = 0  
  
   AND CONVERT(DATE,CON.DATLME)  
  
    <   
    
    (SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)              
     INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC  
      WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')  
      ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC  
    )  
    
   AND    
  
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'S'     
  
  THEN 'PRAZO'  
  
  WHEN   
  
   (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) > 0  
  
   AND (SELECT dbo.adjustedDate(CONVERT(DATE,CON.DATLME),(SELECT CODITN FROM dbo.RODMUN (NOLOCK),dbo.RODLIN (NOLOCK) WHERE CON.CODLIN = RODLIN.CODLIN AND RODLIN.PONFIM = RODMUN.CODITN),CONVERT(TIME,CON.DATLME)))   
  
    <   
    
    (SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)              
     INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC  
      WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')  
      ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC  
    )  
    
   AND    
  
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'S'  
     
  THEN 'PRAZO'  
  
  WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) = 0  
  
   AND CONVERT(DATE,CON.DATLME)  
  
   >   
    
    (SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)              
     INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC  
      WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')  
      ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC  
    )  
    
   AND   
  
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'S'  
  
  THEN 'PRAZO'  
  
  WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) > 0  
  
   AND (SELECT dbo.adjustedDate(CONVERT(DATE,CON.DATLME),(SELECT CODITN FROM dbo.RODMUN(NOLOCK),dbo.RODLIN(NOLOCK) WHERE CON.CODLIN = RODLIN.CODLIN AND RODLIN.PONFIM = RODMUN.CODITN),CONVERT(TIME,CON.DATLME)))  
  
   >   
    
    (SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)              
     INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC  
      WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')  
      ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC  
    )  
    
   AND   
  
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'S'  
  
  THEN 'PRAZO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) = 0  
  
   AND CONVERT(DATE,CON.DATLME)  
     
   <   
    
    (SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)              
     INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC  
      WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')  
      ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC  
    )  
    
   AND  
  
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'N'    
  
  THEN 'ATRASO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) > 0  
  
   AND (SELECT dbo.adjustedDate(CONVERT(DATE,CON.DATLME),(SELECT CODITN FROM dbo.RODMUN(NOLOCK),dbo.RODLIN(NOLOCK) WHERE CON.CODLIN = RODLIN.CODLIN AND RODLIN.PONFIM = RODMUN.CODITN),CONVERT(TIME,CON.DATLME)))  
     
   <   
    
    (SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)              
     INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC  
      WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')  
      ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC  
    )  
    
   AND  
  
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'N'  
    
  THEN 'ATRASO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) = 0  
     
   AND CONVERT(DATE,CON.DATLME)  
       
   >   
    
    (SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)              
     INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC  
      WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')  
      ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC  
    )  
    
   AND   
  
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'N'  
  
  THEN 'PRAZO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) > 0  
     
   AND (SELECT dbo.adjustedDate(CONVERT(DATE,CON.DATLME),(SELECT CODITN FROM dbo.RODMUN(NOLOCK),dbo.RODLIN(NOLOCK) WHERE CON.CODLIN = RODLIN.CODLIN AND RODLIN.PONFIM = RODMUN.CODITN),CONVERT(TIME,CON.DATLME)))  
       
   >   
    
    (SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)              
     INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC  
      WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')  
      ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC  
    )  
    
   AND   
  
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'N'  
  
  THEN 'PRAZO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) = 0  
  
   AND   
     
    ISNULL( CONVERT(DATE,CON.DATLME),'') = ''   
    
   AND   
    
    (SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)              
     INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC  
      WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')  
      ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC  
    )  
    
   < CONVERT(DATE,GETDATE())   
    
   AND   
    
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'N'  
  
  THEN 'ATRASO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) > 0  
  
   AND   
     
    ISNULL( CONVERT(DATE,CON.DATLME),'') = ''   
    
   AND   
    
    (SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)              
     INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC  
      WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')  
      ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC  
    )  
    
   < CONVERT(DATE,GETDATE())   
    
   AND   
    
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'N'  
  
  THEN 'ATRASO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) = 0  
    
   AND CONVERT(DATE,GETDATE()) >  
  
    CONVERT(DATE,CON.DATLME)  
    
   AND   
    
    ISNULL((SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC   
    WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')   
    ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC),'') = ''   
    
   AND   
    
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'N'  
  
  THEN 'ATRASO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) > 0  
    
   AND CONVERT(DATE,GETDATE()) >  
  
    (SELECT dbo.adjustedDate(CONVERT(DATE,CON.DATLME),(SELECT CODITN FROM dbo.RODMUN(NOLOCK),dbo.RODLIN(NOLOCK) WHERE CON.CODLIN = RODLIN.CODLIN AND RODLIN.PONFIM = RODMUN.CODITN),CONVERT(TIME,CON.DATLME)))  
    
   AND   
    
    ISNULL((SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC   
    WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')   
    ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC),'') = ''   
    
   AND   
    
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'N'  
  
  THEN 'ATRASO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) = 0  
     
   AND CONVERT(DATE,GETDATE()) >=  
  
    CONVERT(DATE,CON.DATLME)  
    
   AND   
    
    ISNULL((SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC   
    WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')   
    ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC),'') = ''   
    
   AND   
    
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'S'  
  
  THEN 'PRAZO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) > 0  
     
   AND CONVERT(DATE,GETDATE()) >=  
  
    (SELECT dbo.adjustedDate(CONVERT(DATE,CON.DATLME),(SELECT CODITN FROM dbo.RODMUN(NOLOCK),dbo.RODLIN(NOLOCK) WHERE CON.CODLIN = RODLIN.CODLIN AND RODLIN.PONFIM = RODMUN.CODITN),CONVERT(TIME,CON.DATLME)))  
    
   AND   
    
    ISNULL((SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC   
    WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')   
    ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC),'') = ''   
    
   AND   
    
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'S'  
  
  THEN 'PRAZO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) = 0  
    
   AND CONVERT(DATE,GETDATE()) <=  
  
    CONVERT(DATE,CON.DATLME)  
     
   AND   
    
    ISNULL((SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC   
    WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')   
    ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC),'') = ''   
    
   AND   
    
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'N'  
  
  THEN 'PRAZO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) > 0  
    
   AND CONVERT(DATE,GETDATE()) <=  
  
    (SELECT dbo.adjustedDate(CONVERT(DATE,CON.DATLME),(SELECT CODITN FROM dbo.RODMUN(NOLOCK),dbo.RODLIN(NOLOCK) WHERE CON.CODLIN = RODLIN.CODLIN AND RODLIN.PONFIM = RODMUN.CODITN),CONVERT(TIME,CON.DATLME)))  
     
   AND   
    
    ISNULL((SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC   
    WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')   
    ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC),'') = ''   
    
   AND   
    
    ISNULL((SELECT top 1 OCO.ISEPER FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND NFC.ID_NFC = OCH.ID_NFC ORDER BY OCH.DATATU DESC),'N') = 'N'  
  
  THEN 'PRAZO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) = 0  
    
   AND CONVERT(DATE,CON.DATLME)  
    
   =   
    
   (SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)   
   INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC   
   WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')   
   ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC)    
  
  THEN 'PRAZO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) > 0  
    
   AND (SELECT dbo.adjustedDate(CONVERT(DATE,CON.DATLME),(SELECT CODITN FROM dbo.RODMUN(NOLOCK),dbo.RODLIN(NOLOCK) WHERE CON.CODLIN = RODLIN.CODLIN AND RODLIN.PONFIM = RODMUN.CODITN),CONVERT(TIME,CON.DATLME)))  
    
   =   
    
   (SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)   
   INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC   
   WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')   
   ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC)    
  
  THEN 'PRAZO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) = 0  
    
   AND CONVERT(DATE,GETDATE()) =  
  
    CONVERT(DATE,CON.DATLME)     
    
   AND  
    
    ISNULL((SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC   
    WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')   
    ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC),'') = ''   
  
  THEN 'PRAZO'  
  
   WHEN (SELECT COUNT(OCH.CODOCO) FROM RODOCH AS OCH(NOLOCK) WHERE OCH.ID_NFC = NFC.ID_NFC AND (OCH.CODOCO IN (146,76))) > 0  
    
   AND CONVERT(DATE,GETDATE()) =  
  
    (SELECT dbo.adjustedDate(CONVERT(DATE,CON.DATLME),(SELECT CODITN FROM dbo.RODMUN(NOLOCK),dbo.RODLIN(NOLOCK) WHERE CON.CODLIN = RODLIN.CODLIN AND RODLIN.PONFIM = RODMUN.CODITN),CONVERT(TIME,CON.DATLME)))     
    
   AND  
    
    ISNULL((SELECT top 1 isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) FROM RODOCH AS OCH(NOLOCK)   
    INNER JOIN RODOCO AS OCO(NOLOCK) ON OCO.CODIGO = OCH.CODOCO AND OCH.ID_NFC = NFC.ID_NFC   
    WHERE (OCO.CODIGO IN (1)) OR (OCO.FINENT = 'S')   
    ORDER BY isnull(CONVERT(DATE,NFC.DATENT),CONVERT(DATE,OCH.DATOCO)) DESC),'') = ''   
  
  THEN 'PRAZO'  
  
  ELSE 'PRAZO'  
  
 END  ,
 (SELECT DBO.F_SITUACAO_OCS(CON.CODCON,CON.SERCON,CON.CODFIL,CON.CODREM,NFC.SERIEN,NFC.NOTFIS,NULL)) AS STATUS_OPERACIONAL 
 , VEN.CODVEN
 , VEN.NOMEVE
FROM dbo.RODCON AS CON (NOLOCK)              
    INNER JOIN dbo.RODFIL AS FIL   (NOLOCK)    ON               
    CON.CODFIL = FIL.CODFIL               
    INNER JOIN dbo.RODCLI AS CPAG   (NOLOCK)   ON               
    CON.CODPAG = CPAG.CODCLIFOR               
    LEFT OUTER JOIN dbo.RODMUN AS MUNORI  (NOLOCK)  ON               
    CON.MUNCOL = MUNORI.CODMUN               
    INNER JOIN dbo.RODCLI AS CREM     (NOLOCK)   ON              
    CON.CODREM = CREM.CODCLIFOR              
    INNER JOIN RODMUN AS MREM         (NOLOCK)   ON                  
    CREM.CODMUN = MREM.CODMUN              
    INNER JOIN dbo.RODCLI AS CDES    (NOLOCK)  ON               
    CON.CODDES = CDES.CODCLIFOR               
    INNER JOIN dbo.RODMUN AS MUNDES   (NOLOCK)   ON               
    CDES.CODMUN = MUNDES.CODMUN               
    LEFT OUTER JOIN dbo.RODFRA FRA (NOLOCK)ON               
    CON.TABPAD = FRA.CODFRE              
    LEFT OUTER JOIN dbo.RODCMO CMO (NOLOCK)ON              
    FRA.CODCMO = CMO.CODCMO              
    LEFT OUTER JOIN dbo.RODIIF IIF (NOLOCK)ON              
    CON.ID_RODIIF = IIF.ID_RODIIF              
    LEFT OUTER JOIN dbo.RODCLI AS TENT    (NOLOCK)  ON               
    CON.TERENT = TENT.CODCLIFOR              
    LEFT OUTER JOIN dbo.RODMUN AS MTENT    (NOLOCK)  ON               
    TENT.CODMUN = MTENT.CODMUN               
	LEFT OUTER JOIN dbo.RODFIL AS FILRES (NOLOCK) ON  
	MTENT.FILRES = FILRES.CODFIL  
    LEFT OUTER JOIN CRMREG AS REG_O       (NOLOCK)   ON              
    CON.REGREM = REG_O.CODREG              
	LEFT OUTER JOIN CRMREG AS REG_D ON  
	CON.CODREG = REG_D.CODREG  
    LEFT OUTER JOIN RODMAN MAN            (NOLOCK)   ON              
    CON.FILMAN=MAN.CODFIL              
    AND CON.SERMAN=MAN.SERMAN              
    AND CON.CODMAN=MAN.CODMAN              
    INNER JOIN RODNFC NFC                (NOLOCK)    ON              
    CON.CODFIL = NFC.CODFIL         
    AND CON.SERCON = NFC.SERCON              
	AND CON.CODCON = NFC.CODCON                          
	LEFT OUTER JOIN RECVEN VEN (NOLOCK) ON VEN.CODVEN = CPAG.CODVEN
WHERE                   
   DATEDIFF(MONTH,CAST(CON.DATCAD AS DATE),CAST(GETDATE() AS DATE)) <= 5	
   AND CON.CODCON = 444443
   AND (CON.SITUAC IN ('E', 'D'))  
   AND (CON.TIPCON IN ('A','G','N','O','R','S','U','P','C','D','H','I','M','V')) --Complementar, Devolução Total ou Parcial  
   AND NOT EXISTS (SELECT top 1  OCH.DATOCO          
    FROM RODOCH AS OCH(NOLOCK)                   
    WHERE  (OCH.CODOCO IN (105,133))    
    AND NFC.ID_NFC = OCH.ID_NFC              
    ORDER BY OCH.DATOCO DESC)  