-- LISTA CAD. COMPRAS
-- AUTOR: KELSEN LIMA

SELECT NOME, 
LOGIN, 
ATIVO AS SITUACAO_CAD,
PEDAPR AS APROVA_PED,
PEDLIB AS LIBERA_PED,
VLRLBR AS VLR_LIBERA_PED, 
VLRAPR AS VLR_APROVA_PED,
USUAPR AS APROVA_REQ,
USULIB AS LIBERA_REQ
FROM RODOPE
WHERE ATIVO = 'S'

AND PEDAPR = 'S'
AND PEDLIB = 'S'