-- LISTA USUARIOS WEBCAC
-- AUTOR: KELSEN LIMA

USE db_visual_rodopar

-- LISTA USUARIOS CADASTRADOS NO VR WEBSAC
select * from web_usuario

-- ATUALIZA SENHA DE ACESSO VR WEBSAC
UPDATE WEB_USUARIO SET SENHA = 'EH[oQFmY' WHERE EMAIL = 'adm@datapar.com.br'



