-- PAINEL ANALISE DIARIA DE VOLUME
-- AUTOR: KELSEN LIMA

/****** Object:  View [dbo].[VBI_PAINEL_ANALISE_DIARIA_VOLUME]    Script Date: 10/09/2019 12:08:59 ******/
DROP VIEW [dbo].[VBI_PAINEL_ANALISE_DIARIA_VOLUME]
GO

/****** Object:  View [dbo].[VBI_PAINEL_ANALISE_DIARIA_VOLUME]    Script Date: 10/09/2019 12:08:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VBI_PAINEL_ANALISE_DIARIA_VOLUME] AS
--# CTRC # -
SELECT
	'CTRC' AS TIPDOC,
	CON.TIPCON AS TIPCON,
	CON.SITUAC AS SITUAC,
	convert(char(1),iif(CON.SITDUP is null,'E',CON.SITDUP)) as SITDUP,
	CON.DATCAD AS DATA, 
	CON.NATOPE AS CODFIS,
	CON.DIFERE AS DIFERENCIAL, 
	FIL.NOMEAB AS FILIAL,    
	CON.CODFIL AS COD_FILIAL, 
	FIL.CODCGC AS CNPJ_TRANSPORTADOR,
	CON.SERCON AS SERIE,
	CON.CODCON AS DOCUMENTO,
		(SELECT TOP 1 O.FILORD
				FROM
					RODORC O (nolock)
				WHERE
					CON.CODFIL = O.FILCON
					AND CON.SERCON = O.SERCON
					AND CON.CODCON = O.CODCON) AS FIL_MINUTA
		, (SELECT TOP 1 O.SERORD
				FROM
					RODORC O (nolock)
				WHERE
					CON.CODFIL = O.FILCON
					AND CON.SERCON = O.SERCON
					AND CON.CODCON = O.CODCON) AS SER_MINUTA
		, (SELECT TOP 1 O.CODORD
				FROM
					RODORC O (nolock)
				WHERE
					CON.CODFIL = O.FILCON
					AND CON.SERCON = O.SERCON
					AND CON.CODCON = O.CODCON) AS COD_MINUTA
		, (SELECT TOP 1 CSC.FILOCS
				FROM
					RODCSC CSC (nolock)
				WHERE
					CON.CODFIL = CSC.FILCON
					AND CON.SERCON = CSC.SERCON
					AND CON.CODCON = CSC.CODCON) AS FIL_OCS
		, (SELECT TOP 1 CSC.SEROCS
				FROM
					RODCSC CSC (nolock)
				WHERE
					CON.CODFIL = CSC.FILCON
					AND CON.SERCON = CSC.SERCON
					AND CON.CODCON = CSC.CODCON) AS SER_OCS
		, (SELECT TOP 1 CSC.CODOCS
				FROM
					RODCSC CSC (nolock)
				WHERE
					CON.CODFIL = CSC.FILCON
					AND CON.SERCON = CSC.SERCON
					AND CON.CODCON = CSC.CODCON) AS COD_OCS,
	CON.CODLIN AS LINHA,
	MUNORI.DESCRI AS MUN_ORIGEM, 
	MUNORI.ESTADO AS EST_ORIGEM, 
	CON.LOCENT AS MUN_DESTINO, 
	CON.ESTDES AS EST_DESTINO,
	VEI_FRO.DESCRI AS FROTA_VEICULO,
	VEI_CAV.CODVEI AS CODVEI, 
	VEI_CAV.PROPRI AS CV_PROPRI,
	VEI_CAV.CODPRO AS COD_PROPRIETARIO,
	PROP.CODCGC AS CNPJ_PROPRIETARIO,
	PROP.CODCPF AS CPF_PROPRIETATIO,
	PROP.RAZSOC AS NOME_PROPRIETATIO,
	PROP.FISJUR,
	VEI_CAV.PROPRI AS FROTA,
	VEI_CAV.NUMVEI  AS PLACA_CM, 
	VEI_CR_1.NUMVEI AS PLACA_CR_1,
	VEI_CR_2.NUMVEI AS PLACA_CR_2,
	CON.CODMOT,
	MOT.NOMMOT AS MOTORISTA,
	MOT.NUMCPF AS CPF_MOTORISTA, 
	(SELECT TOP 1 MOTM.NOMMOT
		FROM RODMAN AS MAN (nolock)
		INNER JOIN RODMOT AS MOTM (nolock) ON 
		MAN.CODMO1 = MOTM.CODMOT
		WHERE (MAN.CODFIL= CON.FILMAN) 
		AND (MAN.SERMAN = CON.SERMAN) 
		AND (MAN.CODMAN = CON.CODMAN)) AS MOT_MANIFESTO, 
	CPAG.CODCLIFOR AS COD_PAGADOR, 
	CPAG.CODCGC AS PAG_CNPJ,
	CAST(CPAG.INSCRI AS VARCHAR) AS PAG_INSCRI,
	CPAG.RAZSOC AS PAGADOR, 
	CPAG.NOMEAB AS NOME_ABREVIADO,
	MCPAG.ESTADO AS EST_PAGADOR,
	CPAG.CODCGR AS COD_GRUPO,
	CGR.DESCRI AS GRUPO,
	CPAG.CODVEN AS COD_VENDEDOR,
	VEND.NOMEVE AS NOME_VENDEDOR,
	CREM.CODVEN AS COD_VENDEDOR_REM,
	REMV.NOMEVE AS VENDEDOR_REM,
	CCONS.CODVEN AS COD_VENDEDOR_CONS,
	CONSV.NOMEVE AS VENDEDOR_CONS,
	CDES.CODVEN AS COD_VENDEDOR_DES,
	DESV.NOMEVE AS VENDEDOR_DES, 
	CCONS.RAZSOC AS CONSIGNATARIO,
	CREM.CODCLIFOR AS COD_REMETENTE,
	CREM.CODCGC AS REM_CNPJ,
	CAST(CREM.INSCRI AS VARCHAR) AS REM_INSCRI,
	CREM.RAZSOC AS REMETENTE,
	MREM.DESCRI AS MUN_REMETENTE,
	MREM.ESTADO AS EST_REMETENTE,
	CDES.CODCLIFOR AS COD_DESTINATARIO,
	CDES.CODCGC AS DES_CNPJ, 
	CASE ISNULL(CON.ID_ENDENT, 0)
		WHEN 0 THEN CAST(CDES.INSCRI AS VARCHAR)
		ELSE (SELECT CAST(INSCRI AS VARCHAR) FROM RODEND E (nolock) 
				WHERE CON.ID_ENDENT = E.ID)               
		END DES_INSCRI,
	CDES.CODCEP AS CEP_DESTINO,
	CAST(ISNULL(CDES.TIPLOG,'') AS VARCHAR) AS LOGRAD_DESTINO,
	CDES.NUMERO,
	CDES.ENDERE AS END_DESTINO,
	CDES.BAIRRO AS BAIRRO_DESTINO,
	CDES.RAZSOC AS DESTINATARIO,
	MUNDES.DESCRI AS MUN_DESTINATARIO,
	MUNDES.ESTADO AS EST_DESTINATARIO,
	CRED.RAZSOC AS REDESPACHO,
	CAST(ISNULL(CRED.TIPLOG,'') AS VARCHAR) AS LOGRAD_REDESPACHO, 
	CRED.NUMERO AS NUM_REDESPACHO,
	CRED.ENDERE AS END_REDESPACHO,    
	TCOL.CODCLIFOR AS COD_TCOLETA,
	TCOL.CODCGC AS TCOL_CNPJ,
	CAST(TCOL.INSCRI AS VARCHAR) AS TCOL_INSCRI,
	TCOL.RAZSOC AS TCOLETA,
	MTCOL.DESCRI AS MUN_TCOLETA,
	MTCOL.ESTADO AS EST_TCOLETA,
	TENT.CODCLIFOR AS COD_TENTREGA,
	TENT.CODCGC AS TENT_CNPJ,
	CAST(TENT.INSCRI AS VARCHAR) AS TENT_INSCRI,
	TENT.RAZSOC AS TENTREGA,
	MTENT.DESCRI AS MUN_TENTREGA,
	MTENT.ESTADO AS EST_TENTREGA,
	MAGC.DESCRI AS MUN_AG_CARGA,
	MAGC.ESTADO AS EST_AG_CARGA,
	CON.ORDCOM AS REF_CLIENT,
	NULL AS RECEBEDOR, 
	(SELECT TOP 1 DUP.DATEMI
		FROM dbo.RODDUP DUP (nolock)
				INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
										DUP.NUMDUP = IDU.NUMDUP
		WHERE IDU.FILDOC = CON.CODFIL 
			AND IDU.SERDOC = CON.SERCON
			AND IDU.CODDOC = CON.CODCON
			AND DUP.SITUAC NOT IN ('C', 'I')
			AND IDU.TIPDOC = 'CTRC')    AS DT_EMISSAO_DUP,        
	(SELECT TOP 1 IDU.CODFIL
		FROM dbo.RODDUP DUP (nolock)
				INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
										DUP.NUMDUP = IDU.NUMDUP
		WHERE IDU.FILDOC = CON.CODFIL 
			AND IDU.SERDOC = CON.SERCON
			AND IDU.CODDOC = CON.CODCON
			AND DUP.SITUAC NOT IN ('C', 'I')
			AND IDU.TIPDOC = 'CTRC')    AS COD_FILIAL_DUP,    
	(SELECT TOP 1 IDU.NUMDUP
		FROM dbo.RODDUP DUP (nolock)
				INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
										DUP.NUMDUP = IDU.NUMDUP
		WHERE IDU.FILDOC = CON.CODFIL 
			AND IDU.SERDOC = CON.SERCON
			AND IDU.CODDOC = CON.CODCON
			AND DUP.SITUAC NOT IN ('C', 'I')
			AND IDU.TIPDOC = 'CTRC')    AS COD_FATURA, 
(SELECT TOP 1 DUP.VLRDUP
		FROM dbo.RODDUP DUP (nolock)
				INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
										DUP.NUMDUP = IDU.NUMDUP
		WHERE IDU.FILDOC = CON.CODFIL 
			AND IDU.SERDOC = CON.SERCON
			AND IDU.CODDOC = CON.CODCON
			AND DUP.SITUAC NOT IN ('C', 'I')
			AND IDU.TIPDOC = 'CTRC')    AS VALOR_DUP,    
	(SELECT TOP 1 DUP.DATVEN
		FROM dbo.RODDUP DUP (nolock)
				INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
										DUP.NUMDUP = IDU.NUMDUP
		WHERE IDU.FILDOC = CON.CODFIL 
			AND IDU.SERDOC = CON.SERCON
			AND IDU.CODDOC = CON.CODCON
			AND DUP.SITUAC NOT IN ('C', 'I')
			AND IDU.TIPDOC = 'CTRC') AS DT_VENC_DUP,  
		(SELECT TOP 1 REC.DATLAN
		FROM dbo.RODDUP DUP (nolock)
				INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
										DUP.NUMDUP = IDU.NUMDUP
				INNER JOIN RECMEN REC (nolock) ON DUP.CODFIL = REC.CODFIL AND
										CAST(DUP.NUMDUP AS VARCHAR(15)) = REC.NUMDUP
        		 							  								                                                  
		WHERE IDU.FILDOC = CON.CODFIL 
			AND IDU.SERDOC = CON.SERCON
			AND IDU.CODDOC = CON.CODCON
			AND DUP.SITUAC NOT IN ('C', 'I')
			AND IDU.TIPDOC = 'CTRC' 
			AND REC.DEBCRE = 'C'
			ORDER BY REC.DATLAN DESC)    AS DT_REC_FATURA,  

		(SELECT TOP 1 REC.VLRLIQ
		FROM dbo.RODDUP DUP (nolock)
				INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
										DUP.NUMDUP = IDU.NUMDUP
				INNER JOIN RECMEN REC (nolock) ON DUP.CODFIL = REC.CODFIL AND
						CAST(DUP.NUMDUP AS VARCHAR(15)) = REC.NUMDUP
        		 							  								                                                  
		WHERE IDU.FILDOC = CON.CODFIL 
			AND IDU.SERDOC = CON.SERCON
			AND IDU.CODDOC = CON.CODCON
			AND DUP.SITUAC NOT IN ('C', 'I')
			AND IDU.TIPDOC = 'CTRC' 
			AND REC.DEBCRE = 'C') AS VLR_LIQUIDO,  

		(SELECT TOP 1 DUP.DESCON
		FROM dbo.RODDUP DUP (nolock)
				INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
										DUP.NUMDUP = IDU.NUMDUP
			WHERE IDU.FILDOC = CON.CODFIL 
			AND IDU.SERDOC = CON.SERCON
AND IDU.CODDOC = CON.CODCON
			AND DUP.SITUAC NOT IN ('C', 'I')
			AND IDU.TIPDOC = 'CTRC') AS DESC_CONCEDIDO,
		(SELECT TOP 1 DUP.DESCAN
		FROM dbo.RODDUP DUP (nolock)
				INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
										DUP.NUMDUP = IDU.NUMDUP
			WHERE IDU.FILDOC = CON.CODFIL 
			AND IDU.SERDOC = CON.SERCON
			AND IDU.CODDOC = CON.CODCON
			AND DUP.SITUAC NOT IN ('C', 'I')
			AND IDU.TIPDOC = 'CTRC') AS DESC_ANTECIPADO, 
			NFC.NOTFIS AS NOTA_01, 
			NFC.SERIEN AS SERIE_NF,
			NFC.DATNOT AS DT_NOTA_01,
			NFC.ORDCOM AS REF_CLIENTE,
			NFC.ITECOM AS NOSSA_REF,
			NFC.NOTNFE AS CHAVE_NF,
	CON.NUMINV AS INVOICE,
    CON.NUMAGE AS REF_AGENTE,
	NFC.QUANTI AS QTD_VOL,
	NFC.PESOKG AS PESO,
	NFC.LARGUR AS LARG_CUB,
	NFC.ALTURA AS ALTURA_CUB,
    NFC.PROFUN AS PROFUN_CUB, 
	NFC.PESCUB AS PESO_CUB,
	NFC.PESCAL AS PESO_CALC,
	NFC.VLRMER AS VLR_MERC,
    NFC.VMERSE AS VLR_MERC_SEG,
	NFC.ESPECI AS ESPECIE,
	PRO.DESCRI AS PRODUTO,
	NFC.DATENT AS DATA_ENTREGA,
	PRO.VLRCTN AS VLR_CONTAINER,
    CON.AGECAR AS COD_AG_CARGA,
    AGC.RAZSOC AS NOME_AG_CARGA,
    CON.FREPES AS FRETE_PESO, 
    CON.FREVAL AS FRETE_VALOR,
    CON.DESVAL AS VLR_DESPACHO,
    CON.VLRPED AS VLR_PEDAGIO, 
	CON.ALIISS,
    CON.ALICOT,
	CON.VLRPIS AS PIS_COFINS,
    CON.ICMVLR AS VLR_ICMS, 
	CON.VLRISS AS VLR_ISS,
	CON.BASCAL AS BASE_CALCULO,
    CON.TOTFRE AS VLR_TOTAL_FRETE, 
    CON.VLDES2 AS VLR_DESC2,
    CON.OUTROS AS VLR_OUTROS,
    CON.VLRAJU AS VLR_AJUDANTE,
    CON.VLRCOL AS PLAT_REF_CAR_CC,
    CON.VLRENT AS DGR_DEV_CC,
    CON.VLRCAR AS VLR_CARGA,
    CON.DESCAR AS VLR_DESCARGA,
    CON.TAXDIF AS VLR_TXDIF,
    CON.VLRSUF AS VLR_SUFRAMA,
    CON.SECVAL AS VLR_SECCAT,
    CON.VLRGRI AS VLR_GRIS,
    CON.VLRITR AS SEGURO_CC,
    CON.VLRESC AS VLR_ESCOLTA,
    CON.VLCOMP AS TX_ADICIONAL,  
    CON.OBSCON AS OBSERVACAO,
    CON.TIPOPG,
    CON.TABPAD,
	CON.ID_RODIIF AS ITEM_TARIFA,
    FRA.DESCRI AS DESC_TABELA,
	FRA.CODCMO,
	CMO.DESCRI,
	IIF.VLRFAX,
    CON.NOMNAV AS NAVIO,
    CON.NUMEDI AS DI,
    CON.NUDTAE AS DTA,    
    CON.RESERV AS BL_RESERVA,    
    CON.NUMAWB AS MAWB,
    CON.NUHAWB AS HAWB,
    CON.NUMCTN AS CONTAINER,
    CON.USUATU,
    CON.DDTCHE AS DESC_HR_CHEGADA,
    CON.DDTENT AS DESC_RH_ENTRADA,
    CON.DDTSAI AS DESSC_HR_SAIDA,
    CON.CDTCHE AS CARG_HR_CHEGADA,
    CON.CDTENT AS CARG_HR_ENTRADA,
    CON.CDTSAI AS CARG_HR_SAIDA,
    CON.REGREM AS COD_REG_ORIGEM,
	CON.CODREG AS COD_REG_DESTINO,
	REG_O.DESCRI AS REGIAO_ORIGEM,
	REG_D.DESCRI AS REGIAO_DESTINO,
	 (SELECT TOP 1 MAN.CODMAN
        FROM RODMAN MAN (nolock)
          WHERE MAN.CODFIL = CON.FILMAN 
          AND MAN.SERMAN = CON.SERMAN
          AND MAN.CODMAN = CON.CODMAN
		  AND MAN.TIPMAN <> '2') AS MANIFESTO, 
	 (SELECT TOP 1 MAN.CODFIL
        FROM RODMAN MAN (nolock)
          WHERE MAN.CODFIL = CON.FILMAN 
          AND MAN.SERMAN = CON.SERMAN
          AND MAN.CODMAN = CON.CODMAN
		  AND MAN.TIPMAN <> '2') AS FILIAL_MANIFESTO,
	 (SELECT TOP 1 MAN.SERMAN
        FROM RODMAN MAN (nolock)
          WHERE MAN.CODFIL = CON.FILMAN 
          AND MAN.SERMAN = CON.SERMAN
          AND MAN.CODMAN = CON.CODMAN
		  AND MAN.TIPMAN <> '2') AS SERIE_MANIFESTO,
	 (SELECT TOP 1 MAN.FILDES
        FROM RODMAN MAN (nolock)
          WHERE MAN.CODFIL = CON.FILMAN 
          AND MAN.SERMAN = CON.SERMAN
          AND MAN.CODMAN = CON.CODMAN
		  AND MAN.TIPMAN <> '2') AS FILIAL_DESTINO,
 TIP0_MAN = CASE
                WHEN MAN.TIPMAN = '1' THEN
                       'LOTAÇÃO'
                WHEN TIPMAN = '2' THEN
                       'TRANSFERÊNCIA'
                WHEN TIPMAN = '3' THEN
                       'FRACIONADA'
                WHEN TIPMAN = '4' THEN
                       'MISTA'
                WHEN TIPMAN = '5' THEN
                       'RODORAPIDO'
                WHEN TIPMAN = '6' THEN
                       'DISTRIBUIÇÃO'
                WHEN TIPMAN = '7' THEN
                       'COLETA'
                WHEN TIPMAN = '8' THEN
                       'REENTREGA'
                WHEN TIPMAN = '9' THEN
                       'DEVOLUÇÃO'
                WHEN TIPMAN = '10' THEN
                       'COMPLEMENTAR'
                WHEN TIPMAN = '11' THEN
                       'VIAGEM'
                WHEN TIPMAN = '12' THEN
                       'RETIRADA'
                WHEN TIPMAN = '13' THEN
                       'TRANSF.AQUAVIARIA'
                WHEN TIPMAN = '14' THEN
                       'AÉREO'
                WHEN TIPMAN = '15' THEN
                       'INTERNACIONAL'
          END,
	 (SELECT TOP 1 MANT.CODMAN
        FROM RODMAN MANT (nolock), RODIMA IMA_T (nolock)
          WHERE MANT.CODFIL = IMA_T.FILMAN 
          AND MANT.SERMAN = IMA_T.SERMAN
          AND MANT.CODMAN = IMA_T.CODMAN
		  AND IMA_T.FILDOC = CON.CODFIL 
          AND IMA_T.SERDOC = CON.SERCON
          AND IMA_T.CODDOC = CON.CODCON
		  AND MANT.TIPMAN = '2') AS MANIFESTO_TRANSF, 
	 (SELECT TOP 1 MAN.CODFIL
        FROM RODMAN MANT (nolock), RODIMA IMA_T (nolock)
          WHERE MANT.CODFIL = IMA_T.FILMAN 
          AND MANT.SERMAN = IMA_T.SERMAN
          AND MANT.CODMAN = IMA_T.CODMAN
		  AND IMA_T.FILDOC = CON.CODFIL 
          AND IMA_T.SERDOC = CON.SERCON
          AND IMA_T.CODDOC = CON.CODCON
		  AND MANT.TIPMAN = '2') AS FILIAL_MANIFESTO_TRANSF,
	 (SELECT TOP 1 MANT.SERMAN
        FROM RODMAN MANT (nolock), RODIMA IMA_T (nolock)
          WHERE MANT.CODFIL = IMA_T.FILMAN 
          AND MANT.SERMAN = IMA_T.SERMAN
          AND MANT.CODMAN = IMA_T.CODMAN
		  AND IMA_T.FILDOC = CON.CODFIL 
          AND IMA_T.SERDOC = CON.SERCON
          AND IMA_T.CODDOC = CON.CODCON
		  AND MANT.TIPMAN = '2') AS SERIE_MANIFESTO_TRANSF,
     (SELECT TOP 1 MANT.FILDES
        FROM RODMAN MANT (nolock)
		  WHERE MAN.CODFIL = CON.FILMAN 
          AND MANT.SERMAN = CON.SERMAN
          AND MANT.CODMAN = CON.CODMAN
		  AND MANT.TIPMAN = '2') AS FILIAL_DESTINO_TRANSF,
	CON.CTEAUT,
	CON.CTE_ID AS CHAVE_CTE,
	CON.CTEPRO AS PROTOC_CTE,
	ISNULL (CON.BLOFAT,'N') AS FAT_BLOQUEADO,
	0 AS ICM_INCENTIVADO,
	'N' AS A_VISTA,
	CON.FILCOT AS FILIAL_COTACAO,
	CON.ESTFEC AS COTACAO,
	CON.DATLME AS PRAZO_ENTREGA,
   (SELECT TOP 1 IFR.METDIA
	FROM RODIFR IFR (nolock)
	WHERE CON.TABPAD=IFR.CODFRE
	AND CON.ID_RODIIF=IIF.ID_RODIIF
	AND IIF.ID_RODIFR=IFR.ID_RODIFR) AS METDIA,
	CON.PREFAT,
	(SELECT top 1 datediff(day,CON.DATLME,OCH.DATOCO)
             FROM
                    RODOCO AS OCO (nolock)
                    LEFT OUTER JOIN RODOCH AS OCH (nolock)
                           ON OCO.CODIGO = OCH.CODOCO
                    LEFT OUTER JOIN RODNFC AS NFC (nolock)
                           ON NFC.ID_NFC = OCH.ID_NFC
             WHERE
                    (NFC.CODFIL = CON.CODFIL)               
                    AND (NFC.SERCON = CON.SERCON)
                    AND (NFC.CODCON = CON.CODCON)
                    AND OCO.CODIGO = 1) AS DIAS_ATRASOS,   
		OCO.CODIGO AS COD_OCORRENCIA,
		OCO.DESCRI AS OCORRENCIA,			    
	(SELECT top 1 OCO.CODIGO
        FROM RODOCO AS OCO (nolock)
        LEFT OUTER JOIN RODOCH AS OCH (nolock) ON 
        OCO.CODIGO = OCH.CODOCO
		LEFT OUTER JOIN RODNFC AS NFC (nolock) ON
		NFC.ID_NFC = OCH.ID_NFC
WHERE (NFC.CODFIL = CON.CODFIL) 
        AND (NFC.SERCON = CON.SERCON) 
        AND (NFC.CODCON = CON.CODCON)
		AND OCO.CODIGO IN (1,19,25,119)) AS  COD_OCO_FINALIZ,
	(SELECT top 1 OCO.DESCRI
        FROM RODOCO AS OCO (nolock)
        LEFT OUTER JOIN RODOCH AS OCH (nolock) ON 
        OCO.CODIGO = OCH.CODOCO
		LEFT OUTER JOIN RODNFC AS NFC (nolock) ON
		NFC.ID_NFC = OCH.ID_NFC
        WHERE (NFC.CODFIL = CON.CODFIL) 
        AND (NFC.SERCON = CON.SERCON) 
        AND (NFC.CODCON = CON.CODCON)
		AND OCO.CODIGO IN (1,19,25,119)) AS  OCORRENCIA_FINALIZ,
	(SELECT  top 1 ISNULL(OSE.NOMFUN, 'SEM CONFERENTE')
		  FROM OSEFUN OSE (nolock)
		  LEFT OUTER JOIN RODRMC RMC (nolock) ON
		  OSE.CODFUN = RMC.CODFUN
		  LEFT OUTER JOIN RODIRC IRC (nolock) ON
		  RMC.CODFIL = IRC.FILRMC 
		  AND RMC.CODRMC = IRC.CODRMC
		  WHERE IRC.FILDOC = CON.CODFIL 
          AND IRC.SERDOC = CON.SERCON
          AND IRC.CODDOC = CON.CODCON
		  AND IRC.TIPDOC = 'C') AS CONF_ROM_CARREGTO,
	 (SELECT top 1 ISNULL(OSE.NOMFUN, 'SEM CONFERENTE')
		  FROM OSEFUN OSE (nolock)
		  LEFT OUTER JOIN RODRMD RMD (nolock) ON
		  OSE.CODFUN = RMD.CODFUN
		  LEFT OUTER JOIN RODIRD IRD (nolock) ON
		  RMD.CODFIL = IRD.CODFIL 
		  AND RMD.CODRMD = IRD.CODRMD
		  WHERE IRD.FILDOC = CON.CODFIL 
          AND IRD.SERDOC = CON.SERCON
          AND IRD.CODDOC = CON.CODCON
		  AND IRD.TIPDOC = 'C') AS CONF_ROM_DESCARGA,
    (SELECT TOP 1 INTD.DATENV
        FROM INTDOC INTD (nolock)
          WHERE INTD.FILDOC = CON.CODFIL 
          AND INTD.SERDOC = CON.SERCON
          AND INTD.CODDOC = CON.CODCON
		  AND INTD.TIPDOC = 'CTE') AS DT_AVERBACAO,
	(SELECT TOP 1 INTD.PROTOC
        FROM INTDOC INTD (nolock)
          WHERE INTD.FILDOC = CON.CODFIL 
          AND INTD.SERDOC = CON.SERCON
          AND INTD.CODDOC = CON.CODCON
		  AND INTD.TIPDOC = 'CTE') AS PROT_AVERBACAO,
	(SELECT TOP 1 OCO.CODIGO
        FROM RODOCO AS OCO (nolock)
        LEFT OUTER JOIN RODOCH AS OCH (nolock) ON 
        OCO.CODIGO = OCH.CODOCO
		LEFT OUTER JOIN RODNFC AS NFC (nolock) ON
		NFC.ID_NFC = OCH.ID_NFC
        WHERE (NFC.CODFIL = CON.CODFIL) 
        AND (NFC.SERCON = CON.SERCON) 
        AND (NFC.CODCON = CON.CODCON)
		ORDER BY OCH.ID_OCH DESC) AS  COD_ULT_OCORRENCIA,
	(SELECT TOP 1 OCO.DESCRI
        FROM RODOCO AS OCO (nolock)
        LEFT OUTER JOIN RODOCH AS OCH (nolock) ON 
        OCO.CODIGO = OCH.CODOCO
		LEFT OUTER JOIN RODNFC AS NFC (nolock) ON
		NFC.ID_NFC = OCH.ID_NFC
        WHERE (NFC.CODFIL = CON.CODFIL) 
        AND (NFC.SERCON = CON.SERCON) 
        AND (NFC.CODCON = CON.CODCON)
		ORDER BY OCH.ID_OCH DESC) AS  ULT_OCORRENCIA,
		S.DESCRI AS SETOR_ENTREGA,
		G.CODGRO AS COD_GERENC_RISCO,
		SITUACAO = CASE 
                WHEN G.SITUAC = 'C' THEN
                       'CANCELADO'
                WHEN G.SITUAC = 'D' THEN
                       'CADASTRADO'
			    WHEN G.SITUAC = 'F' THEN
                       'FINALIZADO'
                END,
		RNC.CODRNC,
		SITUACAO_RNC = CASE 
                WHEN G.SITUAC = 'C' THEN
                       'CANCELADO'
                WHEN G.SITUAC = 'D' THEN
                       'CADASTRADO'
			    WHEN G.SITUAC = 'F' THEN
                       'CONCLUIDO'
				WHEN G.SITUAC = 'O' THEN
                       'ENCERRADO'
                END,
	(SELECT  DBO.F_SITUACAO_OCS(CON.CODCON,CON.SERCON,CON.CODFIL,CREM.CODCLIFOR,NFC.SERIEN,NFC.NOTFIS,NULL)) AS SITUACAO_OS,      
	CPR.ID_CPR AS COMPROVANTE_ENTREGA,
	ISNULL (RED.REDMU2,RED.REDMUN) AS COD_REDESPACHO_PARCEIRO,
	REDC.RAZSOC AS REDESPACHO_PARCEIRO,
	CATEGORIA_DOCUMENTO = CASE 
		WHEN ISNULL(CPAG.SUBTIP,0) <> 0 THEN 
			(SELECT RODCMO.DESCRI FROM RODCMO WHERE CODPAD IN (1) AND TIPMVP = 'P' AND RODCMO.CODCMO = CPAG.SUBTIP)
		WHEN (CON.CODFIL) = 18 AND MUNDES.ESTADO = 'SP' THEN
			'TRANSFERENCIA - MG'
		WHEN (CON.CODFIL) = 14 AND MUNDES.ESTADO = 'RJ' THEN
			'TRANSFERENCIA - RJ'
		ELSE 
			'OUTROS'
		END
FROM
    dbo.RODCON AS CON (nolock)
    INNER JOIN dbo.RODFIL AS FIL (nolock)      ON 
    CON.CODFIL = FIL.CODFIL 
    INNER JOIN dbo.RODLIN  AS LIN (nolock)       ON    
    CON.CODLIN = LIN.CODLIN 
    INNER JOIN dbo.RODCLI AS CPAG (nolock)     ON 
    CON.CODPAG = CPAG.CODCLIFOR 
    INNER JOIN dbo.RODMUN AS MCPAG (nolock)     ON 
    CPAG.CODMUN = MCPAG.CODMUN
    LEFT OUTER JOIN dbo.RODCGR AS CGR (nolock)      ON
    CPAG.CODCGR = CGR.CODCGR
    LEFT OUTER JOIN dbo.RODMUN AS MUNORI (nolock)   ON 
    CON.MUNCOL = MUNORI.CODMUN 
    INNER JOIN dbo.RODCLI AS CREM (nolock)       ON
    CON.CODREM = CREM.CODCLIFOR
    INNER JOIN RODMUN AS MREM (nolock)           ON    
    CREM.CODMUN = MREM.CODMUN
    INNER JOIN dbo.RODCLI AS CDES (nolock)     ON 
    CON.CODDES = CDES.CODCLIFOR 
    INNER JOIN dbo.RODMUN AS MUNDES (nolock)     ON 
    CDES.CODMUN = MUNDES.CODMUN 
    INNER JOIN dbo.RODMOT AS MOT  (nolock)     ON 
    CON.CODMOT = MOT.CODMOT 
    INNER JOIN dbo.RODVEI AS VEI_CAV (nolock)  ON 
    CON.PLACA = VEI_CAV.CODVEI
    LEFT OUTER JOIN dbo.RODFRO AS VEI_FRO (nolock)  ON 
    VEI_CAV.CODFRO = VEI_FRO.CODFRO
    LEFT OUTER JOIN dbo.RODVEI AS VEI_CR_1 (nolock)  ON
    CON.PLACA2 = VEI_CR_1.CODVEI
    LEFT OUTER JOIN dbo.RODVEI AS VEI_CR_2 (nolock) ON    
    CON.PLACA3 = VEI_CR_2.CODVEI
    LEFT OUTER JOIN dbo.RODFRA FRA (nolock) ON 
    CON.TABPAD = FRA.CODFRE
	LEFT OUTER JOIN dbo.RODCMO CMO (nolock) ON
	FRA.CODCMO = CMO.CODCMO
	LEFT OUTER JOIN dbo.RODIIF IIF (nolock) ON
	CON.ID_RODIIF = IIF.ID_RODIIF
    LEFT OUTER JOIN dbo.RODCLI AS TCOL (nolock)   ON 
    CON.TERCOL = TCOL.CODCLIFOR 
    LEFT OUTER JOIN dbo.RODMUN AS MTCOL (nolock)     ON 
    TCOL.CODMUN = MTCOL.CODMUN     
    LEFT OUTER JOIN dbo.RODCLI AS TENT (nolock)     ON 
    CON.TERENT = TENT.CODCLIFOR
    LEFT OUTER JOIN dbo.RODMUN AS MTENT (nolock)     ON 
    TENT.CODMUN = MTENT.CODMUN     
    LEFT OUTER JOIN dbo.RODCLI AS AGC (nolock)       ON
    CON.AGECAR = AGC.CODCLIFOR
    LEFT OUTER JOIN dbo.RODMUN AS MAGC (nolock)     ON 
    AGC.CODMUN = MAGC.CODMUN 
    LEFT OUTER JOIN RECVEN AS VEND (nolock)          ON
    CPAG.CODVEN = VEND.CODVEN
	LEFT OUTER JOIN CRMREG AS REG_O (nolock)         ON
	CON.REGREM = REG_O.CODREG
	LEFT OUTER JOIN CRMREG AS REG_D (nolock)         ON
	CON.CODREG = REG_D.CODREG
	LEFT OUTER JOIN RODMAN MAN (nolock)              ON
	CON.FILMAN=MAN.CODFIL
    AND CON.SERMAN=MAN.SERMAN
	AND CON.CODMAN=MAN.CODMAN
	LEFT OUTER JOIN dbo.RODCLI AS CRED (nolock)     ON 
    CON.CODRED = CRED.CODCLIFOR 
	LEFT OUTER JOIN RECVEN REMV (nolock)            ON
	CREM.CODVEN = REMV.CODVEN
	LEFT OUTER JOIN RECVEN DESV (nolock)            ON
	CREM.CODVEN = DESV.CODVEN
	LEFT OUTER JOIN RECVEN CONSV (nolock)            ON
	CREM.CODVEN = CONSV.CODVEN
	LEFT OUTER JOIN RODCLI CCONS (nolock)            ON
	CON.CODICO = CCONS.CODCLIFOR
	LEFT OUTER JOIN RODCLI PROP (nolock)             ON
	VEI_CAV.CODPRO = PROP.CODCLIFOR
	INNER JOIN RODNFC NFC (nolock)                   ON
	CON.CODFIL = NFC.CODFIL
	AND CON.SERCON = NFC.SERCON
    AND CON.CODCON = NFC.CODCON   
	LEFT OUTER JOIN RODPRO PRO (nolock)              ON    
	NFC.CODPROTR = PRO.CODPROTR
	LEFT OUTER JOIN RODOCH OCH (nolock)              ON
	NFC.ID_NFC = OCH.ID_NFC
	LEFT OUTER JOIN RODOCO OCO (nolock)              ON
	OCH.CODOCO = OCO.CODIGO
	LEFT OUTER JOIN RODSET S (nolock)                ON
	CDES.CODSETCL = S.CODSETCL
	LEFT OUTER JOIN RODGRO G (nolock)                ON
	CON.CODCON=G.CODDOC
	AND CON.CODFIL=G.FILDOC
	AND CON.SERCON=G.SERDOC
	LEFT OUTER JOIN RNCREG RNC (nolock)              ON
	CON.CODCON=RNC.CODDOC
	AND CON.CODFIL=RNC.FILDOC
	AND CON.SERCON=RNC.SERDOC    
	LEFT OUTER JOIN RODDOP DOP (nolock)             ON
	CON.CODCON = DOP.CODDOC
	AND CON.SERCON = DOP.SERDOC
	AND CON.CODFIL = DOP.FILDOC
	AND DOP.TIPDOC = 'CTR'
	LEFT OUTER JOIN RODCPR CPR (nolock)             ON
	DOP.ID_CPR = CPR.ID_CPR
	LEFT OUTER JOIN RODRED RED (nolock) ON
	CON.CODFIL=RED.FILDOC
	AND CON.SERCON=RED.SERDOC
	AND CON.CODCON=RED.CODDOC
	AND RED.TIPDOC='CTR'
	LEFT OUTER JOIN RODCLI REDC (nolock) ON
	ISNULL (RED.REDMU2,RED.REDMUN)=REDC.CODCLIFOR

WHERE     
   (CON.SITUAC NOT IN ('C', 'I'))

   --AND CON.CTEAUT = 'S'


UNION ALL
--# OST # -
SELECT
    'OST' AS TIPDOC,  
    CON.TIPORD AS TIPCON,    
    CON.SITUAC AS SITUAC,  
	IIF(CON.SITDUP IS NULL,'E',CON.SITDUP) AS SITDUP,
	CON.DATCAD AS DATA,
    0 AS CODFIS, 
    CON.DIFERE AS DIFERENCIAL,
	FIL.NOMEAB AS FILIAL, 
    CON.CODFIL AS COD_FILIAL,  
	FIL.CODCGC AS CNPJ_TRANSPORTADOR,
    CON.SERORD AS SERIE, 
    CON.CODIGO AS DOCUMENTO, 
    NULL AS FIL_MINUTA,
    NULL AS SER_MINUTA,
    NULL AS COD_MINUTA,
        (SELECT TOP 1 CSC.FILOCS
             FROM
                    RODSOR CSC (nolock)
             WHERE
                    CON.CODFIL = CSC.FILORD
                    AND CON.SERCON = CSC.SERORD
                    AND CON.CODCON = CSC.CODORD) AS FIL_OCS
       , (SELECT TOP 1 CSC.SEROCS
             FROM
                    RODSOR CSC (nolock)
             WHERE
                    CON.CODFIL = CSC.FILORD
                    AND CON.SERCON = CSC.SERORD
                    AND CON.CODCON = CSC.CODORD)  AS SER_OCS
       , (SELECT TOP 1 CSC.CODOCS
             FROM
                    RODSOR CSC (nolock)
             WHERE
                    CON.CODFIL = CSC.FILORD
                    AND CON.SERCON = CSC.SERORD
                    AND CON.CODCON = CSC.CODORD)  AS COD_OCS,
    CON.CODLIN AS LINHA,
    MUNORI.DESCRI AS MUN_ORIGEM, 
    MUNORI.ESTADO AS EST_ORIGEM, 
    MUNDES.DESCRI AS MUN_DESTINO, 
    MUNDES.ESTADO AS EST_DESTINO, 
    VEI_FRO.DESCRI AS FROTA_VEICULO,
    VEI_CAV.CODVEI AS CODVEI,
    VEI_CAV.PROPRI AS CV_PROPRI,
    VEI_CAV.CODPRO AS COD_PROPRIETARIO,
	PROP.CODCGC AS CNPJ_PROPRIETARIO,
	PROP.CODCPF AS CPF_PROPRIETATIO,
	PROP.RAZSOC AS NOME_PROPRIETATIO,
	PROP.FISJUR,
    VEI_CAV.PROPRI AS FROTA,    
    VEI_CAV.NUMVEI  AS PLACA_CM, 
    VEI_CR_1.NUMVEI AS PLACA_CR_1,
    VEI_CR_2.NUMVEI AS PLACA_CR_2,
    CON.CODMOT,
    MOT.NOMMOT AS MOTORISTA, 
	MOT.NUMCPF AS CPF_MOTORISTA,
	(SELECT TOP 1 MOTM.NOMMOT
	    FROM RODMAN AS MAN (nolock)
        INNER JOIN RODMOT AS MOTM (nolock) ON 
        MAN.CODMO1 = MOTM.CODMOT
        WHERE (MAN.CODFIL= CON.FILMAN) 
        AND (MAN.SERMAN = CON.SERMAN) 
        AND (MAN.CODMAN = CON.CODMAN)) AS MOT_MANIFESTO, 
    CPAG.CODCLIFOR AS COD_PAGADOR, 
    CPAG.CODCGC AS PAG_CNPJ,
    CAST(CPAG.INSCRI AS VARCHAR) AS PAG_INSCRI,
    CPAG.RAZSOC AS PAGADOR, 
    CPAG.NOMEAB AS NOME_ABREVIADO,
    MCPAG.ESTADO AS EST_PAGADOR,
    CPAG.CODCGR AS COD_GRUPO,
    CGR.DESCRI AS GRUPO,
	CPAG.CODVEN AS COD_VENDEDOR,
	VEND.NOMEVE AS NOME_VENDEDOR,
	CREM.CODVEN AS COD_VENDEDOR_REM,
	REMV.NOMEVE AS VENDEDOR_REM,
	CCONS.CODVEN AS COD_VENDEDOR_CONS,
	CONSV.NOMEVE AS VENDEDOR_CONS,
	CDES.CODVEN AS COD_VENDEDOR_DES,
	DESV.NOMEVE AS VENDEDOR_DES, 
	CCONS.RAZSOC AS CONSIGNATARIO,
    CREM.CODCLIFOR AS COD_REMETENTE,
    CREM.CODCGC AS REM_CNPJ,
    CAST(CREM.INSCRI AS VARCHAR) AS REM_INSCRI,
    CREM.RAZSOC AS REMETENTE,
    MREM.DESCRI AS MUN_REMETENTE,
    MREM.ESTADO AS EST_REMETENTE,
    CDES.CODCLIFOR AS COD_DESTINATARIO,
    CDES.CODCGC AS DES_CNPJ,
	CAST(CDES.INSCRI AS VARCHAR) AS DES_INSCRI,
	CDES.CODCEP AS CEP_DESTINO,
	CAST(ISNULL(CDES.TIPLOG,'') AS VARCHAR) AS LOGRAD_DESTINO,
	CDES.NUMERO,
	CDES.ENDERE AS END_DESTINO,
	CDES.BAIRRO AS BAIRRO_DESTINO,
    CDES.RAZSOC AS DESTINATARIO,
    MUNDES.DESCRI AS MUN_DESTINATARIO,
    MUNDES.ESTADO AS EST_DESTINATARIO,
	CRED.RAZSOC AS REDESPACHO,
	CAST(ISNULL(CDES.TIPLOG,'') AS VARCHAR)AS LOGRAD_REDESPACHO,
	CRED.NUMERO AS NUM_REDESPACHO,
	CRED.ENDERE AS END_REDESPACHO, 
	TCOL.CODCLIFOR AS COD_TCOLETA,
    TCOL.CODCGC AS TCOL_CNPJ,
    CAST(TCOL.INSCRI AS VARCHAR)AS TCOL_INSCRI,
    TCOL.RAZSOC AS TCOLETA,
    MTCOL.DESCRI AS MUN_TCOLETA,
    MTCOL.ESTADO AS EST_TCOLETA,
    TENT.CODCLIFOR AS COD_TENTREGA,
    TENT.CODCGC AS TENT_CNPJ,
    CAST(TENT.INSCRI AS VARCHAR) AS TENT_INSCRI,
    TENT.RAZSOC AS TENTREGA,
    MTENT.DESCRI AS MUN_TENTREGA,
    MTENT.ESTADO AS EST_TENTREGA,
    MAGC.DESCRI AS MUN_AG_CARGA,
    MAGC.ESTADO AS EST_AG_CARGA,
    CON.ORDCOM AS REF_CLIENT,
	NULL AS RECEBEDOR,   
    (SELECT TOP 1 DUP.DATEMI
        FROM dbo.RODDUP DUP (nolock)
             INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
                                      DUP.NUMDUP = IDU.NUMDUP
        WHERE IDU.FILDOC = CON.CODFIL 
          AND IDU.SERDOC = CON.SERORD          
          AND IDU.CODDOC = CON.CODIGO
          AND DUP.SITUAC NOT IN ('C', 'I')
          AND IDU.TIPDOC = 'OST')    AS DT_EMISSAO_DUP,    
    (SELECT TOP 1 IDU.CODFIL
        FROM dbo.RODDUP DUP (nolock)
             INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
                                      DUP.NUMDUP = IDU.NUMDUP
        WHERE IDU.FILDOC = CON.CODFIL 
          AND IDU.SERDOC = CON.SERORD          
          AND IDU.CODDOC = CON.CODIGO
          AND DUP.SITUAC NOT IN ('C', 'I')
          AND IDU.TIPDOC = 'OST')    AS COD_FILIAL_DUP,    
     (SELECT TOP 1 IDU.NUMDUP
        FROM dbo.RODDUP DUP (nolock)
             INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
                                      DUP.NUMDUP = IDU.NUMDUP
        WHERE IDU.FILDOC = CON.CODFIL 
          AND IDU.SERDOC = CON.SERORD
          AND IDU.CODDOC = CON.CODIGO
          AND DUP.SITUAC NOT IN ('C', 'I')
          AND IDU.TIPDOC = 'OST')    AS COD_FATURA,  
     (SELECT TOP 1 DUP.VLRDUP
        FROM dbo.RODDUP DUP (nolock)
             INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
                                      DUP.NUMDUP = IDU.NUMDUP
        WHERE IDU.FILDOC = CON.CODFIL 
          AND IDU.SERDOC = CON.SERORD
          AND IDU.CODDOC = CON.CODIGO
          AND DUP.SITUAC NOT IN ('C', 'I')
          AND IDU.TIPDOC = 'OST')    AS VALOR_DUP,
      (SELECT TOP 1 DUP.DATVEN
        FROM dbo.RODDUP DUP (nolock)
             INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
                                      DUP.NUMDUP = IDU.NUMDUP
        WHERE IDU.FILDOC = CON.CODFIL 
          AND IDU.SERDOC = CON.SERORD
          AND IDU.CODDOC = CON.CODIGO
          AND DUP.SITUAC NOT IN ('C', 'I')
          AND IDU.TIPDOC = 'OST')    AS DT_VENC_DUP,          
      (SELECT TOP 1 REC.DATLAN
        FROM dbo.RODDUP DUP (nolock)
             INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
                                      DUP.NUMDUP = IDU.NUMDUP
             INNER JOIN RECMEN REC (nolock) ON DUP.CODFIL = REC.CODFIL AND
                                      CAST(DUP.NUMDUP AS VARCHAR(15)) = REC.NUMDUP                                                   
        WHERE IDU.FILDOC = CON.CODFIL 
          AND IDU.SERDOC = CON.SERCON
          AND IDU.CODDOC = CON.CODCON
          AND DUP.SITUAC NOT IN ('C', 'I')
          AND IDU.TIPDOC = 'OST' 
          AND REC.DEBCRE = 'C'
         ORDER BY REC.DATLAN DESC)    AS DT_REC_FATURA, 

	  (SELECT TOP 1 REC.VLRLIQ
        FROM dbo.RODDUP DUP (nolock)
             INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
                                      DUP.NUMDUP = IDU.NUMDUP
             INNER JOIN RECMEN REC (nolock) ON DUP.CODFIL = REC.CODFIL AND
                                      CAST(DUP.NUMDUP AS VARCHAR(15)) = REC.NUMDUP                                                   
        WHERE IDU.FILDOC = CON.CODFIL 
          AND IDU.SERDOC = CON.SERCON
          AND IDU.CODDOC = CON.CODCON
          AND DUP.SITUAC NOT IN ('C', 'I')
          AND IDU.TIPDOC = 'OST' 
          AND REC.DEBCRE = 'C')  AS VLR_LIQUIDO, 
         

		   (SELECT TOP 1 DUP.DESCON
        FROM dbo.RODDUP DUP (nolock)
		     INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
                                      DUP.NUMDUP = IDU.NUMDUP
          WHERE IDU.FILDOC = CON.CODFIL 
          AND IDU.SERDOC = CON.SERCON
          AND IDU.CODDOC = CON.CODCON
          AND DUP.SITUAC NOT IN ('C', 'I')
          AND IDU.TIPDOC = 'CTRC') AS DESC_CONCEDIDO,
     (SELECT TOP 1 DUP.DESCAN
        FROM dbo.RODDUP DUP (nolock)
		     INNER JOIN RODIDU IDU (nolock) ON DUP.CODFIL = IDU.CODFIL AND
                                      DUP.NUMDUP = IDU.NUMDUP
          WHERE IDU.FILDOC = CON.CODFIL 
          AND IDU.SERDOC = CON.SERCON
          AND IDU.CODDOC = CON.CODCON
          AND DUP.SITUAC NOT IN ('C', 'I')
          AND IDU.TIPDOC = 'CTRC') AS DESC_ANTECIPADO,                    
    	  NFC.NOTFIS AS NOTA_01, 
		  NFC.SERIEN AS SERIE_NF,
		  NFC.DATNOT AS DT_NOTA_01,
		  NFC.ORDCOM AS REF_CLIENTE,
		  NFC.ITECOM AS NOSSA_REF,
		  NFC.NOTNFE AS CHAVE_NF,
	CON.NUMINV AS INVOICE,
    CON.NUMAGE AS REF_AGENTE,
	NFC.QUANTI AS QTD_VOL,
	NFC.PESOKG AS PESO,
	NFC.LARGUR AS LARG_CUB,
	NFC.ALTURA AS ALTURA_CUB,
    NFC.PROFUN AS PROFUN_CUB, 
	NFC.PESCUB AS PESO_CUB,
	NFC.PESCAL AS PESO_CALC,
	NFC.VLRMER AS VLR_MERC,
    NFC.VMERSE AS VLR_MERC_SEG,
	NFC.ESPECI AS ESPECIE,
	PRO.DESCRI AS PRODUTO,
	NFC.DATENT AS DATA_ENTREGA,
	PRO.VLRCTN AS VLR_CONTAINER,
    CON.AGECAR AS COD_AG_CARGA,
    AGC.RAZSOC AS NOME_AG_CARGA,        
    CON.FREPES AS FRETE_PESO, 
    CON.FREVAL AS FRETE_VALOR,
    CON.DESVAL AS VLR_DESPACHO,
    CON.VLRPED AS VLR_PEDAGIO, 
	CON.ALIISS,
    CON.ALICOT,
	CON.VLRPIS AS PIS_COFINS,
    CON.ICMVLR AS VLR_ICMS,
	CON.VLRISS AS VLR_ISS, 
    CON.BASCAL AS BASE_CALCULO,
    CON.TOTFRE AS VLR_TOTAL_FRETE, 
    CON.VLDES2 AS VLR_DESC2,
    CON.OUTROS AS VLR_OUTROS,
    CON.VLRAJU AS VLR_AJUDANTE,
    CON.VLRCOL AS PLAT_REF_CAR_CC,
    CON.VLRENT AS DGR_DEV_CC,
    CON.VLRCAR AS VLR_CARGA,
    CON.DESCAR AS VLR_DESCARGA,
    CON.TAXDIF AS VLR_TXDIF,
    CON.VLRSUF AS VLR_SUFRAMA,
    CON.SECVAL AS VLR_SECCAT,
    CON.VLRGRI AS VLR_GRIS,
    CON.VLRITR AS SEGURO_CC,
    CON.VLRESC AS VLR_ESCOLTA,
    CON.VLCOMP AS TX_ADICIONAL, 
    CON.OBSCON AS OBSERVACAO,
    '' AS TIPOPG,
    CON.TABPAD,
	CON.ID_RODIIF AS ITEM_TARIFA,
    FRA.DESCRI AS DESC_TABELA,
	FRA.CODCMO,
	CMO.DESCRI,
	IIF.VLRFAX,
CON.NOMNAV AS NAVIO,
    CON.NUMEDI AS DI,
    CON.NUDTAE AS DTA,    
    CON.RESERV AS BL_RESERVA,    
    CON.NUMAWB AS MAWB,
    CON.NUHAWB AS HAWB,
    CON.NUMCTN AS CONTAINER,
    CON.USUATU,
    CON.DDTCHE AS DESC_HR_CHEGADA,
    CON.DDTENT AS DESC_RH_ENTRADA,
    CON.DDTSAI AS DESSC_HR_SAIDA,
    CON.CDTCHE AS CARG_HR_CHEGADA,
    CON.CDTENT AS CARG_HR_ENTRADA,
    CON.CDTSAI AS CARG_HR_SAIDA,
    CON.REGREM AS COD_REG_ORIGEM,
	CON.CODREG AS COD_REG_DESTINO,
	REG_O.DESCRI AS REGIAO_ORIGEM,
	REG_D.DESCRI AS REGIAO_DESTINO,
	 (SELECT TOP 1 MAN.CODMAN
        FROM RODMAN MAN 
          WHERE MAN.CODFIL = CON.FILMAN 
          AND MAN.SERMAN = CON.SERMAN
          AND MAN.CODMAN = CON.CODMAN
		  AND MAN.TIPMAN <> '2') AS MANIFESTO, 
	 (SELECT TOP 1 MAN.CODFIL
        FROM RODMAN MAN 
          WHERE MAN.CODFIL = CON.FILMAN 
          AND MAN.SERMAN = CON.SERMAN
          AND MAN.CODMAN = CON.CODMAN
		  AND MAN.TIPMAN <> '2') AS FILIAL_MANIFESTO,
	 (SELECT TOP 1 MAN.SERMAN
        FROM RODMAN MAN 
          WHERE MAN.CODFIL = CON.FILMAN 
          AND MAN.SERMAN = CON.SERMAN
          AND MAN.CODMAN = CON.CODMAN
		  AND MAN.TIPMAN <> '2') AS SERIE_MANIFESTO,
	 (SELECT TOP 1 MAN.FILDES
        FROM RODMAN MAN 
          WHERE MAN.CODFIL = CON.FILMAN 
          AND MAN.SERMAN = CON.SERMAN
          AND MAN.CODMAN = CON.CODMAN
		  AND MAN.TIPMAN <> '2') AS FILIAL_DESTINO,
  TIP0_MAN = CASE
                WHEN MAN.TIPMAN = '1' THEN
                       'LOTAÇÃO'
                WHEN TIPMAN = '2' THEN
                       'TRANSFERÊNCIA'
                WHEN TIPMAN = '3' THEN
                       'FRACIONADA'
                WHEN TIPMAN = '4' THEN
                       'MISTA'
                WHEN TIPMAN = '5' THEN
                       'RODORAPIDO'
                WHEN TIPMAN = '6' THEN
                       'DISTRIBUIÇÃO'
                WHEN TIPMAN = '7' THEN
                       'COLETA'
                WHEN TIPMAN = '8' THEN
                       'REENTREGA'
                WHEN TIPMAN = '9' THEN
                       'DEVOLUÇÃO'
                WHEN TIPMAN = '10' THEN
                       'COMPLEMENTAR'
                WHEN TIPMAN = '11' THEN
                       'VIAGEM'
                WHEN TIPMAN = '12' THEN
                       'RETIRADA'
                WHEN TIPMAN = '13' THEN
                       'TRANSF.AQUAVIARIA'
                WHEN TIPMAN = '14' THEN
                       'AÉREO'
                WHEN TIPMAN = '15' THEN
                       'INTERNACIONAL'
          END,
	 (SELECT TOP 1 MANT.CODMAN
        FROM RODMAN MANT (nolock), RODIMA IMA_T (nolock)
          WHERE MANT.CODFIL = IMA_T.FILMAN 
          AND MANT.SERMAN = IMA_T.SERMAN
          AND MANT.CODMAN = IMA_T.CODMAN
		  AND IMA_T.FILDOC = CON.CODFIL 
          AND IMA_T.SERDOC = CON.SERORD
          AND IMA_T.CODDOC = CON.CODIGO
		  AND MANT.TIPMAN = '2') AS MANIFESTO_TRANSF, 
	 (SELECT TOP 1 MANT.CODFIL
        FROM RODMAN MANT (nolock), RODIMA IMA_T (nolock)
          WHERE MANT.CODFIL = IMA_T.FILMAN 
          AND MANT.SERMAN = IMA_T.SERMAN
          AND MANT.CODMAN = IMA_T.CODMAN
		  AND IMA_T.FILDOC = CON.CODFIL 
          AND IMA_T.SERDOC = CON.SERORD
          AND IMA_T.CODDOC = CON.CODIGO
		  AND MANT.TIPMAN = '2') AS FILIAL_MANIFESTO_TRANSF,
	 (SELECT TOP 1 MANT.SERMAN
        FROM RODMAN MANT (nolock), RODIMA IMA_T (nolock)
          WHERE MANT.CODFIL = IMA_T.FILMAN 
          AND MANT.SERMAN = IMA_T.SERMAN
          AND MANT.CODMAN = IMA_T.CODMAN
		  AND IMA_T.FILDOC = CON.CODFIL 
          AND IMA_T.SERDOC = CON.SERORD
          AND IMA_T.CODDOC = CON.CODIGO
		  AND MANT.TIPMAN = '2') AS SERIE_MANIFESTO_TRANSF,
	 (SELECT TOP 1 MANT.FILDES
        FROM RODMAN MANT (nolock)
		  WHERE MAN.CODFIL = CON.FILMAN 
          AND MANT.SERMAN = CON.SERMAN
          AND MANT.CODMAN = CON.CODMAN
		  AND MANT.TIPMAN = '2') AS FILIAL_DESTINO_TRANSF,
	'S' AS CTEAUT,
	NULL AS CHAVE_CTE,
	NULL AS PROTOC_CTE,
	'N' AS FAT_BLOQUEADO,
	0 AS ICM_INCENTIVADO,
	'N' AS A_VISTA,
	CON.FILCOT AS FILIAL_COTACAO,
	CON.ESTFEC AS COTACAO,
	CON.DATLME AS PRAZO_ENTREGA,
(SELECT TOP 1 IFR.METDIA
	FROM RODIFR IFR (nolock)
	WHERE CON.TABPAD=IFR.CODFRE
	AND CON.ID_RODIIF=IIF.ID_RODIIF
	AND IIF.ID_RODIFR=IFR.ID_RODIFR) AS METDIA,
	CON.PREFAT,
	(SELECT TOP 1 datediff(day,CON.DATLME,OCH.DATOCO)
             FROM
                    RODOCO AS OCO (nolock)
                    LEFT OUTER JOIN RODOCH AS OCH (nolock)
                           ON OCO.CODIGO = OCH.CODOCO
                    LEFT OUTER JOIN RODIOS AS NFC (nolock)
                           ON NFC.ID_IOS = OCH.ID_IOS
             WHERE
                    (NFC.FILORD = CON.CODFIL)               
                    AND (NFC.SERORD = CON.SERORD)
                    AND (NFC.CODORD = CON.CODIGO)
                    AND OCO.CODIGO = 1) AS DIAS_ATRASOS,      
	    OCO.CODIGO AS COD_OCORRENCIA,
		OCO.DESCRI AS OCORRENCIA,
    (SELECT TOP 1 OCO.CODIGO
        FROM RODOCO AS OCO (nolock)
        LEFT OUTER JOIN RODOCH AS OCH (nolock) ON 
        OCO.CODIGO = OCH.CODOCO
		LEFT OUTER JOIN RODIOS AS NFC (nolock) ON
		NFC.ID_IOS = OCH.ID_IOS
        WHERE (NFC.FILORD = CON.CODFIL) 
        AND (NFC.SERORD = CON.SERORD) 
        AND (NFC.CODORD = CON.CODIGO)
		AND OCO.CODIGO IN (1,19,25,119)) AS  COD_OCO_FINALIZ,
	(SELECT TOP 1 OCO.DESCRI
        FROM RODOCO AS OCO (nolock)
        LEFT OUTER JOIN RODOCH AS OCH (nolock) ON 
        OCO.CODIGO = OCH.CODOCO
		LEFT OUTER JOIN RODIOS AS NFC (nolock) ON
		NFC.ID_IOS = OCH.ID_IOS
        WHERE (NFC.FILORD = CON.CODFIL) 
        AND (NFC.SERORD = CON.SERORD) 
        AND (NFC.CODORD = CON.CODIGO)
		AND OCO.CODIGO IN (1,19,25,119)) AS  OCORRENCIA_FINALIZ,
	(SELECT TOP 1 ISNULL(OSE.NOMFUN, 'SEM CONFERENTE')
		  FROM OSEFUN OSE (nolock)
		  LEFT OUTER JOIN RODRMC RMC (nolock) ON
		  OSE.CODFUN = RMC.CODFUN
		  LEFT OUTER JOIN RODIRC IRC (nolock) ON
		  RMC.CODFIL = IRC.FILRMC 
		  AND RMC.CODRMC = IRC.CODRMC
		  WHERE IRC.FILDOC = CON.CODFIL 
          AND IRC.SERDOC = CON.SERORD
          AND IRC.CODDOC = CON.CODIGO
		  AND IRC.TIPDOC = 'O') AS CONF_ROM_CARREGTO,
	 (SELECT TOP 1 ISNULL(OSE.NOMFUN, 'SEM CONFERENTE')
		  FROM OSEFUN OSE (nolock)
		  LEFT OUTER JOIN RODRMD RMD (nolock) ON
		  OSE.CODFUN = RMD.CODFUN
		  LEFT OUTER JOIN RODIRD IRD (nolock) ON
		  RMD.CODFIL = IRD.CODFIL 
		  AND RMD.CODRMD = IRD.CODRMD
		  WHERE IRD.FILDOC = CON.CODFIL 
          AND IRD.SERDOC = CON.SERORD
          AND IRD.CODDOC = CON.CODIGO
		  AND IRD.TIPDOC = 'O') AS CONF_ROM_DESCARGA,
	(SELECT TOP 1 INTD.DATENV
        FROM INTDOC INTD (nolock)
          WHERE INTD.FILDOC = CON.CODFIL 
          AND INTD.SERDOC = CON.SERORD
          AND INTD.CODDOC = CON.CODIGO
		  AND INTD.TIPDOC = 'OST') AS DT_AVERBACAO,
	(SELECT TOP 1 INTD.PROTOC
        FROM INTDOC INTD (nolock)
          WHERE INTD.FILDOC = CON.CODFIL 
          AND INTD.SERDOC = CON.SERORD
          AND INTD.CODDOC = CON.CODIGO
		  AND INTD.TIPDOC = 'OST') AS PROT_AVERBACAO,
	(SELECT TOP 1 OCO.CODIGO
        FROM RODOCO AS OCO (nolock)
        LEFT OUTER JOIN RODOCH AS OCH (nolock) ON 
        OCO.CODIGO = OCH.CODOCO
		LEFT OUTER JOIN RODIOS AS NFC (nolock) ON
		NFC.ID_IOS = OCH.ID_IOS
        WHERE (NFC.FILORD = CON.CODFIL) 
        AND (NFC.SERORD = CON.SERORD) 
        AND (NFC.CODORD = CON.CODIGO)
		ORDER BY OCH.ID_OCH DESC) AS  COD_ULT_OCORRENCIA,
	(SELECT TOP 1 OCO.DESCRI
        FROM RODOCO AS OCO (nolock)
        LEFT OUTER JOIN RODOCH AS OCH (nolock) ON 
        OCO.CODIGO = OCH.CODOCO
		LEFT OUTER JOIN RODIOS AS NFC (nolock) ON
		NFC.ID_IOS = OCH.ID_IOS
        WHERE (NFC.FILORD = CON.CODFIL) 
        AND (NFC.SERORD = CON.SERORD) 
        AND (NFC.CODORD = CON.CODIGO)
		ORDER BY OCH.ID_OCH DESC) AS  ULT_OCORRENCIA,
		S.DESCRI AS SETOR_ENTREGA,
		G.CODGRO AS COD_GERENC_RISCO,
		SITUACAO = CASE 
                WHEN G.SITUAC = 'C' THEN
                       'CANCELADO'
                WHEN G.SITUAC = 'D' THEN
                       'CADASTRADO'
			    WHEN G.SITUAC = 'F' THEN
         'FINALIZADO'
                END,
		RNC.CODRNC,
		SITUACAO_RNC = CASE 
                WHEN G.SITUAC = 'C' THEN
                       'CANCELADO'
                WHEN G.SITUAC = 'D' THEN
                       'CADASTRADO'
			    WHEN G.SITUAC = 'F' THEN
                       'CONCLUIDO'
				WHEN G.SITUAC = 'O' THEN
                       'ENCERRADO'
                END,
	(SELECT  DBO.F_SITUACAO_OCS(CON.CODIGO,CON.SERORD,CON.CODFIL,CREM.CODCLIFOR,NFC.SERIEN,NFC.NOTFIS,NULL)) AS SITUACAO_OS,

         '' AS COMPROVANTE_ENTREGA,
		ISNULL (RED.REDMU2,RED.REDMUN) AS COD_REDESPACHO_PARCEIRO,
		REDC.RAZSOC AS REDESPACHO_PARCEIRO,
	CATEGORIA_DOCUMENTO = CASE 
		WHEN ISNULL(CPAG.SUBTIP,0) <> 0 THEN 
			(SELECT RODCMO.DESCRI FROM RODCMO WHERE CODPAD IN (1) AND TIPMVP = 'P' AND RODCMO.CODCMO = CPAG.SUBTIP)
		WHEN (CON.CODFIL) = 18 AND MUNDES.ESTADO = 'SP' THEN
			'TRANSFERENCIA - MG'
		WHEN (CON.CODFIL) = 14 AND MUNDES.ESTADO = 'RJ' THEN
			'TRANSFERENCIA - RJ'
		ELSE 
			'OUTROS'
		END
FROM
    dbo.RODORD AS CON (nolock)
    INNER JOIN dbo.RODFIL AS FIL (nolock)       ON 
    CON.CODFIL = FIL.CODFIL 
    INNER JOIN dbo.RODLIN AS LIN (nolock)       ON    
    CON.CODLIN = LIN.CODLIN
    INNER JOIN dbo.RODCLI AS CPAG (nolock)     ON 
    CON.CODPAG = CPAG.CODCLIFOR
    INNER JOIN dbo.RODMUN AS MCPAG (nolock)     ON 
    CPAG.CODMUN = MCPAG.CODMUN 
    LEFT OUTER JOIN dbo.RODCGR AS CGR (nolock)       ON
    CPAG.CODCGR = CGR.CODCGR
    INNER JOIN dbo.RODCLI AS CREM (nolock)     ON 
    CON.CODREM = CREM.CODCLIFOR 
    INNER JOIN RODMUN AS MREM (nolock)           ON    
    CREM.CODMUN = MREM.CODMUN
    LEFT OUTER JOIN dbo.RODMUN AS MUNORI (nolock)    ON 
    CREM.CODMUN = MUNORI.CODMUN 
    INNER JOIN dbo.RODCLI AS CDES (nolock)     ON 
    CON.CODDES = CDES.CODCLIFOR 
    INNER JOIN dbo.RODMUN AS MUNDES (nolock)   ON 
    CDES.CODMUN = MUNDES.CODMUN
    INNER JOIN dbo.RODMOT AS MOT (nolock)      ON 
    CON.CODMOT = MOT.CODMOT 
    INNER JOIN dbo.RODVEI AS VEI_CAV (nolock)  ON 
    CON.PLACA = VEI_CAV.CODVEI 
    LEFT OUTER JOIN dbo.RODFRO AS VEI_FRO (nolock)  ON 
    VEI_CAV.CODFRO = VEI_FRO.CODFRO   
    LEFT OUTER JOIN dbo.RODVEI AS VEI_CR_1 (nolock)  ON
    CON.PLACA2 = VEI_CR_1.CODVEI
    LEFT OUTER JOIN dbo.RODVEI AS VEI_CR_2 (nolock)    ON    
    CON.PLACA3 = VEI_CR_2.CODVEI
    LEFT OUTER JOIN dbo.RODFRA FRA (nolock) ON 
    CON.TABPAD = FRA.CODFRE 
    LEFT OUTER JOIN dbo.RODCMO CMO (nolock) ON
	FRA.CODCMO = CMO.CODCMO
	LEFT OUTER JOIN dbo.RODIIF IIF (nolock) ON
    CON.ID_RODIIF = IIF.ID_RODIIF
	LEFT OUTER JOIN dbo.RODCLI AS TCOL (nolock)     ON 
    CON.TERCOL = TCOL.CODCLIFOR
    LEFT OUTER JOIN dbo.RODMUN AS MTCOL (nolock)     ON 
    TCOL.CODMUN = MTCOL.CODMUN     
    LEFT OUTER JOIN dbo.RODCLI AS TENT (nolock)     ON 
    CON.TERENT = TENT.CODCLIFOR 
    LEFT OUTER JOIN dbo.RODMUN AS MTENT (nolock)     ON 
    TENT.CODMUN = MTENT.CODMUN          
    LEFT OUTER JOIN dbo.RODCLI AS AGC (nolock)       ON
    CON.AGECAR = AGC.CODCLIFOR
    LEFT OUTER JOIN dbo.RODMUN AS MAGC (nolock)     ON 
    AGC.CODMUN = MAGC.CODMUN     
    LEFT OUTER JOIN RECVEN AS VEND (nolock)           ON
    CPAG.CODVEN = VEND.CODVEN  
    LEFT OUTER JOIN CRMREG AS REG_O (nolock)         ON
	CON.REGREM = REG_O.CODREG
	LEFT OUTER JOIN CRMREG AS REG_D (nolock)         ON
	CON.CODREG = REG_D.CODREG
	LEFT OUTER JOIN RODMAN MAN (nolock)              ON
	CON.FILMAN=MAN.CODFIL
	AND CON.SERMAN=MAN.SERMAN
	AND CON.CODMAN=MAN.CODMAN
	LEFT OUTER JOIN dbo.RODCLI AS CRED (nolock)     ON 
    CON.CODRED = CRED.CODCLIFOR 
	LEFT OUTER JOIN RECVEN REMV (nolock)            ON
	CREM.CODVEN = REMV.CODVEN
	LEFT OUTER JOIN RECVEN DESV (nolock)            ON
	CREM.CODVEN = DESV.CODVEN
	LEFT OUTER JOIN RECVEN CONSV (nolock)            ON
	CREM.CODVEN = CONSV.CODVEN
	LEFT OUTER JOIN RODCLI CCONS (nolock)            ON
	CON.CODICO = CCONS.CODCLIFOR
    LEFT OUTER JOIN RODCLI PROP (nolock)             ON
	VEI_CAV.CODPRO = PROP.CODCLIFOR
	INNER JOIN RODIOS NFC  (nolock)                  ON
	CON.CODFIL = NFC.FILORD
	AND CON.SERORD = NFC.SERORD
    AND CON.CODIGO = NFC.CODORD   
	LEFT OUTER JOIN RODPRO PRO  (nolock)             ON    
	NFC.CODPROTR = PRO.CODPROTR
	LEFT OUTER JOIN RODOCH OCH (nolock)              ON
	NFC.ID_IOS = OCH.ID_IOS
	LEFT OUTER JOIN RODOCO OCO (nolock)              ON
	OCH.CODOCO = OCO.CODIGO
	LEFT OUTER JOIN RODSET S (nolock)                ON
	CDES.CODSETCL = S.CODSETCL
	LEFT OUTER JOIN RODGRO G (nolock)                ON
	CON.CODIGO=G.CODDOC
	AND CON.CODFIL=G.FILDOC
	AND CON.SERORD=G.SERDOC
	LEFT OUTER JOIN RNCREG RNC (nolock)           ON
	CON.CODIGO=RNC.CODDOC
	AND CON.CODFIL=RNC.FILDOC
	AND CON.SERORD=RNC.SERDOC
	LEFT OUTER JOIN RODRED RED (nolock) ON
	CON.CODFIL=RED.FILDOC
	AND CON.SERORD=RED.SERDOC
	AND CON.CODIGO=RED.CODDOC
	AND RED.TIPDOC='OST'
	LEFT OUTER JOIN RODCLI REDC (nolock) ON
	ISNULL (RED.REDMU2,RED.REDMUN)=REDC.CODCLIFOR

WHERE     
    (CON.SITUAC NOT IN ('C', 'I'))
    AND NOT EXISTS (SELECT 1 FROM RODORC O (nolock) WHERE CON.CODFIL=O.FILORD AND CON.SERORD=O.SERORD AND CON.CODIGO=O.CODORD)
    AND NOT EXISTS (SELECT 1 FROM RODORN O (nolock) WHERE CON.CODFIL=O.FILORD AND CON.SERORD=O.SERORD AND CON.CODIGO=O.CODORD) 
GO
