-- POWER BI PAINEL DE FATURAMENTO CUSTO VEICULO
-- AUTOR: KELSEN LIMA

/****** Object:  View [dbo].[VW_FATURAMENTO_CUSTO_VEICULO_PBI_REV3]    Script Date: 05/08/2020 09:37:10 ******/
DROP VIEW [dbo].[VW_FATURAMENTO_CUSTO_VEICULO_PBI_REV3]
GO

/****** Object:  View [dbo].[VW_FATURAMENTO_CUSTO_VEICULO_PBI_REV3]    Script Date: 05/08/2020 09:37:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_FATURAMENTO_CUSTO_VEICULO_PBI_REV3] AS 

SELECT CFR.CODIGO,
CFR.SERSUB,
CFR.CODFIL,
DOC.DATREF AS DATA_REFERENCIA,
MOT.NOMMOT,
VEI.NUMVEI,
FRT.DESCRI AS FROTA,
MCV.DESCRI AS Marca,
MDV.DESCRI AS Modelo,
VEI.LOTACA AS CAP_VEIC_KG,
CON.CODCON,
CON.SERCON,
CON.CODFIL AS FILIAL_DOCTO,
CON.CODLIN AS CODIGO_LINHA,
(SELECT PI.DESCRI FROM RODLIN L INNER JOIN RODFIL F ON L.CODFIL = F.CODFIL  LEFT OUTER  JOIN RODMUN PI ON L.PONINI = PI.CODITN WHERE L.CODLIN = CON.CODLIN AND L.CODPAD = 1) AS PONTO_INICIAL,
(SELECT PF.DESCRI FROM RODLIN L INNER JOIN RODFIL F ON L.CODFIL = F.CODFIL  LEFT OUTER  JOIN RODMUN PF ON L.PONFIM = PF.CODITN WHERE L.CODLIN = CON.CODLIN AND L.CODPAD = 1) AS PONTO_FINAL,
(SELECT RODLIN.KMTPLA FROM RODLIN WHERE RODLIN.CODLIN = CON.CODLIN) AS KM_LINHA,
CAST(FORMAT(VW.SOMA_PESOKG,'N','de-de') AS VARCHAR(20)) AS PESO_DOC_KG,
CAST(FORMAT(VW.SOMA_QUANTI,'N','de-de') AS VARCHAR(20)) AS VOLUMES_DOC,
CON.CODPAG,
CLI.RAZSOC,
MAN.CODMAN,
MAN.SERMAN,
MAN.CODFIL AS FILIAL_MANIFESTO,
TIPO_MAN = CASE  
                WHEN MAN.TIPMAN = '1' THEN  
                       'LOTAÇÃO'  
                WHEN TIPMAN = '2' THEN  
                       'TRANSFERÊNCIA'  
                WHEN TIPMAN = '3' THEN  
                       'FRACIONADA'  
                WHEN TIPMAN = '4' THEN  
                       'MISTA'  
                WHEN TIPMAN = '5' THEN  
                       'RODORAPIDO'  
                WHEN TIPMAN = '6' THEN  
                       'DISTRIBUIÇÃO'  
                WHEN TIPMAN = '7' THEN  
                       'COLETA'  
               WHEN TIPMAN = '8' THEN  
                       'REENTREGA'  
                WHEN TIPMAN = '9' THEN  
                       'DEVOLUÇÃO'  
                WHEN TIPMAN = '10' THEN  
                       'COMPLEMENTAR'  
                WHEN TIPMAN = '11' THEN  
                       'VIAGEM'  
                WHEN TIPMAN = '12' THEN  
                       'RETIRADA'  
                WHEN TIPMAN = '13' THEN  
                       'TRANSF.AQUAVIARIA'  
                WHEN TIPMAN = '14' THEN  
                       'AÉREO'  
                WHEN TIPMAN = '15' THEN  
                       'INTERNACIONAL'  
          END,
--FORMAT(CON.TOTFRE,'###,###,###.##','de-de') AS TOTFRE,
--FORMAT(CFR.VLRFRE,'###,###,###.##','de-de') AS VLRFRE,
--CAST(FORMAT(CON.TOTFRE,'N','de-de') AS VARCHAR(20)) AS TOTFRE,
--REPLACE(CON.TOTFRE,'.',',') AS TOTFRE,
CON.TOTFRE,
CAST(FORMAT(CFR.VLRFRE,'N','de-de') AS VARCHAR(20)) AS VLRFRE,
--CFR.VLRFRE,
'' AS EVENTO,
LTRIM(CAST(CFR.CODFIL AS CHAR(02)))+'-'+LTRIM(CFR.SERSUB)+'-'+LTRIM(CAST(CFR.CODIGO AS CHAR(06))) AS CHAVE_CFR
FROM 
RODCFR CFR(NOLOCK) INNER JOIN RODDCO DCO(NOLOCK) ON 
CFR.CODIGO = DCO.CODIGO 
AND CFR.CODFIL = DCO.CODFIL
AND CFR.SERSUB = DCO.SERSUB 
INNER JOIN PAGDOC DOC (NOLOCK) ON 
CFR.CODCLIFOR = DOC.CODCLIFOR AND CFR.SERSUB = DOC.SERIE AND convert(varchar,CFR.CODIGO) = DOC.NUMDOC
INNER JOIN RODCON CON (NOLOCK) ON
DCO.CODDOC = CON.CODCON 
AND DCO.SERDOC = CON.SERCON
AND DCO.FILDOC = CON.CODFIL
INNER JOIN RODMAN MAN (NOLOCK) ON
MAN.CODMAN = DCO.CODMAN AND MAN.SERMAN = DCO.SERMAN AND MAN.CODFIL = DCO.FILMAN
INNER JOIN RODMOT MOT (NOLOCK) ON
CFR.CODMOT = MOT.CODMOT
INNER JOIN RODVEI VEI (NOLOCK) ON
CFR.PLACA = VEI.CODVEI
INNER JOIN RODFRO FRT (NOLOCK) ON
VEI.CODFRO = FRT.CODFRO
INNER JOIN RODCLI CLI (NOLOCK) ON
CON.CODPAG = CLI.CODCLIFOR
INNER JOIN RODMCV MCV (NOLOCK) ON
VEI.CODMCV = MCV.CODMCV
INNER JOIN RODMDV MDV (NOLOCK) ON
VEI.CODMDV = MDV.CODMDV
INNER JOIN VW_CTRC_OST_PESO VW ON
VW.CODCON = CON.CODCON 
AND VW.SERCON = CON.SERCON
AND VW.FILCON = CON.CODFIL
WHERE
DOC.SITUAC = 'L'
AND MOT.EMPREG = 'N'
AND DCO.TIPDOC = 'C.T.R.C.'

union all
SELECT
CFR.CODIGO,
CFR.SERSUB,
CFR.CODFIL,
DOC.DATREF AS DATA_REFERENCIA,
MOT.NOMMOT,
VEI.NUMVEI,
FRT.DESCRI AS FROTA,
MCV.DESCRI AS MARCA,
MDV.DESCRI AS MODELO,
VEI.LOTACA AS CAP_VEIC_KG,
CON.CODIGO,
CON.SERORD,
CON.CODFIL AS FILIAL_DOCTO,
CON.CODLIN AS CODIGO_LINHA,
(SELECT PI.DESCRI FROM RODLIN L INNER JOIN RODFIL F ON L.CODFIL = F.CODFIL  LEFT OUTER  JOIN RODMUN PI ON L.PONINI = PI.CODITN WHERE L.CODLIN = CON.CODLIN AND L.CODPAD = 1) AS PONTO_INICIAL,
(SELECT PF.DESCRI FROM RODLIN L INNER JOIN RODFIL F ON L.CODFIL = F.CODFIL  LEFT OUTER  JOIN RODMUN PF ON L.PONFIM = PF.CODITN WHERE L.CODLIN = CON.CODLIN AND L.CODPAD = 1) AS PONTO_FINAL,
(SELECT RODLIN.KMTPLA FROM RODLIN WHERE RODLIN.CODLIN = CON.CODLIN) AS KM_LINHA,
CAST(FORMAT(VW.SOMA_PESOKG,'N','de-de') AS VARCHAR(20)) AS PESO_DOC_KG,
CAST(FORMAT(VW.SOMA_QUANTI,'N','de-de') AS VARCHAR(20)) AS VOLUMES_DOC,
CON.CODPAG,
CLI.RAZSOC,
MAN.CODMAN,
MAN.SERMAN,
MAN.CODFIL FILIAL_MANIFESTO,
TIPO_MAN = CASE  
                WHEN MAN.TIPMAN = '1' THEN  
                       'LOTAÇÃO'  
                WHEN TIPMAN = '2' THEN  
                       'TRANSFERÊNCIA'  
                WHEN TIPMAN = '3' THEN  
                       'FRACIONADA'  
                WHEN TIPMAN = '4' THEN  
                       'MISTA'  
                WHEN TIPMAN = '5' THEN  
                       'RODORAPIDO'  
                WHEN TIPMAN = '6' THEN  
                       'DISTRIBUIÇÃO'  
                WHEN TIPMAN = '7' THEN  
                       'COLETA'  
               WHEN TIPMAN = '8' THEN  
                       'REENTREGA'  
                WHEN TIPMAN = '9' THEN  
                       'DEVOLUÇÃO'  
                WHEN TIPMAN = '10' THEN  
                       'COMPLEMENTAR'  
                WHEN TIPMAN = '11' THEN  
                       'VIAGEM'  
                WHEN TIPMAN = '12' THEN  
                       'RETIRADA'  
                WHEN TIPMAN = '13' THEN  
                       'TRANSF.AQUAVIARIA'  
                WHEN TIPMAN = '14' THEN  
                       'AÉREO'  
                WHEN TIPMAN = '15' THEN  
                       'INTERNACIONAL'  
          END,
--FORMAT(CON.TOTFRE,'###,###,###.##','de-de') AS TOTFRE,
--FORMAT(CFR.VLRFRE,'###,###,###.##','de-de') AS VLRFRE,
--REPLACE(CON.TOTFRE,'.',',') AS TOTFRE,
--CAST(FORMAT(CON.TOTFRE,'N','de-de') AS VARCHAR(20)) AS TOTFRE,
CON.TOTFRE,
CAST(FORMAT(CFR.VLRFRE,'N','de-de') AS VARCHAR(20)) AS VLRFRE,
--CFR.VLRFRE,
'' AS EVENTO,
LTRIM(CAST(CFR.CODFIL AS CHAR(02)))+'-'+LTRIM(CFR.SERSUB)+'-'+LTRIM(CAST(CFR.CODIGO AS CHAR(06))) AS CHAVE_CFR
FROM 
RODCFR CFR(NOLOCK) INNER JOIN RODDCO DCO(NOLOCK) ON 
CFR.CODIGO = DCO.CODIGO 
AND CFR.CODFIL = DCO.CODFIL
AND CFR.SERSUB = DCO.SERSUB 
INNER JOIN PAGDOC DOC (NOLOCK) ON 
CFR.CODCLIFOR = DOC.CODCLIFOR AND CFR.SERSUB = DOC.SERIE AND convert(varchar,CFR.CODIGO) = DOC.NUMDOC
INNER JOIN RODORD CON (NOLOCK) ON
DCO.CODDOC = CON.CODIGO 
AND DCO.SERDOC = CON.SERORD
AND DCO.FILDOC = CON.CODFIL
INNER JOIN RODMAN MAN (NOLOCK) ON
MAN.CODMAN = DCO.CODMAN AND MAN.SERMAN = DCO.SERMAN AND MAN.CODFIL = DCO.FILMAN
INNER JOIN RODMOT MOT (NOLOCK) ON
CFR.CODMOT = MOT.CODMOT
INNER JOIN RODVEI VEI (NOLOCK) ON
CFR.PLACA = VEI.CODVEI
INNER JOIN RODFRO FRT (NOLOCK) ON
VEI.CODFRO = FRT.CODFRO
INNER JOIN RODCLI CLI (NOLOCK) ON
CON.CODPAG = CLI.CODCLIFOR
INNER JOIN RODMCV MCV (NOLOCK) ON
VEI.CODMCV = MCV.CODMCV
INNER JOIN RODMDV MDV (NOLOCK) ON
VEI.CODMDV = MDV.CODMDV
INNER JOIN VW_CTRC_OST_PESO VW ON
VW.CODORD = CON.CODIGO 
AND VW.SERORD = CON.SERORD
AND VW.FILORD = CON.CODFIL
WHERE
DOC.SITUAC = 'L'
AND MOT.EMPREG = 'N'
AND DCO.TIPDOC = 'O.S.T.'

union all

SELECT 
CFR.CODIGO,
CFR.SERSUB,
CFR.CODFIL,
DOC.DATREF AS DATA_REFERENCIA,
MOT.NOMMOT,
VEI.NUMVEI,
FRT.DESCRI AS FROTA,
MCV.DESCRI AS MARCA,
MDV.DESCRI AS MODELO,
VEI.LOTACA AS CAP_VEIC_KG,
CON.CODOCS,
CON.SEROCS,
CON.FILOCS AS FILIAL_DOCTO,
NULL AS CODIGO_LINHA,
NULL AS PONTO_INICIAL,
NULL AS PONTO_FINAL,
NULL AS KM_LINHA,
CAST(FORMAT(VW.SOMA_PESOKG,'N','de-de') AS VARCHAR(20)) AS PESO_DOC_KG,
CAST(FORMAT(VW.SOMA_QUANTI,'N','de-de') AS VARCHAR(20)) AS VOLUMES_DOC,
CON.CODPAG,
CLI.RAZSOC,
MAN.CODMAN,
MAN.SERMAN,
MAN.CODFIL AS FILIAL_MANIFESTO,
TIPO_MAN = CASE  
                WHEN MAN.TIPMAN = '1' THEN  
                       'LOTAÇÃO'  
                WHEN TIPMAN = '2' THEN  
                       'TRANSFERÊNCIA'  
                WHEN TIPMAN = '3' THEN  
                       'FRACIONADA'  
                WHEN TIPMAN = '4' THEN  
                       'MISTA'  
                WHEN TIPMAN = '5' THEN  
                       'RODORAPIDO'  
                WHEN TIPMAN = '6' THEN  
                       'DISTRIBUIÇÃO'  
                WHEN TIPMAN = '7' THEN  
                       'COLETA'  
               WHEN TIPMAN = '8' THEN  
                       'REENTREGA'  
                WHEN TIPMAN = '9' THEN  
                       'DEVOLUÇÃO'  
                WHEN TIPMAN = '10' THEN  
                       'COMPLEMENTAR'  
                WHEN TIPMAN = '11' THEN  
                       'VIAGEM'  
                WHEN TIPMAN = '12' THEN  
                       'RETIRADA'  
                WHEN TIPMAN = '13' THEN  
                       'TRANSF.AQUAVIARIA'  
                WHEN TIPMAN = '14' THEN  
                       'AÉREO'  
                WHEN TIPMAN = '15' THEN  
                       'INTERNACIONAL'  
          END,
0 AS TOTFRE,
--FORMAT(CFR.VLRFRE,'###,###,###.##','de-de') AS VLRFRE,
CAST(FORMAT(CFR.VLRFRE,'N','de-de') AS VARCHAR(20)) AS VLRFRE,
--CFR.VLRFRE,
'' AS EVENTO,
LTRIM(CAST(CFR.CODFIL AS CHAR(02)))+'-'+LTRIM(CFR.SERSUB)+'-'+LTRIM(CAST(CFR.CODIGO AS CHAR(06))) AS CHAVE_CFR
FROM 
RODCFR CFR(NOLOCK) INNER JOIN RODDCO DCO(NOLOCK) ON 
CFR.CODIGO = DCO.CODIGO 
AND CFR.CODFIL = DCO.CODFIL
AND CFR.SERSUB = DCO.SERSUB 
INNER JOIN PAGDOC DOC (NOLOCK) ON 
CFR.CODCLIFOR = DOC.CODCLIFOR AND CFR.SERSUB = DOC.SERIE AND convert(varchar,CFR.CODIGO) = DOC.NUMDOC
INNER JOIN RODOCS CON (NOLOCK) ON
DCO.CODDOC = CON.CODOCS 
AND DCO.SERDOC = CON.SEROCS
AND DCO.FILDOC = CON.FILOCS
INNER JOIN RODMAN MAN (NOLOCK) ON
MAN.CODMAN = DCO.CODMAN AND MAN.SERMAN = DCO.SERMAN AND MAN.CODFIL = DCO.FILMAN
INNER JOIN RODMOT MOT (NOLOCK) ON
CFR.CODMOT = MOT.CODMOT
INNER JOIN RODVEI VEI (NOLOCK) ON
CFR.PLACA = VEI.CODVEI
INNER JOIN RODFRO FRT (NOLOCK) ON
VEI.CODFRO = FRT.CODFRO
INNER JOIN RODCLI CLI (NOLOCK) ON
CON.CODPAG = CLI.CODCLIFOR
INNER JOIN RODMCV MCV (NOLOCK) ON
VEI.CODMCV = MCV.CODMCV
INNER JOIN RODMDV MDV (NOLOCK) ON
VEI.CODMDV = MDV.CODMDV
INNER JOIN VW_CTRC_OST_PESO VW ON
VW.CODOCS = CON.CODOCS 
AND VW.SEROCS = CON.SEROCS
AND VW.FILOCS = CON.FILOCS
WHERE
DOC.SITUAC = 'L'
AND MOT.EMPREG = 'N'
AND DCO.TIPDOC = 'O.C.S.'

union all

SELECT 
CFR.CODIGO,
CFR.SERSUB,
CFR.CODFIL,
DOC.DATREF AS DATA_REFERENCIA,
MOT.NOMMOT,
VEI.NUMVEI,
FRT.DESCRI AS FROTA,
MCV.DESCRI AS MARCA,
MDV.DESCRI AS MODELO,
VEI.LOTACA AS CAP_VEIC_KG,
CCT.CODCON,
CCT.SERCON,
CCT.FILDOC AS FILIAL_DOCTO,
NULL AS CODIGO_LINHA,
NULL AS PONTO_INICIAL,
NULL AS PONTO_FINAL,
NULL AS KM_LINHA,
CASE 
WHEN CCT.TIPDOC = 'C' THEN (SELECT FORMAT(VW.SOMA_PESOKG,'###,###,###.##','de-de') FROM VW_CTRC_OST_PESO VW where 
					VW.CODCON = CCT.CODCON 
					AND VW.SERCON = CCT.SERCON
					AND VW.FILCON = CCT.CODFIL)			 
WHEN CCT.TIPDOC = 'O' THEN (SELECT FORMAT(VW.SOMA_PESOKG,'###,###,###.##','de-de') FROM VW_CTRC_OST_PESO VW where 
					VW.CODORD = CCT.CODCON 
					AND VW.SERORD = CCT.SERCON
					AND VW.FILORD = CCT.CODFIL)	 
WHEN CCT.TIPDOC = 'S' THEN (SELECT FORMAT(VW.SOMA_PESOKG,'###,###,###.##','de-de') FROM VW_CTRC_OST_PESO VW where 
					VW.CODOCS = CCT.CODCON 
					AND VW.SEROCS = CCT.SERCON
					AND VW.FILOCS = CCT.CODFIL)	 
END  PESO_DOC_KG,
CASE
WHEN CCT.TIPDOC = 'C' THEN (SELECT FORMAT(VW.SOMA_QUANTI,'###,###,###.##','de-de') FROM VW_CTRC_OST_PESO VW where 
					VW.CODCON = CCT.CODCON 
					AND VW.SERCON = CCT.SERCON
					AND VW.FILCON = CCT.CODFIL)			 
WHEN CCT.TIPDOC = 'O' THEN (SELECT FORMAT(VW.SOMA_QUANTI,'###,###,###.##','de-de') FROM VW_CTRC_OST_PESO VW where 
					VW.CODORD = CCT.CODCON 
					AND VW.SERORD = CCT.SERCON
					AND VW.FILORD = CCT.CODFIL)	 
WHEN CCT.TIPDOC = 'S' THEN (SELECT FORMAT(VW.SOMA_QUANTI,'###,###,###.##','de-de') FROM VW_CTRC_OST_PESO VW where 
					VW.CODOCS = CCT.CODCON 
					AND VW.SEROCS = CCT.SERCON
					AND VW.FILOCS = CCT.CODFIL)	 
END VOLUMES_DOC,
CASE 
WHEN CCT.TIPDOC = 'C' THEN (SELECT CLI.CODCLIFOR FROM RODCLI CLI (NOLOCK) WHERE CLI.CODCLIFOR = (SELECT CON.CODPAG FROM RODCON CON (NOLOCK) WHERE CON.CODCON = CCT.CODCON AND CON.SERCON = CCT.SERCON AND CON.CODFIL = CCT.CODFIL))
WHEN CCT.TIPDOC = 'O' THEN (SELECT CLI.CODCLIFOR FROM RODCLI CLI (NOLOCK) WHERE CLI.CODCLIFOR = (SELECT CON.CODPAG FROM RODORD CON (NOLOCK) WHERE CON.CODIGO = CCT.CODCON AND CON.SERORD = CCT.SERCON AND CON.CODFIL = CCT.CODFIL)) 
WHEN CCT.TIPDOC = 'A' THEN (SELECT CLI.CODCLIFOR FROM RODCLI CLI (NOLOCK) WHERE CLI.CODCLIFOR = (SELECT CON.CODPAG FROM RODCOL CON (NOLOCK) WHERE CON.CODIGO = CCT.CODCON AND CON.SERCOL = CCT.SERCON AND CON.CODFIL = CCT.CODFIL)) 
WHEN CCT.TIPDOC = 'S' THEN (SELECT CLI.CODCLIFOR FROM RODCLI CLI (NOLOCK) WHERE CLI.CODCLIFOR = (SELECT CON.CODPAG FROM RODOCS CON (NOLOCK) WHERE CON.CODOCS = CCT.CODCON AND CON.SEROCS = CCT.SERCON AND CON.FILOCS = CCT.CODFIL)) 
END CODCLIFOR,
CASE 
WHEN CCT.TIPDOC = 'C' THEN (SELECT CLI.RAZSOC FROM RODCLI CLI (NOLOCK) WHERE CLI.CODCLIFOR = (SELECT CON.CODPAG FROM RODCON CON (NOLOCK) WHERE CON.CODCON = CCT.CODCON AND CON.SERCON = CCT.SERCON AND CON.CODFIL = CCT.CODFIL))
WHEN CCT.TIPDOC = 'O' THEN (SELECT CLI.RAZSOC FROM RODCLI CLI (NOLOCK) WHERE CLI.CODCLIFOR = (SELECT CON.CODPAG FROM RODORD CON (NOLOCK) WHERE CON.CODIGO = CCT.CODCON AND CON.SERORD = CCT.SERCON AND CON.CODFIL = CCT.CODFIL)) 
WHEN CCT.TIPDOC = 'A' THEN (SELECT CLI.RAZSOC FROM RODCLI CLI (NOLOCK) WHERE CLI.CODCLIFOR = (SELECT CON.CODPAG FROM RODCOL CON (NOLOCK) WHERE CON.CODIGO = CCT.CODCON AND CON.SERCOL = CCT.SERCON AND CON.CODFIL = CCT.CODFIL)) 
WHEN CCT.TIPDOC = 'S' THEN (SELECT CLI.RAZSOC FROM RODCLI CLI (NOLOCK) WHERE CLI.CODCLIFOR = (SELECT CON.CODPAG FROM RODOCS CON (NOLOCK) WHERE CON.CODOCS = CCT.CODCON AND CON.SEROCS = CCT.SERCON AND CON.FILOCS = CCT.CODFIL)) 
END RAZSOC,
CASE 
WHEN CCT.TIPDOC = 'C' THEN (SELECT CON.CODMAN FROM RODCON CON (NOLOCK) WHERE CON.CODCON = CCT.CODCON AND CON.SERCON = CCT.SERCON AND CON.CODFIL = CCT.CODFIL)
WHEN CCT.TIPDOC = 'O' THEN (SELECT CON.CODMAN FROM RODORD CON (NOLOCK) WHERE CON.CODIGO = CCT.CODCON AND CON.SERORD = CCT.SERCON AND CON.CODFIL = CCT.CODFIL) 
WHEN CCT.TIPDOC = 'A' THEN (SELECT CON.CODMAN FROM RODCOL CON (NOLOCK) WHERE CON.CODIGO = CCT.CODCON AND CON.SERCOL = CCT.SERCON AND CON.CODFIL = CCT.CODFIL)
WHEN CCT.TIPDOC = 'S' THEN (SELECT CON.CODMAN FROM RODOCS CON (NOLOCK) WHERE CON.CODOCS = CCT.CODCON AND CON.SEROCS = CCT.SERCON AND CON.FILOCS = CCT.CODFIL) 
END CODMAN,
CASE 
WHEN CCT.TIPDOC = 'C' THEN (SELECT CON.SERMAN FROM RODCON CON (NOLOCK) WHERE CON.CODCON = CCT.CODCON AND CON.SERCON = CCT.SERCON AND CON.CODFIL = CCT.CODFIL)
WHEN CCT.TIPDOC = 'O' THEN (SELECT CON.SERMAN FROM RODORD CON (NOLOCK) WHERE CON.CODIGO = CCT.CODCON AND CON.SERORD = CCT.SERCON AND CON.CODFIL = CCT.CODFIL) 
WHEN CCT.TIPDOC = 'A' THEN (SELECT CON.SERMAN FROM RODCOL CON (NOLOCK) WHERE CON.CODIGO = CCT.CODCON AND CON.SERCOL = CCT.SERCON AND CON.CODFIL = CCT.CODFIL)
WHEN CCT.TIPDOC = 'S' THEN (SELECT CON.SERMAN FROM RODOCS CON (NOLOCK) WHERE CON.CODOCS = CCT.CODCON AND CON.SEROCS = CCT.SERCON AND CON.FILOCS = CCT.CODFIL) 
END SERMAN,
CASE 
WHEN CCT.TIPDOC = 'C' THEN (SELECT CON.FILMAN FROM RODCON CON (NOLOCK) WHERE CON.CODCON = CCT.CODCON AND CON.SERCON = CCT.SERCON AND CON.CODFIL = CCT.CODFIL)
WHEN CCT.TIPDOC = 'O' THEN (SELECT CON.FILMAN FROM RODORD CON (NOLOCK) WHERE CON.CODIGO = CCT.CODCON AND CON.SERORD = CCT.SERCON AND CON.CODFIL = CCT.CODFIL) 
WHEN CCT.TIPDOC = 'A' THEN (SELECT CON.FILMAN FROM RODCOL CON (NOLOCK) WHERE CON.CODIGO = CCT.CODCON AND CON.SERCOL = CCT.SERCON AND CON.CODFIL = CCT.CODFIL)
WHEN CCT.TIPDOC = 'S' THEN (SELECT CON.FILMAN FROM RODOCS CON (NOLOCK) WHERE CON.CODOCS = CCT.CODCON AND CON.SEROCS = CCT.SERCON AND CON.FILOCS = CCT.CODFIL) 
END FILIAL_MANIFESTO,
'' AS TIPO_MAN,
--CASE 
--WHEN CCT.TIPDOC = 'C' THEN (SELECT CAST(FORMAT(CON.TOTFRE,'N','de-de') AS VARCHAR(20)) FROM RODCON CON (NOLOCK) WHERE CON.CODCON = CCT.CODCON AND CON.SERCON = CCT.SERCON AND CON.CODFIL = CCT.CODFIL)
--WHEN CCT.TIPDOC = 'O' THEN (SELECT CAST(FORMAT(CON.TOTFRE,'N','de-de') AS VARCHAR(20)) FROM RODORD CON (NOLOCK) WHERE CON.CODIGO = CCT.CODCON AND CON.SERORD = CCT.SERCON AND CON.CODFIL = CCT.CODFIL) 
--WHEN CCT.TIPDOC = 'A' THEN (SELECT CAST(FORMAT(CON.TOTFRE,'N','de-de') AS VARCHAR(20)) FROM RODCOL CON (NOLOCK) WHERE CON.CODIGO = CCT.CODCON AND CON.SERCOL = CCT.SERCON AND CON.CODFIL = CCT.CODFIL)
--WHEN CCT.TIPDOC = 'S' THEN (SELECT 0 FROM RODOCS CON (NOLOCK) WHERE CON.CODOCS = CCT.CODCON AND CON.SEROCS = CCT.SERCON AND CON.FILOCS = CCT.CODFIL) 
--END AS TOTFRE,
CASE 
WHEN CCT.TIPDOC = 'C' THEN (SELECT CON.TOTFRE FROM RODCON CON (NOLOCK) WHERE CON.CODCON = CCT.CODCON AND CON.SERCON = CCT.SERCON AND CON.CODFIL = CCT.CODFIL)
WHEN CCT.TIPDOC = 'O' THEN (SELECT CON.TOTFRE FROM RODORD CON (NOLOCK) WHERE CON.CODIGO = CCT.CODCON AND CON.SERORD = CCT.SERCON AND CON.CODFIL = CCT.CODFIL) 
WHEN CCT.TIPDOC = 'A' THEN (SELECT CON.TOTFRE FROM RODCOL CON (NOLOCK) WHERE CON.CODIGO = CCT.CODCON AND CON.SERCOL = CCT.SERCON AND CON.CODFIL = CCT.CODFIL)
WHEN CCT.TIPDOC = 'S' THEN (SELECT 0 FROM RODOCS CON (NOLOCK) WHERE CON.CODOCS = CCT.CODCON AND CON.SEROCS = CCT.SERCON AND CON.FILOCS = CCT.CODFIL) 
END AS TOTFRE,
--FORMAT(CCT.VLRCUS,'###,###,###.##','de-de') AS VLRFRE,
CAST(FORMAT(CCT.VLRCUS,'N','de-de') AS VARCHAR(20)) AS VLRFRE,
--CCT.VLRCUS AS VLRFRE,
CAL.COMPLE AS EVENTO,
LTRIM(CAST(CFR.CODFIL AS CHAR(02)))+'-'+LTRIM(CFR.SERSUB)+'-'+LTRIM(CAST(CFR.CODIGO AS CHAR(06))) AS CHAVE_CFR
FROM 
RODCFR CFR (NOLOCK)
INNER JOIN TERFEC FEC (NOLOCK) ON FEC.CODFEC = CFR.CODEXT 
INNER JOIN TERIFC IFC (NOLOCK) ON IFC.CODFEC = FEC.CODFEC -- item dos eventos manuais
INNER JOIN RODACE ACE (NOLOCK) ON ACE.CODCFR = CFR.CODIGO
INNER JOIN RODCCT CCT (NOLOCK) ON ACE.ID_ACE = CCT.ID_ACE
INNER JOIN PAGDOC DOC (NOLOCK) ON CFR.CODCLIFOR = DOC.CODCLIFOR AND CFR.SERSUB = DOC.SERIE AND convert(varchar,CFR.CODIGO) = DOC.NUMDOC
INNER JOIN TERCAL CAL (NOLOCK) ON IFC.ID_CAL = CAL.ID_CAL AND CAL.NUMDOC = ACE.NUMDOC
INNER JOIN RODMOT MOT (NOLOCK) ON CFR.CODMOT = MOT.CODMOT
INNER JOIN RODVEI VEI (NOLOCK) ON CFR.PLACA = VEI.CODVEI
INNER JOIN RODFRO FRT (NOLOCK) ON VEI.CODFRO = FRT.CODFRO
INNER JOIN RODMCV MCV (NOLOCK) ON VEI.CODMCV = MCV.CODMCV
INNER JOIN RODMDV MDV (NOLOCK) ON VEI.CODMDV = MDV.CODMDV

WHERE
CAL.TIPDOC in('ABA','EVD','EVC')
AND DOC.SITUAC = 'L'
AND MOT.EMPREG = 'N'
GO


