-- AUTOR: KELSEN LIMA
select * from RODVEI 
select M.CODMOT,
       M.NOMMOT,
       M.NOMEAB,
       M.DTNASC,
       M.NATURA,
       M.ESTADO,
       M.ENDERE,
       M.NUMERG,
       M.NUMCPF,
       M.SITUAC,
       M.CODCMO
  from RODMOT M
 WHERE SITUAC = 'A' AND CODCMO <> 1
 

[?07/?08/?2017 14:14]  Carlos Nogueira:  
select V.CODFRO AS 'CODIGO DA FROTA',
V.NUMVEI AS 'PLACA',
V.TIPVEI AS 'COD.TIPO VEICULO',
V.LOTACA AS 'CAPACIDADE KG',
M1.DESCRI AS 'MARCA',
M.DESCRI AS 'MODELO',
F.DESCRI AS 'TIPO',
V.PROPRI AS 'PROPRIO (S/N)',
V.QTDLIT AS 'QTD LITROS TANQUE',
V.CODCMB AS 'TIPO COMBUSTIVEL',
G.DESCRI AS 'COMBUSTIVEL'
P.
from RODVEI V 
INNER JOIN RODMDV M ON V.CODMDV = M.CODMDV
INNER JOIN RODMCV M1 ON V.CODMCV = M1.CODMCV
INNER JOIN RODFRO F ON V.CODFRO = F.CODFRO
INNER JOIN RODGAS G ON G.CODCMB = V.CODCMB
INNER JOIN RODMOT P ON P.CODMOT = V.CODMOT 
WHERE V.SITUAC =1 
AND V.PROPRI = 'N'
AND V.CODCMB = 1