-- AUTOR: KELSEN LIMA
SELECT DI.APRUSU AS APROVADOR,
       DI.APRDAT AS DAT_APROVACAO,
       DI.NUMPAR AS PARCELA,
       DI.DATVEN AS VENCIMENTO,
       DI.VLRPAR AS VALOR_PARCELA,       
       CASE DI.SITUAC 
          WHEN 'L' THEN 'LIQUIDADO' 
          WHEN 'D' THEN 'DEVEDOR' 
          ELSE '' 
       END AS SITUACAO,
       --ISNULL((ISNULL(DI.VLRLIQ,0) + (ISNULL(DI.JURDOC,0)+ISNULL(DI.CORDOC,0)) -ISNULL(DI.VLRPAG,0)),0) AS VLRDEV,
       (SELECT CL.RAZSOC FROM RODCLI CL WHERE DC.CODCLIFOR = CL.CODCLIFOR) AS FORNECEDOR,
       DC.*  
  FROM PAGDOCI DI,
       PAGDOC  DC       
 --Where  NUMDOC = '248753462' AND CODCLIFOR = 1 AND SERIE = '1'
 WHERE DI.CODCLIFOR = DC.CODCLIFOR
   AND DI.SERIE = DC.SERIE
   AND DI.NUMDOC = DC.NUMDOC
   AND DI.APRDAT >= '09/10/2016' 
   AND DI.APRDAT <= '10/07/2016'
ORDER BY DI.APRDAT