-- SP CONSULTA CTRC
-- AUTOR: KELSEN LIMA

USE [db_visual_rodopar]
GO

DROP PROCEDURE [dbo].[SP_CONSULTA_CTRC_OST]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_CONSULTA_CTRC_OST_GAT] (@DATA_INI SMALLDATETIME, @DATA_FIM SMALLDATETIME, @PAGADOR INT, @REMETENTE INT, @DESTINATARIO INT,  
@TIPDOC VARCHAR(5), @PAG_CNPJ VARCHAR(20), @CODVEI VARCHAR(10), @FATURADOS VARCHAR(1), @FILIAL SMALLINT, @MODAL SMALLINT, @FILIAL_FATURA SMALLINT, @FATURA INT, @REDESPACHO INT) AS  
--# CTRC # -    
SELECT  
    'CTRC' AS TIPDOC,    
    CON.TIPCON AS TIPCON,
    convert(char(1),iif(CON.SITDUP is null,'E',CON.SITDUP)) as SITDUP,  
    CON.DATCAD AS DATA,   
    CON.NATOPE AS CODFIS,  
    CON.DIFERE AS DIFERENCIAL,   
 --FIL.NOMEAB AS FILIAL,      
    FIL.CODCGC AS CNPJ_TRANSPORTADOR,  
 CON.CODFIL AS COD_FILIAL,  
    CON.SERCON AS SERIE,  
    CON.CODCON AS DOCUMENTO,  
      (SELECT TOP 1 CSC.CODOCS  
             FROM   
                    RODCSC CSC WITH(NOLOCK) 
             WHERE  
                    CON.CODFIL = CSC.FILCON  
                    AND CON.SERCON = CSC.SERCON  
                    AND CON.CODCON = CSC.CODCON) AS COD_OCS,  
    CON.CODLIN AS LINHA,  
    VEI_CAV.CODVEI AS CODVEI,   
    PROP.CODCGC AS CNPJ_PROPRIETARIO,  
 PROP.CODCPF AS CPF_PROPRIETATIO,  
 PROP.RAZSOC AS NOME_PROPRIETATIO,  
 PROP.FISJUR,  
    VEI_CAV.NUMVEI  AS PLACA_CM,   
    VEI_CR_1.NUMVEI AS PLACA_CR_1,  
    MOT.NOMMOT AS MOTORISTA,  
 MOT.NUMCPF AS CPF_MOTORISTA,   
 (SELECT TOP 1 MOTM.NOMMOT  
     FROM RODMAN AS MAN WITH(NOLOCK) 
        LEFT OUTER JOIN RODMOT AS MOTM WITH(NOLOCK)ON   
        MAN.CODMO1 = MOTM.CODMOT  
        WHERE (MAN.CODFIL= CON.FILMAN)   
        AND (MAN.SERMAN = CON.SERMAN)   
        AND (MAN.CODMAN = CON.CODMAN)) AS MOT_MANIFESTO,   
    CPAG.CODCLIFOR AS COD_PAGADOR,   
    CPAG.CODCGC AS PAG_CNPJ,  
 CPAG.RAZSOC AS PAGADOR,   
    CPAG.NOMEAB AS NOME_ABREVIADO,  
 VEND.NOMEVE AS NOME_VENDEDOR,  
 CREM.CODVEN AS COD_VENDEDOR_REM,  
 CCONS.CODVEN AS COD_VENDEDOR_CONS,  
 CONSV.NOMEVE AS VENDEDOR_CONS,  
 CDES.CODVEN AS COD_VENDEDOR_DES,  
 DESV.NOMEVE AS VENDEDOR_DES,   
    CREM.CODCLIFOR AS COD_REMETENTE,  
    CREM.CODCGC AS REM_CNPJ,  
    CAST(CREM.INSCRI AS VARCHAR) AS REM_INSCRI,  
    CREM.RAZSOC AS REMETENTE,  
    MREM.DESCRI AS MUN_REMETENTE,  
    MREM.ESTADO AS EST_REMETENTE,  
    CDES.CODCLIFOR AS COD_DESTINATARIO,  
    CDES.CODCGC AS DES_CNPJ,   
 CDES.CODCEP AS CEP_DESTINO,  
 CAST(ISNULL(CDES.TIPLOG,'') AS VARCHAR) AS LOGRAD_DESTINO,  
 CDES.NUMERO,  
 CDES.ENDERE AS END_DESTINO,  
 CDES.BAIRRO AS BAIRRO_DESTINO,  
    CDES.RAZSOC AS DESTINATARIO,  
    MUNDES.DESCRI AS MUN_DESTINATARIO,  
    MUNDES.ESTADO AS EST_DESTINATARIO,  
    CRED.RAZSOC AS REDESPACHO,  
 CAST(ISNULL(CRED.TIPLOG,'') AS VARCHAR) AS LOGRAD_REDESPACHO,   
 CRED.NUMERO AS NUM_REDESPACHO,  
 CRED.ENDERE AS END_REDESPACHO,      
    TCOL.RAZSOC AS TCOLETA,  
    MTCOL.DESCRI AS MUN_TCOLETA,  
    MTCOL.ESTADO AS EST_TCOLETA,  
    TENT.RAZSOC AS TENTREGA,  
    MTENT.DESCRI AS MUN_TENTREGA,  
    MTENT.ESTADO AS EST_TENTREGA,  
    NULL AS RECEBEDOR,   
    (SELECT TOP 1 DUP.DATEMI  
        FROM dbo.RODDUP DUP WITH(NOLOCK)  
             INNER JOIN RODIDU IDU WITH(NOLOCK)ON DUP.CODFIL = IDU.CODFIL AND  
                                      DUP.NUMDUP = IDU.NUMDUP  
        WHERE IDU.FILDOC = CON.CODFIL   
          AND IDU.SERDOC = CON.SERCON  
          AND IDU.CODDOC = CON.CODCON  
          AND DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'CTRC')    AS DT_EMISSAO_DUP,          
    (SELECT TOP 1 IDU.CODFIL  
        FROM dbo.RODDUP DUP WITH(NOLOCK)   
             INNER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL AND  
                                      DUP.NUMDUP = IDU.NUMDUP  
        WHERE IDU.FILDOC = CON.CODFIL   
          AND IDU.SERDOC = CON.SERCON  
          AND IDU.CODDOC = CON.CODCON  
          AND DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'CTRC')    AS COD_FILIAL_DUP,      
    (SELECT TOP 1 IDU.NUMDUP  
        FROM dbo.RODDUP DUP WITH(NOLOCK)  
             INNER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL AND  
                                      DUP.NUMDUP = IDU.NUMDUP  
        WHERE IDU.FILDOC = CON.CODFIL   
          AND IDU.SERDOC = CON.SERCON  
          AND IDU.CODDOC = CON.CODCON  
          AND DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'CTRC')    AS COD_FATURA,   
    (SELECT TOP 1 DUP.DATVEN  
        FROM dbo.RODDUP DUP WITH(NOLOCK)  
             INNER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL AND  
                                      DUP.NUMDUP = IDU.NUMDUP  
        WHERE IDU.FILDOC = CON.CODFIL   
          AND IDU.SERDOC = CON.SERCON  
          AND IDU.CODDOC = CON.CODCON  
          AND DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'CTRC') AS DT_VENC_DUP,    
       (SELECT TOP 1 REC.DATLAN  
        FROM dbo.RODDUP DUP WITH(NOLOCK)  
             INNER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL AND  
                                      DUP.NUMDUP = IDU.NUMDUP  
             INNER JOIN RECMEN REC WITH(NOLOCK) ON IDU.CODFIL = REC.CODFIL AND  
                                      IDU.NUMDUP_CHAR= REC.NUMDUP  
        WHERE IDU.FILDOC = CON.CODFIL   
          AND IDU.SERDOC = CON.SERCON  
          AND IDU.CODDOC = CON.CODCON  
          AND DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'CTRC'   
          AND REC.DEBCRE = 'C'  
         ORDER BY REC.DATLAN DESC)    AS DT_REC_FATURA,    
    (SELECT TOP 1 NFC.ORDCOM  
     FROM dbo.RODNFC AS NFC WITH(NOLOCK) 
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)) AS REF_CLIENTE,  
    (SELECT TOP 1 NFC.ITECOM  
     FROM dbo.RODNFC AS NFC WITH(NOLOCK) 
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)) AS NOSSA_REF,  
   (SELECT ISNULL(SUM(ISNULL(QUANTI, 0)), 0) AS Expr1  
        FROM dbo.RODNFC AS NFC WITH(NOLOCK) 
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)) AS QTD_VOL,  
    (SELECT ISNULL(SUM(ISNULL(PESOKG, 0)), 0) AS Expr1  
        FROM dbo.RODNFC AS NFC WITH(NOLOCK) 
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)) AS PESO,  
    (SELECT ISNULL(SUM(ISNULL(LARGUR, 0)), 0) AS Expr1  
        FROM dbo.RODNFC AS NFC WITH(NOLOCK) 
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)) AS LARG_CUB,      
    (SELECT ISNULL(SUM(ISNULL(ALTURA, 0)), 0) AS Expr1  
        FROM dbo.RODNFC AS NFC WITH(NOLOCK) 
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)) AS ALTURA_CUB,      
    (SELECT ISNULL(SUM(ISNULL(PROFUN, 0)), 0) AS Expr1  
        FROM dbo.RODNFC AS NFC WITH(NOLOCK) 
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)) AS PROFUN_CUB,          
    (SELECT ISNULL(SUM(ISNULL(PESCUB, 0)), 0) AS Expr1  
        FROM dbo.RODNFC AS NFC WITH(NOLOCK) 
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)) AS PESO_CUB,    
    (SELECT ISNULL(SUM(ISNULL(PESCAL, 0)), 0) AS Expr1  
        FROM dbo.RODNFC AS NFC WITH(NOLOCK) 
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)) AS PESO_CALC,              
    (SELECT ISNULL(SUM(ISNULL(VLRMER, 0)), 0) AS Expr1  
        FROM dbo.RODNFC AS NFC WITH(NOLOCK)  
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)) AS VLR_MERC,  
 (SELECT TOP 1 NFC.ESPECI  
     FROM dbo.RODNFC AS NFC WITH(NOLOCK) 
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)) AS ESPECIE,  
    (SELECT TOP 1 PRO.DESCRI  
        FROM dbo.RODNFC AS NFC WITH(NOLOCK)  
        INNER JOIN dbo.RODPRO AS PRO WITH(NOLOCK) ON   
        NFC.CODPROTR = PRO.CODPROTR  
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)) AS PRODUTO,      
 (SELECT TOP 1 NFC.DATENT  
        FROM dbo.RODNFC AS NFC WITH(NOLOCK)  
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)) AS DATA_ENTREGA,   
    CON.FREPES AS FRETE_PESO,   
    CON.FREVAL AS FRETE_VALOR,  
    CON.DESVAL AS VLR_DESPACHO,  
    CON.VLRPED AS VLR_PEDAGIO,   
 CON.ALIISS,  
    CON.ALICOT,  
 CON.VLRPIS AS PIS_COFINS,  
    CON.ICMVLR AS VLR_ICMS,   
 CON.VLRISS AS VLR_ISS,  
 CON.BASCAL AS BASE_CALCULO,  
    CON.TOTFRE AS VLR_TOTAL_FRETE,   
    CON.VLRAJU AS VLR_AJUDANTE,  
    CON.VLRCOL AS PLAT_REF_CAR_CC,  
    CON.VLRENT AS DGR_DEV_CC,  
    CON.VLRCAR AS VLR_CARGA,  
    CON.DESCAR AS VLR_DESCARGA,  
    CON.TAXDIF AS VLR_TXDIF,  
    CON.VLRSUF AS VLR_SUFRAMA,  
    CON.SECVAL AS VLR_SECCAT,  
    CON.VLRGRI AS VLR_GRIS,  
    CON.VLRESC AS VLR_ESCOLTA,  
    CON.VLCOMP AS TX_ADICIONAL,    
    CON.OBSCON AS OBSERVACAO,  
    CON.TABPAD,  
 CON.ID_RODIIF AS ITEM_TARIFA,  
 FRA.CODCMO,  
 CMO.DESCRI,  
    CON.USUATU,  
    CON.DDTCHE AS DESC_HR_CHEGADA,  
    CON.DDTENT AS DESC_RH_ENTRADA,  
    CON.DDTSAI AS DESSC_HR_SAIDA,  
    CON.CDTCHE AS CARG_HR_CHEGADA,  
    CON.CDTENT AS CARG_HR_ENTRADA,  
    CON.CDTSAI AS CARG_HR_SAIDA,  
 REG_O.DESCRI AS REGIAO_ORIGEM,  
 REG_D.DESCRI AS REGIAO_DESTINO,  
  (SELECT TOP 1 MAN.CODMAN  
        FROM RODMAN MAN WITH(NOLOCK)  
          WHERE MAN.CODFIL = CON.FILMAN   
          AND MAN.SERMAN = CON.SERMAN  
          AND MAN.CODMAN = CON.CODMAN  
    AND MAN.TIPMAN <> '2') AS MANIFESTO,   
  (SELECT TOP 1 MAN.CODFIL  
        FROM RODMAN MAN WITH(NOLOCK)   
          WHERE MAN.CODFIL = CON.FILMAN   
          AND MAN.SERMAN = CON.SERMAN  
          AND MAN.CODMAN = CON.CODMAN  
    AND MAN.TIPMAN <> '2') AS FILIAL_MANIFESTO,  
  (SELECT TOP 1 MAN.SERMAN  
        FROM RODMAN MAN WITH(NOLOCK)  
          WHERE MAN.CODFIL = CON.FILMAN   
          AND MAN.SERMAN = CON.SERMAN  
          AND MAN.CODMAN = CON.CODMAN  
    AND MAN.TIPMAN <> '2') AS SERIE_MANIFESTO,  
  (SELECT TOP 1 MAN.FILDES  
        FROM RODMAN MAN WITH(NOLOCK)  
          WHERE MAN.CODFIL = CON.FILMAN   
          AND MAN.SERMAN = CON.SERMAN  
          AND MAN.CODMAN = CON.CODMAN  
    AND MAN.TIPMAN <> '2') AS FILIAL_DESTINO,  
 TIP0_MAN = CASE  
                WHEN MAN.TIPMAN = '1' THEN  
                       'LOTAÇÃO'  
                WHEN TIPMAN = '2' THEN  
                       'TRANSFERÊNCIA'  
                WHEN TIPMAN = '3' THEN  
                       'FRACIONADA'  
                WHEN TIPMAN = '4' THEN  
                       'MISTA'  
                WHEN TIPMAN = '5' THEN  
                       'RODORAPIDO'  
                WHEN TIPMAN = '6' THEN  
                       'DISTRIBUIÇÃO'  
                WHEN TIPMAN = '7' THEN  
                       'COLETA'  
               WHEN TIPMAN = '8' THEN  
                       'REENTREGA'  
                WHEN TIPMAN = '9' THEN  
                       'DEVOLUÇÃO'  
                WHEN TIPMAN = '10' THEN  
                       'COMPLEMENTAR'  
                WHEN TIPMAN = '11' THEN  
                       'VIAGEM'  
                WHEN TIPMAN = '12' THEN  
                       'RETIRADA'  
                WHEN TIPMAN = '13' THEN  
                       'TRANSF.AQUAVIARIA'  
                WHEN TIPMAN = '14' THEN  
                       'AÉREO'  
                WHEN TIPMAN = '15' THEN  
                       'INTERNACIONAL'  
          END,  
  (SELECT TOP 1 MANT.CODMAN  
        FROM RODMAN MANT WITH(NOLOCK), RODIMA IMA_T WITH(NOLOCK) 
          WHERE MANT.CODFIL = IMA_T.FILMAN   
     AND MANT.SERMAN = IMA_T.SERMAN  
          AND MANT.CODMAN = IMA_T.CODMAN  
    AND IMA_T.FILDOC = CON.CODFIL   
          AND IMA_T.SERDOC = CON.SERCON  
          AND IMA_T.CODDOC = CON.CODCON  
    AND MANT.TIPMAN = '2') AS MANIFESTO_TRANSF,   
  (SELECT TOP 1 MANT.CODFIL  
        FROM RODMAN MANT WITH(NOLOCK), RODIMA IMA_T WITH(NOLOCK)  
          WHERE MANT.CODFIL = IMA_T.FILMAN   
          AND MANT.SERMAN = IMA_T.SERMAN  
          AND MANT.CODMAN = IMA_T.CODMAN  
    AND IMA_T.FILDOC = CON.CODFIL   
          AND IMA_T.SERDOC = CON.SERCON  
          AND IMA_T.CODDOC = CON.CODCON  
    AND MANT.TIPMAN = '2') AS FILIAL_MANIFESTO_TRANSF,  
  (SELECT TOP 1 MANT.SERMAN  
        FROM RODMAN MANT WITH(NOLOCK), RODIMA IMA_T WITH(NOLOCK) 
          WHERE MANT.CODFIL = IMA_T.FILMAN   
          AND MANT.SERMAN = IMA_T.SERMAN  
          AND MANT.CODMAN = IMA_T.CODMAN  
    AND IMA_T.FILDOC = CON.CODFIL   
     AND IMA_T.SERDOC = CON.SERCON  
          AND IMA_T.CODDOC = CON.CODCON  
    AND MANT.TIPMAN = '2') AS SERIE_MANIFESTO_TRANSF,  
     (SELECT TOP 1 MANT.FILDES  
        FROM RODMAN MANT WITH(NOLOCK) 
    WHERE MAN.CODFIL = CON.FILMAN   
          AND MANT.SERMAN = CON.SERMAN  
          AND MANT.CODMAN = CON.CODMAN  
    AND MANT.TIPMAN = '2') AS FILIAL_DESTINO_TRANSF,  
 CON.CTEAUT,  
 CON.CTE_ID AS CHAVE_CTE,  
 CON.CTEPRO AS PROTOC_CTE,  
 ISNULL (CON.BLOFAT,'N') AS FAT_BLOQUEADO,  
 0 AS ICM_INCENTIVADO,  
 'N' AS A_VISTA,  
 CON.FILCOT AS FILIAL_COTACAO,  
 CON.ESTFEC AS COTACAO,  
 CON.DATLME AS PRAZO_ENTREGA,  
   (SELECT TOP 1 IFR.METDIA  
 FROM RODIFR IFR WITH(NOLOCK) 
 WHERE CON.TABPAD=IFR.CODFRE  
 AND CON.ID_RODIIF=IIF.ID_RODIIF  
 AND IIF.ID_RODIFR=IFR.ID_RODIFR) AS METDIA,  
 CON.PREFAT,  
 (SELECT top 1 datediff(day,OCH.DATOCO,CON.DATLME)  
             FROM  
                    RODOCO AS OCO WITH(NOLOCK) 
                    LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) 
                           ON OCO.CODIGO = OCH.CODOCO  
                    LEFT OUTER JOIN RODNFC AS NFC WITH(NOLOCK) 
                           ON NFC.ID_NFC = OCH.ID_NFC  
             WHERE  
                    (NFC.CODFIL = CON.CODFIL)                 
                    AND (NFC.SERCON = CON.SERCON)  
                    AND (NFC.CODCON = CON.CODCON)  
                    AND OCO.CODIGO = 1) AS DIAS_ATRASOS,         
 (SELECT top 1 OCO.CODIGO  
        FROM RODOCO AS OCO WITH(NOLOCK)   
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODNFC AS NFC WITH(NOLOCK) ON  
  NFC.ID_NFC = OCH.ID_NFC  
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)) AS  COD_OCORRENCIA,  
 (SELECT top 1 OCO.DESCRI  
        FROM RODOCO AS OCO WITH(NOLOCK)   
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODNFC AS NFC WITH(NOLOCK) ON  
  NFC.ID_NFC = OCH.ID_NFC  
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)) AS  OCORRENCIA,  
 (SELECT top 1 OCO.CODIGO  
        FROM RODOCO AS OCO WITH(NOLOCK)  
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODNFC AS NFC WITH(NOLOCK) ON  
  NFC.ID_NFC = OCH.ID_NFC  
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)  
  AND OCO.CODIGO IN (1,19,25,119)) AS  COD_OCO_FINALIZ,  
 (SELECT top 1 OCO.DESCRI  
        FROM RODOCO AS OCO WITH(NOLOCK)  
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODNFC AS NFC WITH(NOLOCK) ON  
  NFC.ID_NFC = OCH.ID_NFC  
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)  
  AND OCO.CODIGO IN (1,19,25,119)) AS  OCORRENCIA_FINALIZ,  
 (SELECT  top 1 ISNULL(OSE.NOMFUN, 'SEM CONFERENTE')  
    FROM OSEFUN OSE WITH(NOLOCK) 
    LEFT OUTER JOIN RODRMC RMC WITH(NOLOCK) ON  
    OSE.CODFUN = RMC.CODFUN  
    LEFT OUTER JOIN RODIRC IRC WITH(NOLOCK) ON  
    RMC.CODFIL = IRC.FILRMC   
    AND RMC.CODRMC = IRC.CODRMC  
    WHERE IRC.FILDOC = CON.CODFIL   
          AND IRC.SERDOC = CON.SERCON  
          AND IRC.CODDOC = CON.CODCON  
    AND IRC.TIPDOC = 'C') AS CONF_ROM_CARREGTO,  
  (SELECT top 1 ISNULL(OSE.NOMFUN, 'SEM CONFERENTE')  
    FROM OSEFUN OSE WITH(NOLOCK) 
    LEFT OUTER JOIN RODRMD RMD WITH(NOLOCK) ON  
    OSE.CODFUN = RMD.CODFUN  
    LEFT OUTER JOIN RODIRD IRD WITH(NOLOCK) ON  
    RMD.CODFIL = IRD.CODFIL   
    AND RMD.CODRMD = IRD.CODRMD  
    WHERE IRD.FILDOC = CON.CODFIL   
          AND IRD.SERDOC = CON.SERCON  
          AND IRD.CODDOC = CON.CODCON  
    AND IRD.TIPDOC = 'C') AS CONF_ROM_DESCARGA,  
    (SELECT TOP 1 INTD.DATENV  
        FROM INTDOC INTD WITH(NOLOCK)  
          WHERE INTD.FILDOC = CON.CODFIL   
          AND INTD.SERDOC = CON.SERCON  
          AND INTD.CODDOC = CON.CODCON  
    AND INTD.TIPDOC = 'CTE') AS DT_AVERBACAO,  
 (SELECT TOP 1 INTD.PROTOC  
        FROM INTDOC INTD WITH(NOLOCK)  
          WHERE INTD.FILDOC = CON.CODFIL   
          AND INTD.SERDOC = CON.SERCON  
          AND INTD.CODDOC = CON.CODCON  
    AND INTD.TIPDOC = 'CTE') AS PROT_AVERBACAO,  
 (SELECT TOP 1 OCO.CODIGO  
        FROM RODOCO AS OCO WITH(NOLOCK)  
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODNFC AS NFC WITH(NOLOCK) ON  
  NFC.ID_NFC = OCH.ID_NFC  
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)  
  ORDER BY OCH.ID_OCH DESC) AS  COD_ULT_OCORRENCIA,  
 (SELECT TOP 1 OCO.DESCRI  
        FROM RODOCO AS OCO WITH(NOLOCK)  
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODNFC AS NFC WITH(NOLOCK) ON  
  NFC.ID_NFC = OCH.ID_NFC  
        WHERE (NFC.CODFIL = CON.CODFIL)   
        AND (NFC.SERCON = CON.SERCON)   
        AND (NFC.CODCON = CON.CODCON)  
  ORDER BY OCH.ID_OCH DESC) AS  ULT_OCORRENCIA,  
  S.DESCRI AS SETOR_ENTREGA,  
  G.CODGRO AS COD_GERENC_RISCO,  
  SITUACAO = CASE   
                WHEN G.SITUAC = 'C' THEN  
                       'CANCELADO'  
                WHEN G.SITUAC = 'D' THEN  
                       'CADASTRADO'  
       WHEN G.SITUAC = 'F' THEN  
                       'FINALIZADO'  
                END,  
  CPR.ID_CPR AS COMPROVANTE_ENTREGA,  
  (SELECT  DBO.F_SITUACAO_OCS(CON.CODCON,CON.SERCON,CON.CODFIL,CREM.CODCLIFOR,NFC.SERIEN,NFC.NOTFIS,NULL)) AS SITUACAO_OS,  
  REDC.RAZSOC AS REDESPACHO_PARCEIRO
--  ,
--  coalesce((SELECT DISTINCT CAST(H1.CODOCO AS VARCHAR(003)) +'-' + O.DESCRI +'/' AS [text()]
--		from RODOCH H1,RODOCO O WHERE H1.ID_NFC = NFC.ID_NFC	
--		AND O.CODIGO = H1.CODOCO						
--		FOR XML PATH(''),TYPE).value('.[1]','Varchar(max)'),'') as Ocorrencias_da_NF  
FROM  
    dbo.RODCON AS CON WITH(NOLOCK)  
    INNER JOIN dbo.RODFIL AS FIL WITH(NOLOCK) ON   
    CON.CODFIL = FIL.CODFIL   
    INNER JOIN dbo.RODLIN AS LIN WITH(NOLOCK) ON      
    CON.CODLIN = LIN.CODLIN  
    INNER JOIN dbo.RODCLI AS CPAG WITH(NOLOCK) ON   
    CON.CODPAG = CPAG.CODCLIFOR   
    INNER JOIN dbo.RODMUN AS MCPAG WITH(NOLOCK) ON   
    CPAG.CODMUN = MCPAG.CODMUN  
    LEFT OUTER JOIN dbo.RODCGR AS CGR WITH(NOLOCK) ON  
    CPAG.CODCGR = CGR.CODCGR  
    LEFT OUTER JOIN dbo.RODMUN AS MUNORI WITH(NOLOCK) ON   
    CON.MUNCOL = MUNORI.CODMUN   
    INNER JOIN dbo.RODCLI AS CREM WITH(NOLOCK) ON  
    CON.CODREM = CREM.CODCLIFOR  
    INNER JOIN RODMUN AS MREM WITH(NOLOCK) ON      
    CREM.CODMUN = MREM.CODMUN  
    INNER JOIN dbo.RODCLI AS CDES WITH(NOLOCK) ON   
    CON.CODDES = CDES.CODCLIFOR   
    INNER JOIN dbo.RODMUN AS MUNDES WITH(NOLOCK) ON   
    CDES.CODMUN = MUNDES.CODMUN   
    LEFT OUTER JOIN dbo.RODMOT AS MOT WITH(NOLOCK) ON   
    CON.CODMOT = MOT.CODMOT   
    LEFT OUTER JOIN dbo.RODVEI AS VEI_CAV WITH(NOLOCK) ON   
    CON.PLACA = VEI_CAV.CODVEI  
    LEFT OUTER JOIN dbo.RODFRO AS VEI_FRO WITH(NOLOCK) ON   
    VEI_CAV.CODFRO = VEI_FRO.CODFRO  
    LEFT OUTER JOIN dbo.RODVEI AS VEI_CR_1 WITH(NOLOCK) ON  
    CON.PLACA2 = VEI_CR_1.CODVEI  
    LEFT OUTER JOIN dbo.RODVEI AS VEI_CR_2 WITH(NOLOCK) ON      
    CON.PLACA3 = VEI_CR_2.CODVEI  
    LEFT OUTER JOIN dbo.RODFRA FRA WITH(NOLOCK) ON   
    CON.TABPAD = FRA.CODFRE  
	LEFT OUTER JOIN dbo.RODCMO CMO WITH(NOLOCK) ON  
	FRA.CODCMO = CMO.CODCMO  
	LEFT OUTER JOIN dbo.RODIIF IIF WITH(NOLOCK) ON  
	CON.ID_RODIIF = IIF.ID_RODIIF  
    LEFT OUTER JOIN dbo.RODCLI AS TCOL WITH(NOLOCK) ON   
    CON.TERCOL = TCOL.CODCLIFOR   
    LEFT OUTER JOIN dbo.RODMUN AS MTCOL WITH(NOLOCK) ON   
    TCOL.CODMUN = MTCOL.CODMUN       
    LEFT OUTER JOIN dbo.RODCLI AS TENT WITH(NOLOCK) ON   
    CON.TERENT = TENT.CODCLIFOR  
    LEFT OUTER JOIN dbo.RODMUN AS MTENT WITH(NOLOCK) ON   
    TENT.CODMUN = MTENT.CODMUN       
    LEFT OUTER JOIN RECVEN AS VEND WITH(NOLOCK) ON  
    CPAG.CODVEN = VEND.CODVEN  
 LEFT OUTER JOIN CRMREG AS REG_O WITH(NOLOCK) ON  
 CON.REGREM = REG_O.CODREG  
 LEFT OUTER JOIN CRMREG AS REG_D WITH(NOLOCK) ON  
 CON.CODREG = REG_D.CODREG  
 LEFT OUTER JOIN RODMAN MAN WITH(NOLOCK) ON  
 CON.FILMAN=MAN.CODFIL  
    AND CON.SERMAN=MAN.SERMAN  
 AND CON.CODMAN=MAN.CODMAN  
 LEFT OUTER JOIN dbo.RODCLI AS CRED WITH(NOLOCK) ON   
    CON.CODRED = CRED.CODCLIFOR   
 LEFT OUTER JOIN RECVEN DESV WITH(NOLOCK) ON  
 CREM.CODVEN = DESV.CODVEN  
 LEFT OUTER JOIN RECVEN CONSV WITH(NOLOCK) ON  
 CREM.CODVEN = CONSV.CODVEN  
 LEFT OUTER JOIN RODCLI CCONS WITH(NOLOCK) ON  
 CON.CODICO = CCONS.CODCLIFOR  
 LEFT OUTER JOIN RODCLI PROP WITH(NOLOCK) ON  
 VEI_CAV.CODPRO = PROP.CODCLIFOR  
 LEFT OUTER JOIN RODSET S WITH(NOLOCK) ON  
 CDES.CODSETCL = S.CODSETCL  
 LEFT OUTER JOIN RODGRO G WITH(NOLOCK) ON  
 CON.CODCON=G.CODDOC  
 AND CON.CODFIL=G.FILDOC  
 AND CON.SERCON=G.SERDOC  
 LEFT OUTER JOIN RODDOP DOP WITH(NOLOCK) ON  
 CON.CODCON = DOP.CODDOC  
 AND CON.SERCON = DOP.SERDOC  
 AND CON.CODFIL = DOP.FILDOC  
 AND DOP.TIPDOC = 'CTR'  
 LEFT OUTER JOIN RODCPR CPR WITH(NOLOCK) ON  
 DOP.ID_CPR = CPR.ID_CPR  
 LEFT OUTER JOIN RODNFC NFC WITH(NOLOCK) ON  
 CON.CODCON = NFC.CODCON  
 AND CON.SERCON = NFC.SERCON  
 AND CON.CODFIL = NFC.CODFIL  
 LEFT OUTER JOIN RODRED RED WITH(NOLOCK) ON  
 CON.CODFIL=RED.FILDOC  
 AND CON.SERCON=RED.SERDOC  
 AND CON.CODCON=RED.CODDOC  
 AND RED.TIPDOC='CTR'  
 LEFT OUTER JOIN RODCLI REDC WITH(NOLOCK) ON  
 ISNULL (RED.REDMU2,RED.REDMUN)=REDC.CODCLIFOR  
WHERE       
   (CPAG.CODCLIFOR = @PAGADOR OR @PAGADOR = 0)  
   AND CON.DATCAD >= @DATA_INI AND CON.DATCAD < DATEADD(DAY,1,@DATA_FIM)
   AND (CON.SITUAC NOT IN ('C', 'I'))
   AND (CREM.CODCLIFOR = @REMETENTE OR @REMETENTE = 0)  
   AND (CDES.CODCLIFOR = @DESTINATARIO OR @DESTINATARIO = 0)  
   AND ('CTRC' = @TIPDOC OR @TIPDOC = '')  
   AND (CPAG.CODCGC LIKE @PAG_CNPJ OR @PAG_CNPJ = '')  
   AND (VEI_CAV.CODVEI = @CODVEI OR @CODVEI = '')  
   AND (iif(CON.SITDUP is null,'E',CON.SITDUP) = @FATURADOS OR @FATURADOS = '')  
   AND (CON.CODFIL = @FILIAL OR @FILIAL = 0)  
   AND (FRA.CODCMO = @MODAL OR @MODAL = 0)  
   AND (CON.FILDUP = @FILIAL_FATURA OR @FILIAL_FATURA = 0)  
   AND (CON.NUMDUP = @FATURA OR @FATURA = 0)  
   AND (ISNULL (RED.REDMU2,RED.REDMUN) = @REDESPACHO OR @REDESPACHO = 0)
   --AND CON.CTEAUT = 'S'  
UNION ALL  
--# OST # -  
SELECT  
    'OST' AS TIPDOC,  
    CON.TIPORD AS TIPCON,      
	IIF(CON.SITDUP IS NULL,'E',CON.SITDUP) AS SITDUP,    
    CON.DATCAD AS DATA,  
    0 AS CODFIS,   
    CON.DIFERE AS DIFERENCIAL,  
 --FIL.NOMEAB AS FILIAL,   
    FIL.CODCGC AS CNPJ_TRANSPORTADOR,  
 CON.CODFIL AS COD_FILIAL,  
    CON.SERORD AS SERIE,   
    CON.CODIGO AS DOCUMENTO,   
        (SELECT TOP 1 CSC.CODOCS  
             FROM  
                    RODSOR CSC WITH(NOLOCK)  
             WHERE  
                    CON.CODFIL = CSC.FILORD  
                    AND CON.SERCON = CSC.SERORD  
                    AND CON.CODCON = CSC.CODORD)  AS COD_OCS,  
    CON.CODLIN AS LINHA,  
    VEI_CAV.CODVEI AS CODVEI,  
 PROP.CODCGC AS CNPJ_PROPRIETARIO,  
 PROP.CODCPF AS CPF_PROPRIETATIO,  
 PROP.RAZSOC AS NOME_PROPRIETATIO,  
 PROP.FISJUR,  
    VEI_CAV.NUMVEI  AS PLACA_CM,   
    VEI_CR_1.NUMVEI AS PLACA_CR_1,  
    MOT.NOMMOT AS MOTORISTA,   
 MOT.NUMCPF AS CPF_MOTORISTA,  
 (SELECT TOP 1 MOTM.NOMMOT  
     FROM RODMAN AS MAN WITH(NOLOCK)  
        LEFT OUTER JOIN RODMOT AS MOTM WITH(NOLOCK) ON   
        MAN.CODMO1 = MOTM.CODMOT  
        WHERE (MAN.CODFIL= CON.FILMAN)   
        AND (MAN.SERMAN = CON.SERMAN)   
        AND (MAN.CODMAN = CON.CODMAN)) AS MOT_MANIFESTO,   
    CPAG.CODCLIFOR AS COD_PAGADOR,   
    CPAG.CODCGC AS PAG_CNPJ,  
    CPAG.RAZSOC AS PAGADOR,   
    CPAG.NOMEAB AS NOME_ABREVIADO,  
 VEND.NOMEVE AS NOME_VENDEDOR,  
 CREM.CODVEN AS COD_VENDEDOR_REM,  
 CCONS.CODVEN AS COD_VENDEDOR_CONS,  
 CONSV.NOMEVE AS VENDEDOR_CONS,  
 CDES.CODVEN AS COD_VENDEDOR_DES,  
 DESV.NOMEVE AS VENDEDOR_DES,   
    CREM.CODCLIFOR AS COD_REMETENTE,  
    CREM.CODCGC AS REM_CNPJ,  
    CAST(CREM.INSCRI AS VARCHAR) AS REM_INSCRI,  
    CREM.RAZSOC AS REMETENTE,  
    MREM.DESCRI AS MUN_REMETENTE,  
    MREM.ESTADO AS EST_REMETENTE,  
    CDES.CODCLIFOR AS COD_DESTINATARIO,  
    CDES.CODCGC AS DES_CNPJ,  
 CDES.CODCEP AS CEP_DESTINO,  
 CAST(ISNULL(CDES.TIPLOG,'') AS VARCHAR) AS LOGRAD_DESTINO,  
 CDES.NUMERO,  
 CDES.ENDERE AS END_DESTINO,  
 CDES.BAIRRO AS BAIRRO_DESTINO,  
    CDES.RAZSOC AS DESTINATARIO,  
    MUNDES.DESCRI AS MUN_DESTINATARIO,  
    MUNDES.ESTADO AS EST_DESTINATARIO,  
 CRED.RAZSOC AS REDESPACHO,  
 CAST(ISNULL(CDES.TIPLOG,'') AS VARCHAR)AS LOGRAD_REDESPACHO,  
 CRED.NUMERO AS NUM_REDESPACHO,  
 CRED.ENDERE AS END_REDESPACHO,   
    TCOL.RAZSOC AS TCOLETA,  
    MTCOL.DESCRI AS MUN_TCOLETA,  
    MTCOL.ESTADO AS EST_TCOLETA,  
    TENT.RAZSOC AS TENTREGA,  
    MTENT.DESCRI AS MUN_TENTREGA,  
    MTENT.ESTADO AS EST_TENTREGA,  
 NULL AS RECEBEDOR,     
    (SELECT TOP 1 DUP.DATEMI  
        FROM dbo.RODDUP DUP WITH(NOLOCK)   
/*  Alterado em 07/10/2016 para evitar restringir documentos que não possuem nr de fatura associada */
--         INNER JOIN RODIDU IDU ON DUP.CODFIL = IDU.CODFIL AND 
		   LEFT OUTER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL AND
                                      DUP.NUMDUP = IDU.NUMDUP  
        WHERE IDU.FILDOC = CON.CODFIL   
          AND IDU.SERDOC = CON.SERORD            
         AND IDU.CODDOC = CON.CODIGO  
          AND DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'OST')    AS DT_EMISSAO_DUP,      
    (SELECT TOP 1 IDU.CODFIL  
        FROM dbo.RODDUP DUP WITH(NOLOCK)   
/*  Alterado em 07/10/2016 para evitar restringir documentos que não possuem nr de fatura associada */
--           INNER JOIN RODIDU IDU ON DUP.CODFIL = IDU.CODFIL AND  
             LEFT OUTER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL AND  
                                      DUP.NUMDUP = IDU.NUMDUP  
        WHERE IDU.FILDOC = CON.CODFIL   
          AND IDU.SERDOC = CON.SERORD            
          AND IDU.CODDOC = CON.CODIGO  
          AND DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'OST')    AS COD_FILIAL_DUP,      
     (SELECT TOP 1 IDU.NUMDUP  
        FROM dbo.RODDUP DUP WITH(NOLOCK)   
/*  Alterado em 07/10/2016 para evitar restringir documentos que não possuem nr de fatura associada */
--           INNER JOIN RODIDU IDU ON DUP.CODFIL = IDU.CODFIL AND  
           LEFT OUTER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL AND  
                                      DUP.NUMDUP = IDU.NUMDUP  
        WHERE IDU.FILDOC = CON.CODFIL   
          AND IDU.SERDOC = CON.SERORD  
          AND IDU.CODDOC = CON.CODIGO  
          AND DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'OST')    AS COD_FATURA,    
      (SELECT TOP 1 DUP.DATVEN  
        FROM dbo.RODDUP DUP WITH(NOLOCK)   
/*  Alterado em 07/10/2016 para evitar restringir documentos que não possuem nr de fatura associada */
--             INNER JOIN RODIDU IDU ON DUP.CODFIL = IDU.CODFIL AND  
             LEFT OUTER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL AND DUP.NUMDUP = IDU.NUMDUP  
        WHERE IDU.FILDOC = CON.CODFIL   
          AND IDU.SERDOC = CON.SERORD  
          AND IDU.CODDOC = CON.CODIGO  
          AND DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'OST')    AS DT_VENC_DUP,            
      (SELECT TOP 1 REC.DATLAN  
        FROM dbo.RODDUP DUP WITH(NOLOCK)   
/*  Alterado em 07/10/2016 para evitar restringir documentos que não possuem nr de fatura associada */
--             INNER JOIN RODIDU IDU ON DUP.CODFIL = IDU.CODFIL AND  
             LEFT OUTER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL AND  
                                      DUP.NUMDUP = IDU.NUMDUP  
--             INNER JOIN RECMEN REC ON DUP.CODFIL = REC.CODFIL AND  
             LEFT OUTER JOIN RECMEN REC WITH(NOLOCK) ON DUP.CODFIL = REC.CODFIL AND CAST(DUP.NUMDUP AS VARCHAR(15)) = REC.NUMDUP                                                     
        WHERE IDU.FILDOC = CON.CODFIL   
          AND IDU.SERDOC = CON.SERCON  
          AND IDU.CODDOC = CON.CODCON  
          AND DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'OST'   
          AND REC.DEBCRE = 'C'  
         ORDER BY REC.DATLAN DESC)    AS DT_REC_FATURA,   
    (SELECT TOP 1 NFC.ORDCOM  
        FROM dbo.RODIOS AS NFC WITH(NOLOCK)  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS REF_CLIENTE,  
    (SELECT TOP 1 NFC.ITECOM  
        FROM dbo.RODIOS AS NFC WITH(NOLOCK)  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS NOSSA_REF,  
    (SELECT ISNULL(SUM(ISNULL(QUANTI, 0)), 0) AS Expr1  
          FROM dbo.RODIOS AS NFC WITH(NOLOCK)  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS QTD_VOL,  
    (SELECT ISNULL(SUM(ISNULL(PESOKG, 0)), 0) AS Expr1  
        FROM dbo.RODIOS AS NFC WITH(NOLOCK)  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS PESO,      
    (SELECT ISNULL(SUM(ISNULL(LARGUR, 0)), 0) AS Expr1  
        FROM dbo.RODIOS AS NFC  WITH(NOLOCK) 
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS LARG_CUB,  
    (SELECT ISNULL(SUM(ISNULL(ALTURA, 0)), 0) AS Expr1  
        FROM dbo.RODIOS AS NFC WITH(NOLOCK)  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS ALTURA_CUB,  
    (SELECT ISNULL(SUM(ISNULL(PROFUN, 0)), 0) AS Expr1  
        FROM dbo.RODIOS AS NFC WITH(NOLOCK)  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS PROFUN_CUB,      
    (SELECT ISNULL(SUM(ISNULL(PESCUB, 0)), 0) AS Expr1      
        FROM dbo.RODIOS AS NFC WITH(NOLOCK)  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS PESO_CUB,          
    (SELECT ISNULL(SUM(ISNULL(PESCAL, 0)), 0) AS Expr1      
        FROM dbo.RODIOS AS NFC WITH(NOLOCK)  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS PESO_CALC,          
    (SELECT ISNULL(SUM(ISNULL(VLRMER, 0)), 0) AS Expr1  
     FROM dbo.RODIOS AS NFC WITH(NOLOCK)  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS VLR_MERC,  
   (SELECT TOP 1 NFC.ESPECI  
        FROM dbo.RODIOS AS NFC WITH(NOLOCK)  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS ESPECIE,  
   (SELECT TOP 1 PRO.DESCRI  
        FROM dbo.RODIOS AS NFC WITH(NOLOCK)   
        INNER JOIN dbo.RODPRO AS PRO WITH(NOLOCK) ON   
        NFC.CODPROTR = PRO.CODPROTR  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS PRODUTO,   
    (SELECT TOP 1 NFC.DATENT  
        FROM dbo.RODIOS AS NFC WITH(NOLOCK)   
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS DATA_ENTREGA,  
    CON.FREPES AS FRETE_PESO,   
    CON.FREVAL AS FRETE_VALOR,  
    CON.DESVAL AS VLR_DESPACHO,  
    CON.VLRPED AS VLR_PEDAGIO,   
 CON.ALIISS,  
    CON.ALICOT,  
 CON.VLRPIS AS PIS_COFINS,  
    CON.ICMVLR AS VLR_ICMS,  
 CON.VLRISS AS VLR_ISS,   
    CON.BASCAL AS BASE_CALCULO,  
    CON.TOTFRE AS VLR_TOTAL_FRETE,   
    CON.VLRAJU AS VLR_AJUDANTE,  
    CON.VLRCOL AS PLAT_REF_CAR_CC,  
    CON.VLRENT AS DGR_DEV_CC,  
    CON.VLRCAR AS VLR_CARGA,  
    CON.DESCAR AS VLR_DESCARGA,  
    CON.TAXDIF AS VLR_TXDIF,  
    CON.VLRSUF AS VLR_SUFRAMA,  
    CON.SECVAL AS VLR_SECCAT,  
    CON.VLRGRI AS VLR_GRIS,  
    CON.VLRESC AS VLR_ESCOLTA,  
    CON.VLCOMP AS TX_ADICIONAL,   
    CON.OBSCON AS OBSERVACAO,  
    CON.TABPAD,  
 CON.ID_RODIIF AS ITEM_TARIFA,  
 FRA.CODCMO,  
 CMO.DESCRI,  
    CON.USUATU,  
    CON.DDTCHE AS DESC_HR_CHEGADA,  
    CON.DDTENT AS DESC_RH_ENTRADA,  
    CON.DDTSAI AS DESSC_HR_SAIDA,  
    CON.CDTCHE AS CARG_HR_CHEGADA,  
    CON.CDTENT AS CARG_HR_ENTRADA,  
    CON.CDTSAI AS CARG_HR_SAIDA,  
 REG_O.DESCRI AS REGIAO_ORIGEM,  
 REG_D.DESCRI AS REGIAO_DESTINO,  
  (SELECT TOP 1 MAN.CODMAN  
        FROM RODMAN MAN WITH(NOLOCK)   
          WHERE MAN.CODFIL = CON.FILMAN   
          AND MAN.SERMAN = CON.SERMAN  
          AND MAN.CODMAN = CON.CODMAN  
    AND MAN.TIPMAN <> '2') AS MANIFESTO,   
  (SELECT TOP 1 MAN.CODFIL  
        FROM RODMAN MAN WITH(NOLOCK)   
          WHERE MAN.CODFIL = CON.FILMAN   
          AND MAN.SERMAN = CON.SERMAN  
          AND MAN.CODMAN = CON.CODMAN  
    AND MAN.TIPMAN <> '2') AS FILIAL_MANIFESTO,  
  (SELECT TOP 1 MAN.SERMAN  
        FROM RODMAN MAN WITH(NOLOCK)   
          WHERE MAN.CODFIL = CON.FILMAN   
          AND MAN.SERMAN = CON.SERMAN  
          AND MAN.CODMAN = CON.CODMAN  
    AND MAN.TIPMAN <> '2') AS SERIE_MANIFESTO,  
  (SELECT TOP 1 MAN.FILDES  
        FROM RODMAN MAN WITH(NOLOCK)    
          WHERE MAN.CODFIL = CON.FILMAN   
          AND MAN.SERMAN = CON.SERMAN  
          AND MAN.CODMAN = CON.CODMAN  
    AND MAN.TIPMAN <> '2') AS FILIAL_DESTINO,  
  TIP0_MAN = CASE  
                WHEN MAN.TIPMAN = '1' THEN  
                       'LOTAÇÃO'  
                WHEN TIPMAN = '2' THEN  
    'TRANSFERÊNCIA'  
                WHEN TIPMAN = '3' THEN  
                      'FRACIONADA'  
                WHEN TIPMAN = '4' THEN  
                       'MISTA'  
                WHEN TIPMAN = '5' THEN  
                       'RODORAPIDO'  
                WHEN TIPMAN = '6' THEN  
                       'DISTRIBUIÇÃO'  
                WHEN TIPMAN = '7' THEN  
                       'COLETA'  
                WHEN TIPMAN = '8' THEN  
                       'REENTREGA'  
                WHEN TIPMAN = '9' THEN  
                       'DEVOLUÇÃO'  
                WHEN TIPMAN = '10' THEN  
                       'COMPLEMENTAR'  
                WHEN TIPMAN = '11' THEN  
                       'VIAGEM'  
                WHEN TIPMAN = '12' THEN  
                       'RETIRADA'  
                WHEN TIPMAN = '13' THEN  
                       'TRANSF.AQUAVIARIA'  
                WHEN TIPMAN = '14' THEN  
                       'AÉREO'  
                WHEN TIPMAN = '15' THEN  
                       'INTERNACIONAL'  
          END,  
  (SELECT TOP 1 MANT.CODMAN  
        FROM RODMAN MANT WITH(NOLOCK) , RODIMA IMA_T WITH(NOLOCK)  
          WHERE MANT.CODFIL = IMA_T.FILMAN   
          AND MANT.SERMAN = IMA_T.SERMAN  
          AND MANT.CODMAN = IMA_T.CODMAN  
    AND IMA_T.FILDOC = CON.CODFIL   
          AND IMA_T.SERDOC = CON.SERORD  
          AND IMA_T.CODDOC = CON.CODIGO  
    AND MANT.TIPMAN = '2') AS MANIFESTO_TRANSF,   
  (SELECT TOP 1 MANT.CODFIL  
        FROM RODMAN MANT WITH(NOLOCK) , RODIMA IMA_T WITH(NOLOCK)  
          WHERE MANT.CODFIL = IMA_T.FILMAN   
          AND MANT.SERMAN = IMA_T.SERMAN  
          AND MANT.CODMAN = IMA_T.CODMAN  
    AND IMA_T.FILDOC = CON.CODFIL   
          AND IMA_T.SERDOC = CON.SERORD  
          AND IMA_T.CODDOC = CON.CODIGO  
    AND MANT.TIPMAN = '2') AS FILIAL_MANIFESTO_TRANSF,  
  (SELECT TOP 1 MANT.SERMAN  
        FROM RODMAN MANT WITH(NOLOCK) , RODIMA IMA_T WITH(NOLOCK)  
          WHERE MANT.CODFIL = IMA_T.FILMAN   
          AND MANT.SERMAN = IMA_T.SERMAN  
          AND MANT.CODMAN = IMA_T.CODMAN  
    AND IMA_T.FILDOC = CON.CODFIL   
          AND IMA_T.SERDOC = CON.SERORD  
          AND IMA_T.CODDOC = CON.CODIGO  
    AND MANT.TIPMAN = '2') AS SERIE_MANIFESTO_TRANSF,  
  (SELECT TOP 1 MANT.FILDES  
        FROM RODMAN MANT WITH(NOLOCK)  
    WHERE MAN.CODFIL = CON.FILMAN   
          AND MANT.SERMAN = CON.SERMAN  
          AND MANT.CODMAN = CON.CODMAN  
    AND MANT.TIPMAN = '2') AS FILIAL_DESTINO_TRANSF,  
 'S' AS CTEAUT,  
 NULL AS CHAVE_CTE,  
 NULL AS PROTOC_CTE,  
 'N' AS FAT_BLOQUEADO,  
 0 AS ICM_INCENTIVADO,  
 'N' AS A_VISTA,  
 CON.FILCOT AS FILIAL_COTACAO,  
 CON.ESTFEC AS COTACAO,  
 CON.DATLME AS PRAZO_ENTREGA,  
(SELECT TOP 1 IFR.METDIA  
 FROM RODIFR IFR WITH(NOLOCK)  
 WHERE CON.TABPAD=IFR.CODFRE  
 AND CON.ID_RODIIF=IIF.ID_RODIIF  
 AND IIF.ID_RODIFR=IFR.ID_RODIFR) AS METDIA,  
 CON.PREFAT,  
 (SELECT TOP 1 datediff(day,OCH.DATOCO,CON.DATLME)  
             FROM  
                    RODOCO AS OCO WITH(NOLOCK)  
                    LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK)  
                           ON OCO.CODIGO = OCH.CODOCO  
                    LEFT OUTER JOIN RODIOS AS NFC WITH(NOLOCK)  
                           ON NFC.ID_IOS = OCH.ID_IOS  
             WHERE  
                    (NFC.FILORD = CON.CODFIL)    
                    AND (NFC.SERORD = CON.SERORD)  
                    AND (NFC.CODORD = CON.CODIGO)  
                    AND OCO.CODIGO = 1) AS DIAS_ATRASOS,        
 (SELECT TOP 1 OCO.CODIGO  
        FROM RODOCO AS OCO WITH(NOLOCK)   
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODIOS AS NFC WITH(NOLOCK) ON  
  NFC.ID_IOS = OCH.ID_IOS  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS  COD_OCORRENCIA,  
 (SELECT TOP 1 OCO.DESCRI  
        FROM RODOCO AS OCO WITH(NOLOCK)    
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODIOS AS NFC WITH(NOLOCK) ON  
  NFC.ID_IOS = OCH.ID_IOS  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS  OCORRENCIA,  
    (SELECT TOP 1 OCO.CODIGO  
        FROM RODOCO AS OCO WITH(NOLOCK)   
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODIOS AS NFC WITH(NOLOCK) ON  
  NFC.ID_IOS = OCH.ID_IOS  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)  
  AND OCO.CODIGO IN (1,19,25,119)) AS  COD_OCO_FINALIZ,  
 (SELECT TOP 1 OCO.DESCRI  
        FROM RODOCO AS OCO WITH(NOLOCK)   
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODIOS AS NFC WITH(NOLOCK) ON  
  NFC.ID_IOS = OCH.ID_IOS  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)  
  AND OCO.CODIGO IN (1,19,25,119)) AS  OCORRENCIA_FINALIZ,  
 (SELECT TOP 1 ISNULL(OSE.NOMFUN, 'SEM CONFERENTE')  
    FROM OSEFUN OSE WITH(NOLOCK)  
    LEFT OUTER JOIN RODRMC RMC WITH(NOLOCK) ON  
    OSE.CODFUN = RMC.CODFUN  
    LEFT OUTER JOIN RODIRC IRC WITH(NOLOCK) ON  
    RMC.CODFIL = IRC.FILRMC   
    AND RMC.CODRMC = IRC.CODRMC  
    WHERE IRC.FILDOC = CON.CODFIL   
          AND IRC.SERDOC = CON.SERORD  
          AND IRC.CODDOC = CON.CODIGO  
    AND IRC.TIPDOC = 'O') AS CONF_ROM_CARREGTO,  
  (SELECT TOP 1 ISNULL(OSE.NOMFUN, 'SEM CONFERENTE')  
    FROM OSEFUN OSE WITH(NOLOCK)  
    LEFT OUTER JOIN RODRMD RMD WITH(NOLOCK) ON  
    OSE.CODFUN = RMD.CODFUN  
    LEFT OUTER JOIN RODIRD IRD WITH(NOLOCK) ON  
    RMD.CODFIL = IRD.CODFIL   
    AND RMD.CODRMD = IRD.CODRMD  
    WHERE IRD.FILDOC = CON.CODFIL   
          AND IRD.SERDOC = CON.SERORD  
          AND IRD.CODDOC = CON.CODIGO  
    AND IRD.TIPDOC = 'O') AS CONF_ROM_DESCARGA,  
 (SELECT TOP 1 INTD.DATENV  
        FROM INTDOC INTD WITH(NOLOCK)   
          WHERE INTD.FILDOC = CON.CODFIL   
          AND INTD.SERDOC = CON.SERORD  
          AND INTD.CODDOC = CON.CODIGO  
    AND INTD.TIPDOC = 'OST') AS DT_AVERBACAO,  
 (SELECT TOP 1 INTD.PROTOC  
        FROM INTDOC INTD WITH(NOLOCK)   
          WHERE INTD.FILDOC = CON.CODFIL   
          AND INTD.SERDOC = CON.SERORD  
          AND INTD.CODDOC = CON.CODIGO  
    AND INTD.TIPDOC = 'OST') AS PROT_AVERBACAO,  
 (SELECT TOP 1 OCO.CODIGO  
        FROM RODOCO AS OCO WITH(NOLOCK)   
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODIOS AS NFC WITH(NOLOCK) ON  
  NFC.ID_IOS = OCH.ID_IOS  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)  
  ORDER BY OCH.ID_OCH DESC) AS  COD_ULT_OCORRENCIA,  
 (SELECT TOP 1 OCO.DESCRI  
        FROM RODOCO AS OCO WITH(NOLOCK)   
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODIOS AS NFC WITH(NOLOCK) ON  
  NFC.ID_IOS = OCH.ID_IOS  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)  
  ORDER BY OCH.ID_OCH DESC) AS  ULT_OCORRENCIA,  
  S.DESCRI AS SETOR_ENTREGA,  
  G.CODGRO AS COD_GERENC_RISCO,  
  SITUACAO = CASE   
                WHEN G.SITUAC = 'C' THEN  
                       'CANCELADO'  
                WHEN G.SITUAC = 'D' THEN  
      'CADASTRADO'  
       WHEN G.SITUAC = 'F' THEN  
                       'FINALIZADO'  
                END,  
  CPR.ID_CPR AS COMPROVANTE_ENTREGA,  
  (SELECT  DBO.F_SITUACAO_OCS(CON.CODIGO,CON.SERORD,CON.CODFIL,CREM.CODCLIFOR,NFC.SERIEN,NFC.NOTFIS,NULL)) AS SITUACAO_OS,  
  REDC.RAZSOC AS REDESPACHO_PARCEIRO
-- ,
--  coalesce((SELECT DISTINCT CAST(H1.CODOCO AS VARCHAR(003)) +'-' + O.DESCRI +'/' AS [text()]
--		from RODOCH H1,RODOCO O WHERE H1.ID_IOS = NFC.ID_IOS	
--		AND O.CODIGO = H1.CODOCO						
--		FOR XML PATH(''),TYPE).value('.[1]','Varchar(max)'),'') as Ocorrencias_da_NF  
FROM  
    dbo.RODORD AS CON WITH(NOLOCK)   
    INNER JOIN dbo.RODFIL AS FIL WITH(NOLOCK) ON   
    CON.CODFIL = FIL.CODFIL   
    INNER JOIN dbo.RODLIN AS LIN WITH(NOLOCK) ON      
    CON.CODLIN = LIN.CODLIN  
    INNER JOIN dbo.RODCLI AS CPAG WITH(NOLOCK) ON   
    CON.CODPAG = CPAG.CODCLIFOR  
    INNER JOIN dbo.RODMUN AS MCPAG WITH(NOLOCK) ON   
    CPAG.CODMUN = MCPAG.CODMUN   
    LEFT OUTER JOIN dbo.RODCGR AS CGR WITH(NOLOCK) ON  
    CPAG.CODCGR = CGR.CODCGR  
    INNER JOIN dbo.RODCLI AS CREM WITH(NOLOCK) ON   
    CON.CODREM = CREM.CODCLIFOR   
    INNER JOIN RODMUN AS MREM WITH(NOLOCK) ON      
    CREM.CODMUN = MREM.CODMUN  
    LEFT OUTER JOIN dbo.RODMUN AS MUNORI WITH(NOLOCK) ON   
    CREM.CODMUN = MUNORI.CODMUN   
    INNER JOIN dbo.RODCLI AS CDES WITH(NOLOCK) ON   
    CON.CODDES = CDES.CODCLIFOR   
    INNER JOIN dbo.RODMUN AS MUNDES WITH(NOLOCK) ON   
    CDES.CODMUN = MUNDES.CODMUN  
    LEFT OUTER JOIN dbo.RODMOT AS MOT WITH(NOLOCK) ON   
    CON.CODMOT = MOT.CODMOT   
    LEFT OUTER JOIN dbo.RODVEI AS VEI_CAV WITH(NOLOCK) ON   
    CON.PLACA = VEI_CAV.CODVEI   
    LEFT OUTER JOIN dbo.RODFRO AS VEI_FRO WITH(NOLOCK) ON   
    VEI_CAV.CODFRO = VEI_FRO.CODFRO     
    LEFT OUTER JOIN dbo.RODVEI AS VEI_CR_1 WITH(NOLOCK) ON  
    CON.PLACA2 = VEI_CR_1.CODVEI  
    LEFT OUTER JOIN dbo.RODVEI AS VEI_CR_2 WITH(NOLOCK) ON      
    CON.PLACA3 = VEI_CR_2.CODVEI  
    LEFT OUTER JOIN dbo.RODFRA FRA WITH(NOLOCK) ON   
    CON.TABPAD = FRA.CODFRE   
    LEFT OUTER JOIN dbo.RODCMO CMO WITH(NOLOCK) ON  
 FRA.CODCMO = CMO.CODCMO  
 LEFT OUTER JOIN dbo.RODIIF IIF WITH(NOLOCK) ON  
    CON.ID_RODIIF = IIF.ID_RODIIF  
    LEFT OUTER JOIN dbo.RODCLI AS TCOL WITH(NOLOCK) ON   
    CON.TERCOL = TCOL.CODCLIFOR  
    LEFT OUTER JOIN dbo.RODMUN AS MTCOL WITH(NOLOCK) ON   
    TCOL.CODMUN = MTCOL.CODMUN       
    LEFT OUTER JOIN dbo.RODCLI AS TENT WITH(NOLOCK) ON   
    CON.TERENT = TENT.CODCLIFOR   
    LEFT OUTER JOIN dbo.RODMUN AS MTENT WITH(NOLOCK) ON   
    TENT.CODMUN = MTENT.CODMUN            
    LEFT OUTER JOIN RECVEN AS VEND WITH(NOLOCK) ON  
    CPAG.CODVEN = VEND.CODVEN    
    LEFT OUTER JOIN CRMREG AS REG_O WITH(NOLOCK) ON  
 CON.REGREM = REG_O.CODREG  
 LEFT OUTER JOIN CRMREG AS REG_D WITH(NOLOCK) ON  
 CON.CODREG = REG_D.CODREG  
 LEFT OUTER JOIN RODMAN MAN WITH(NOLOCK) ON  
 CON.FILMAN=MAN.CODFIL  
 AND CON.SERMAN=MAN.SERMAN  
 AND CON.CODMAN=MAN.CODMAN  
 LEFT OUTER JOIN dbo.RODCLI AS CRED WITH(NOLOCK) ON   
    CON.CODRED = CRED.CODCLIFOR   
 LEFT OUTER JOIN RECVEN DESV WITH(NOLOCK) ON  
 CREM.CODVEN = DESV.CODVEN  
 LEFT OUTER JOIN RECVEN CONSV WITH(NOLOCK) ON  
 CREM.CODVEN = CONSV.CODVEN  
 LEFT OUTER JOIN RODCLI CCONS WITH(NOLOCK) ON  
 CON.CODICO = CCONS.CODCLIFOR  
    LEFT OUTER JOIN RODCLI PROP WITH(NOLOCK) ON  
 VEI_CAV.CODPRO = PROP.CODCLIFOR  
 LEFT OUTER JOIN RODSET S WITH(NOLOCK) ON  
 CDES.CODSETCL = S.CODSETCL  
 LEFT OUTER JOIN RODGRO G WITH(NOLOCK) ON  
 CON.CODIGO=G.CODDOC  
 AND CON.CODFIL=G.FILDOC  
 AND CON.SERORD=G.SERDOC  
    LEFT OUTER JOIN RODDOP DOP WITH(NOLOCK) ON  
 CON.CODIGO = DOP.CODDOC  
 AND CON.SERORD = DOP.SERDOC  
 AND CON.CODFIL = DOP.FILDOC  
 AND DOP.TIPDOC = 'OST'  
 LEFT OUTER JOIN RODCPR CPR WITH(NOLOCK) ON  
 DOP.ID_CPR = CPR.ID_CPR  
 LEFT OUTER JOIN RODIOS NFC WITH(NOLOCK) ON  
 CON.CODIGO = NFC.CODORD  
 AND CON.SERCON = NFC.SERORD  
 AND CON.CODFIL = NFC.FILORD  
 LEFT OUTER JOIN RODRED RED WITH(NOLOCK) ON  
 CON.CODFIL=RED.FILDOC  
 AND CON.SERORD=RED.SERDOC  
 AND CON.CODIGO=RED.CODDOC  
 AND RED.TIPDOC='OST'  
 LEFT OUTER JOIN RODCLI REDC WITH(NOLOCK) ON  
 ISNULL (RED.REDMU2,RED.REDMUN)=REDC.CODCLIFOR  
WHERE       
   (CPAG.CODCLIFOR = @PAGADOR OR @PAGADOR = 0)
   AND CON.DATCAD >= @DATA_INI AND CON.DATCAD < DATEADD(DAY,1,@DATA_FIM)    
   AND NOT EXISTS (SELECT 1 FROM RODORC O WITH(NOLOCK) WHERE CON.CODFIL=O.FILORD AND CON.SERORD=O.SERORD AND CON.CODIGO=O.CODORD)  
   AND NOT EXISTS (SELECT 1 FROM RODORN O WITH(NOLOCK) WHERE CON.CODFIL=O.FILORD AND CON.SERORD=O.SERORD AND CON.CODIGO=O.CODORD)  
   AND (CREM.CODCLIFOR = @REMETENTE OR @REMETENTE = 0)  
   AND (CDES.CODCLIFOR = @DESTINATARIO OR @DESTINATARIO = 0)  
   AND (CON.SITUAC NOT IN ('C', 'I'))
   AND ('OST' = @TIPDOC OR @TIPDOC = '')  
   AND (CPAG.CODCGC LIKE @PAG_CNPJ OR @PAG_CNPJ = '')  
   AND (VEI_CAV.CODVEI = @CODVEI OR @CODVEI = '')  
   AND (IIF(CON.SITDUP IS NULL,'E',CON.SITDUP) = @FATURADOS OR @FATURADOS = '') 
   AND (CON.CODFIL = @FILIAL OR @FILIAL = 0)  
   AND (FRA.CODCMO = @MODAL OR @MODAL = 0)  
   AND (CON.FILDUP = @FILIAL_FATURA OR @FILIAL_FATURA = 0)  
   AND (CON.NUMDUP = @FATURA OR @FATURA = 0)  
   AND (ISNULL (RED.REDMU2,RED.REDMUN) = @REDESPACHO OR @REDESPACHO = 0)
   UNION ALL  
--# NF DE SERVIÇO # -  
SELECT    
    'NFS' AS TIPDOC,
    CON.TIPORD AS TIPCON,      
 CON.SITDUP,     
    (SELECT TOP 1 NF.DATEMI FROM ESTNOT NF WITH(NOLOCK)   
         WHERE  NF.CODFIL = CON.FILNOT AND  
                NF.SERSUB = CON.SERNOT AND  
                NF.CODIGO = CON.CODNOT AND  
                NF.SERSUB IN ('E', 'ND')) AS DATA,  
    0 AS CODFIS,   
    CON.DIFERE AS DIFERENCIAL,  
 --FIL.NOMEAB AS FILIAL,   
 FIL.CODCGC AS CNPJ_TRANSPORTADOR,  
 CON.FILNOT AS COD_FILIAL,  
    CON.SERNOT AS SERIE,   
    CON.CODNOT AS DOCUMENTO,  
       (SELECT TOP 1 CSC.CODOCS  
             FROM  
                    RODSOR CSC WITH(NOLOCK)  
             WHERE  
                    CON.CODFIL = CSC.FILORD  
                    AND CON.SERORD = CSC.SERORD  
                    AND CON.CODIGO = CSC.CODORD)  AS COD_OCS,  
    CON.CODLIN AS LINHA,  
    VEI_CAV.CODVEI AS CODVEI,  
 PROP.CODCGC AS CNPJ_PROPRIETARIO,  
 PROP.CODCPF AS CPF_PROPRIETATIO,  
 PROP.RAZSOC AS NOME_PROPRIETATIO,  
 PROP.FISJUR,  
    VEI_CAV.NUMVEI  AS PLACA_CM,   
    VEI_CR_1.NUMVEI AS PLACA_CR_1,  
    MOT.NOMMOT AS MOTORISTA,   
 MOT.NUMCPF AS CPF_MOTORISTA,  
 (SELECT TOP 1 MOTM.NOMMOT  
     FROM RODMAN AS MAN WITH(NOLOCK)  
        LEFT OUTER JOIN RODMOT AS MOTM WITH(NOLOCK) ON   
        MAN.CODMO1 = MOTM.CODMOT  
        WHERE (MAN.CODFIL= CON.FILMAN)   
        AND (MAN.SERMAN = CON.SERMAN)   
        AND (MAN.CODMAN = CON.CODMAN)) AS MOT_MANIFESTO,   
    CPAG.CODCLIFOR AS COD_PAGADOR,   
    CPAG.CODCGC AS PAG_CNPJ,  
    CPAG.RAZSOC AS PAGADOR,   
    CPAG.NOMEAB AS NOME_ABREVIADO,  
 VEND.NOMEVE AS NOME_VENDEDOR,  
 CREM.CODVEN AS COD_VENDEDOR_REM,  
 CCONS.CODVEN AS COD_VENDEDOR_CONS,  
 CONSV.NOMEVE AS VENDEDOR_CONS,  
 CDES.CODVEN AS COD_VENDEDOR_DES,  
 DESV.NOMEVE AS VENDEDOR_DES,   
    CREM.CODCLIFOR AS COD_REMETENTE,  
    CREM.CODCGC AS REM_CNPJ,  
    CAST(CREM.INSCRI AS VARCHAR) AS REM_INSCRI,  
    CREM.RAZSOC AS REMETENTE,  
    MREM.DESCRI AS MUN_REMETENTE,  
    MREM.ESTADO AS EST_REMETENTE,  
    CDES.CODCLIFOR AS COD_DESTINATARIO,  
    CDES.CODCGC AS DES_CNPJ,  
 CDES.CODCEP AS CEP_DESTINO,  
 CAST(CDES.TIPLOG AS VARCHAR) AS LOGRAD_DESTINO,  
 CDES.NUMERO,  
 CDES.ENDERE AS END_DESTINO,  
 CDES.BAIRRO AS BAIRRO_DESTINO,  
 CDES.RAZSOC AS DESTINATARIO,  
    MUNDES.DESCRI AS MUN_DESTINATARIO,  
    MUNDES.ESTADO AS EST_DESTINATARIO,  
    CRED.RAZSOC AS REDESPACHO,  
 CAST(CRED.TIPLOG AS VARCHAR) AS LOGRAD_REDESPACHO,  
 CRED.NUMERO AS NUM_REDESPACHO,  
 CRED.ENDERE AS END_REDESPACHO,   
    TCOL.RAZSOC AS TCOLETA,  
    MTCOL.DESCRI AS MUN_TCOLETA,  
    MTCOL.ESTADO AS EST_TCOLETA,  
    TENT.RAZSOC AS TENTREGA,  
    MTENT.DESCRI AS MUN_TENTREGA,  
    MTENT.ESTADO AS EST_TENTREGA,  
    NULL AS RECEBEDOR,  
    (SELECT TOP 1 DUP.DATEMI  
        FROM dbo.RODDUP DUP WITH(NOLOCK)   
             INNER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL  
                                  AND DUP.NUMDUP = IDU.NUMDUP  
             INNER JOIN ESTNOT NF WITH(NOLOCK)  ON IDU.FILDOC = NF.CODFIL   
                                                 AND IDU.SERDOC = NF.SERSUB      
                                                 AND IDU.CODDOC = NF.CODIGO  
                  INNER JOIN RODORN O WITH(NOLOCK)  ON  O.FILNOT   = NF.CODFIL  
                                      AND O.SERNOT   = NF.SERSUB  
                                                 AND O.CODNOT   = NF.CODIGO  
          WHERE DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'NF'  
          AND CON.CODFIL = O.FILORD  
          AND CON.SERORD = O.SERORD  
          AND CON.CODIGO = O.CODORD )    AS DT_EMISSAO_DUP,  
    (SELECT TOP 1 IDU.CODFIL  
            FROM dbo.RODDUP DUP WITH(NOLOCK)   
             INNER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL  
                                  AND DUP.NUMDUP = IDU.NUMDUP  
             INNER JOIN ESTNOT NF WITH(NOLOCK) ON IDU.FILDOC = NF.CODFIL   
                                                 AND IDU.SERDOC = NF.SERSUB            
                                                 AND IDU.CODDOC = NF.CODIGO  
                  INNER JOIN RODORN O WITH(NOLOCK) ON  O.FILNOT   = NF.CODFIL  
                                                 AND O.SERNOT   = NF.SERSUB  
                                                 AND O.CODNOT   = NF.CODIGO  
          WHERE DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'NF'  
          AND CON.CODFIL = O.FILORD  
          AND CON.SERORD = O.SERORD  
          AND CON.CODIGO = O.CODORD )    AS COD_FILIAL_DUP,      
    (SELECT TOP 1 IDU.NUMDUP  
         FROM dbo.RODDUP DUP WITH(NOLOCK)   
             INNER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL  
                                  AND DUP.NUMDUP = IDU.NUMDUP  
             INNER JOIN ESTNOT NF WITH(NOLOCK) ON IDU.FILDOC = NF.CODFIL   
                                                 AND IDU.SERDOC = NF.SERSUB            
                                                 AND IDU.CODDOC = NF.CODIGO  
                  INNER JOIN RODORN O WITH(NOLOCK) ON  O.FILNOT   = NF.CODFIL  
                                                 AND O.SERNOT   = NF.SERSUB  
                                                 AND O.CODNOT   = NF.CODIGO  
          WHERE DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'NF'  
          AND CON.CODFIL = O.FILORD  
          AND CON.SERORD = O.SERORD  
          AND CON.CODIGO = O.CODORD )   AS COD_FATURA,   
    (SELECT TOP 1 DUP.DATVEN  
         FROM dbo.RODDUP DUP WITH(NOLOCK)   
             INNER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL  
                                  AND DUP.NUMDUP = IDU.NUMDUP  
             INNER JOIN ESTNOT NF WITH(NOLOCK) ON IDU.FILDOC = NF.CODFIL   
                                                 AND IDU.SERDOC = NF.SERSUB            
                                                 AND IDU.CODDOC = NF.CODIGO  
                  INNER JOIN RODORN O WITH(NOLOCK) ON  O.FILNOT   = NF.CODFIL  
                                                 AND O.SERNOT   = NF.SERSUB  
                                                 AND O.CODNOT   = NF.CODIGO  
          WHERE DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'NF'  
          AND CON.CODFIL = O.FILORD  
          AND CON.SERORD = O.SERORD  
          AND CON.CODIGO = O.CODORD ) AS DT_VENC_DUP,  
    (SELECT TOP 1 M.DATLAN  
         FROM dbo.RODDUP DUP WITH(NOLOCK)  
             INNER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL  
                                  AND DUP.NUMDUP = IDU.NUMDUP  
             INNER JOIN ESTNOT NF WITH(NOLOCK) ON IDU.FILDOC = NF.CODFIL   
                                               AND IDU.SERDOC = NF.SERSUB            
                                                 AND IDU.CODDOC = NF.CODIGO  
                  INNER JOIN RODORN O WITH(NOLOCK) ON  O.FILNOT   = NF.CODFIL  
                                                 AND O.SERNOT   = NF.SERSUB  
                                                 AND O.CODNOT   = NF.CODIGO  
                  INNER JOIN RECMEN M WITH(NOLOCK) ON  DUP.CODFIL = M.CODFIL  
                                                 AND CAST(DUP.NUMDUP AS VARCHAR)=M.NUMDUP  
          WHERE DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'NF'  
          AND CON.CODFIL = O.FILORD  
          AND CON.SERORD = O.SERORD  
          AND CON.CODIGO = O.CODORD  
          AND M.DEBCRE = 'C'  
          ORDER BY M.DATLAN DESC )   AS DT_REC_FATURA,   
    (SELECT TOP 1 NFC.ORDCOM  
        FROM dbo.RODIOS AS NFC WITH(NOLOCK)  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS REF_CLIENTE,  
    (SELECT TOP 1 NFC.ITECOM  
        FROM dbo.RODIOS AS NFC WITH(NOLOCK)  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS NOSSA_REF,  
--		VW.QUANTI AS QTD_VOL ,
		(SELECT SUM(V1.QUANTI) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as QTD_VOL,
		(SELECT SUM(V1.PESO) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as PESO,	
--		VW.PESO AS PESO,      
		0 AS LARG_CUB,  
		0 AS ALTURA_CUB,  
		0 AS PROFUN_CUB,      
		0 AS PESO_CUB,          
		(SELECT SUM(V1.PESCAL) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as PESO_CALC,	
--		VW.PESCAL AS PESO_CALC,          
		(SELECT SUM(V1.VLRMER) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as VLR_MERC,	
--		VW.VLRMER AS VLR_MERC,  
   (SELECT TOP 1 NFC.ESPECI  
        FROM dbo.RODIOS AS NFC WITH(NOLOCK)  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS ESPECIE,  
   (SELECT TOP 1 PRO.DESCRI  
 FROM dbo.RODIOS AS NFC WITH(NOLOCK)   
        INNER JOIN dbo.RODPRO AS PRO WITH(NOLOCK) ON   
        NFC.CODPROTR = PRO.CODPROTR  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS PRODUTO,   
    (SELECT TOP 1 NFC.DATENT  
        FROM dbo.RODIOS AS NFC WITH(NOLOCK)   
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS DATA_ENTREGA,  
		(SELECT SUM(V1.FREPES) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as FRETE_PESO,	
--		VW.FREPES AS FRETE_PESO,
		(SELECT SUM(V1.FREVAL) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as FRETE_VALOR,	
--		VW.FREVAL AS FRETE_VALOR, 
		(SELECT SUM(V1.DESVAL) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as VLR_DESPACHO,	
--		VW.DESVAL AS VLR_DESPACHO,
		(SELECT SUM(V1.VLRPED) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as VLR_PEDAGIO,	
--		VW.VLRPED AS VLR_PEDAGIO,
		CON.ALIISS,  
		CON.ALICOT,  
		(SELECT SUM(V1.VLRPIS) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as PIS_COFINS,	
--		VW.VLRPIS AS PIS_COFINS,
		(SELECT SUM(V1.ICMVLR) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as VLR_ICMS,	
--		VW.ICMVLR AS VLR_ICMS,
		(SELECT SUM(V1.VLRISS) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as VLR_ISS,	
--		VW.VLRISS AS VLR_ISS,
		(SELECT SUM(V1.BASCAL) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as BASE_CALCULO,	
--		VW.BASCAL AS BASE_CALCULO,
		(SELECT SUM(V1.TOTFRE) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as VLR_TOTAL_FRETE,	
--		VW.TOTFRE AS VLR_TOTAL_FRETE,  
		(SELECT SUM(V1.VLRAJU) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as VLR_AJUDANTE,	
--		VW.VLRAJU AS VLR_AJUDANTE, 
		(SELECT SUM(V1.VLRCOL) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as PLAT_REF_CAR_CC,	
--		VW.VLRCOL AS PLAT_REF_CAR_CC,
		(SELECT SUM(V1.VLRENT) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as DGR_DEV_CC,	
--		VW.VLRENT AS DGR_DEV_CC,
		(SELECT SUM(V1.VLRCAR) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as VLR_CARGA,	
--		VW.VLRCAR AS VLR_CARGA,
		(SELECT SUM(V1.DESCAR) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as VLR_DESCARGA,	
--		VW.DESCAR AS VLR_DESCARGA,
		(SELECT SUM(V1.TAXDIF) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as VLR_TXDIF,	
--		VW.TAXDIF AS VLR_TXDIF,
		(SELECT SUM(V1.VLRSUF) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as VLR_SUFRAMA,	
--		VW.VLRSUF AS VLR_SUFRAMA,  
		(SELECT SUM(V1.SECVAL) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as VLR_SECCAT,	
--		VW.SECVAL AS VLR_SECCAT,
		(SELECT SUM(V1.VLRGRI) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as VLR_GRIS,	
--		VW.VLRGRI AS VLR_GRIS,
		(SELECT SUM(V1.VLRESC) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as VLR_ESCOLTA,	
--		VW.VLRESC AS VLR_ESCOLTA,
		(SELECT SUM(V1.VLCOMP) from VW_RODORD_ESTNOT V1 
		where V1.CODNOT = CON.CODNOT and
		V1.SERNOT = CON.SERNOT and
		V1.FILNOT = CON.FILNOT) as TX_ADICIONAL,	
--		VW.VLCOMP AS TX_ADICIONAL,   
		CON.OBSCON AS OBSERVACAO,  
		CON.TABPAD,  
		CON.ID_RODIIF AS ITEM_TARIFA,  
		FRA.CODCMO,  
		CMO.DESCRI,  
		CON.USUATU,  
		CON.DDTCHE AS DESC_HR_CHEGADA,  
    CON.DDTENT AS DESC_RH_ENTRADA,  
    CON.DDTSAI AS DESSC_HR_SAIDA,  
    CON.CDTCHE AS CARG_HR_CHEGADA,  
    CON.CDTENT AS CARG_HR_ENTRADA,  
    CON.CDTSAI AS CARG_HR_SAIDA,  
 REG_O.DESCRI AS REGIAO_ORIGEM,  
 REG_D.DESCRI AS REGIAO_DESTINO,  
   (SELECT TOP 1 MAN.CODMAN  
        FROM RODMAN MAN WITH(NOLOCK)   
          WHERE MAN.CODFIL = CON.FILMAN   
          AND MAN.SERMAN = CON.SERMAN  
          AND MAN.CODMAN = CON.CODMAN  
    AND MAN.TIPMAN <> '2') AS MANIFESTO,   
  (SELECT TOP 1 MAN.CODFIL  
        FROM RODMAN MAN WITH(NOLOCK)   
          WHERE MAN.CODFIL = CON.FILMAN   
          AND MAN.SERMAN = CON.SERMAN  
          AND MAN.CODMAN = CON.CODMAN  
    AND MAN.TIPMAN <> '2') AS FILIAL_MANIFESTO,  
  (SELECT TOP 1 MAN.SERMAN  
        FROM RODMAN MAN WITH(NOLOCK)   
          WHERE MAN.CODFIL = CON.FILMAN   
          AND MAN.SERMAN = CON.SERMAN  
          AND MAN.CODMAN = CON.CODMAN  
    AND MAN.TIPMAN <> '2') AS SERIE_MANIFESTO,  
 (SELECT TOP 1 MAN.FILDES  
        FROM RODMAN MAN WITH(NOLOCK)   
          WHERE MAN.CODFIL = CON.FILMAN   
          AND MAN.SERMAN = CON.SERMAN  
          AND MAN.CODMAN = CON.CODMAN  
    AND MAN.TIPMAN <> '2') AS FILIAL_DESTINO,  
  TIP0_MAN = CASE  
                WHEN MAN.TIPMAN = '1' THEN  
                       'LOTAÇÃO'  
                WHEN TIPMAN = '2' THEN  
                       'TRANSFERÊNCIA'  
                WHEN TIPMAN = '3' THEN  
                       'FRACIONADA'  
                WHEN TIPMAN = '4' THEN  
                       'MISTA'  
                WHEN TIPMAN = '5' THEN  
                       'RODORAPIDO'  
                WHEN TIPMAN = '6' THEN  
                       'DISTRIBUIÇÃO'  
                WHEN TIPMAN = '7' THEN  
                       'COLETA'  
                WHEN TIPMAN = '8' THEN  
                       'REENTREGA'  
                WHEN TIPMAN = '9' THEN  
                       'DEVOLUÇÃO'  
                WHEN TIPMAN = '10' THEN  
                       'COMPLEMENTAR'  
                WHEN TIPMAN = '11' THEN  
                       'VIAGEM'  
                WHEN TIPMAN = '12' THEN  
                       'RETIRADA'  
                WHEN TIPMAN = '13' THEN  
                       'TRANSF.AQUAVIARIA'  
                WHEN TIPMAN = '14' THEN  
                       'AÉREO'  
                WHEN TIPMAN = '15' THEN  
                       'INTERNACIONAL'  
          END,  
  (SELECT TOP 1 MANT.CODMAN  
        FROM RODMAN MANT WITH(NOLOCK), RODIMA IMA_T WITH(NOLOCK)  
          WHERE MANT.CODFIL = IMA_T.FILMAN   
          AND MANT.SERMAN = IMA_T.SERMAN  
          AND MANT.CODMAN = IMA_T.CODMAN  
    AND IMA_T.FILDOC = CON.CODFIL   
          AND IMA_T.SERDOC = CON.SERORD  
          AND IMA_T.CODDOC = CON.CODIGO  
    AND MANT.TIPMAN = '2') AS MANIFESTO_TRANSF,   
  (SELECT TOP 1 MANT.CODFIL  
        FROM RODMAN MANT WITH(NOLOCK), RODIMA IMA_T WITH(NOLOCK)  
          WHERE MANT.CODFIL = IMA_T.FILMAN   
          AND MANT.SERMAN = IMA_T.SERMAN  
          AND MANT.CODMAN = IMA_T.CODMAN  
    AND IMA_T.FILDOC = CON.CODFIL   
          AND IMA_T.SERDOC = CON.SERORD  
          AND IMA_T.CODDOC = CON.CODIGO  
    AND MANT.TIPMAN = '2') AS FILIAL_MANIFESTO_TRANSF,  
  (SELECT TOP 1 MANT.SERMAN  
        FROM RODMAN MANT WITH(NOLOCK)  
    WHERE MAN.CODFIL = CON.FILMAN   
          AND MANT.SERMAN = CON.SERMAN  
          AND MANT.CODMAN = CON.CODMAN  
    AND MANT.TIPMAN = '2') AS SERIE_MANIFESTO_TRANSF,  
 (SELECT TOP 1 MANT.FILDES  
        FROM RODMAN MANT WITH(NOLOCK)  
    WHERE MAN.CODFIL = CON.FILMAN   
          AND MANT.SERMAN = CON.SERMAN  
          AND MANT.CODMAN = CON.CODMAN  
    AND MANT.TIPMAN = '2') AS FILIAL_DESTINO_TRANSF,  
 'S' AS CTEAUT,  
 (SELECT TOP 1 NF.ISS_ID FROM ESTNOT NF WITH(NOLOCK)   
         WHERE  NF.CODFIL = CON.FILNOT AND  
                NF.SERSUB = CON.SERNOT AND  
                NF.CODIGO = CON.CODNOT AND  
                NF.SERSUB IN ('E', 'ND')) AS CHAVE_CTE,  
 (SELECT TOP 1 NF.ISSPRO FROM ESTNOT NF WITH(NOLOCK)   
         WHERE  NF.CODFIL = CON.FILNOT AND  
                NF.SERSUB = CON.SERNOT AND  
                NF.CODIGO = CON.CODNOT AND  
                NF.SERSUB IN ('E', 'ND')) AS PROTOC_CTE,  
 'N' AS FAT_BLOQUEADO,  
 0 AS ICM_INCENTIVADO,  
 'N' AS A_VISTA,  
 CON.FILCOT AS FILIAL_COTACAO,  
 CON.ESTFEC AS COTACAO,  
 CON.DATLME AS PRAZO_ENTREGA,  
(SELECT TOP 1 IFR.METDIA  
 FROM RODIFR IFR WITH(NOLOCK)  
 WHERE CON.TABPAD=IFR.CODFRE  
 AND CON.ID_RODIIF=IIF.ID_RODIIF  
 AND IIF.ID_RODIFR=IFR.ID_RODIFR) AS METDIA,  
 (SELECT TOP 1 NF.PREFAT FROM ESTNOT NF WITH(NOLOCK)   
         WHERE  NF.CODFIL = CON.FILNOT AND  
                NF.SERSUB = CON.SERNOT AND  
                NF.CODIGO = CON.CODNOT AND  
                NF.SERSUB IN ('E', 'ND')) AS PREFAT,  
    (SELECT TOP 1 datediff(day,OCH.DATOCO,CON.DATLME)  
             FROM  
                    RODOCO AS OCO WITH(NOLOCK)  
                    LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK)  
                           ON OCO.CODIGO = OCH.CODOCO  
                    LEFT OUTER JOIN RODIOS AS NFC WITH(NOLOCK)  
                           ON NFC.ID_IOS = OCH.ID_IOS  
             WHERE  
                    (NFC.FILORD = CON.CODFIL)                 
                    AND (NFC.SERORD = CON.SERORD)  
                    AND (NFC.CODORD = CON.CODIGO)  
                    AND OCO.CODIGO = 1) AS DIAS_ATRASOS,   
 (SELECT TOP 1 OCO.CODIGO  
        FROM RODOCO AS OCO WITH(NOLOCK)   
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODIOS AS NFC WITH(NOLOCK) ON  
  NFC.ID_IOS = OCH.ID_IOS  
        WHERE (NFC.FILORD = CON.CODFIL)   
 AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS  COD_OCORRENCIA,  
 (SELECT TOP 1 OCO.DESCRI  
        FROM RODOCO AS OCO WITH(NOLOCK)   
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODIOS AS NFC WITH(NOLOCK) ON  
  NFC.ID_IOS = OCH.ID_IOS  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)) AS  OCORRENCIA,  
 (SELECT TOP 1 OCO.CODIGO  
        FROM RODOCO AS OCO WITH(NOLOCK)   
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODIOS AS NFC WITH(NOLOCK) ON  
  NFC.ID_IOS = OCH.ID_IOS  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)  
  AND OCO.CODIGO IN (1,19,25,119)) AS  COD_OCO_FINALIZ,  
 (SELECT TOP 1 OCO.DESCRI  
        FROM RODOCO AS OCO WITH(NOLOCK)  
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODIOS AS NFC WITH(NOLOCK) ON  
  NFC.ID_IOS = OCH.ID_IOS  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)  
  AND OCO.CODIGO IN (1,19,25,119)) AS  OCORRENCIA_FINALIZ,  
 (SELECT TOP 1 ISNULL(OSE.NOMFUN, 'SEM CONFERENTE')  
    FROM OSEFUN OSE WITH(NOLOCK)  
    LEFT OUTER JOIN RODRMC RMC WITH(NOLOCK) ON  
    OSE.CODFUN = RMC.CODFUN  
    LEFT OUTER JOIN RODIRC IRC WITH(NOLOCK) ON  
    RMC.CODFIL = IRC.FILRMC   
    AND RMC.CODRMC = IRC.CODRMC  
    WHERE IRC.FILDOC = CON.CODFIL   
          AND IRC.SERDOC = CON.SERORD  
          AND IRC.CODDOC = CON.CODIGO  
    AND IRC.TIPDOC = 'O') AS CONF_ROM_CARREGTO,  
  (SELECT TOP 1 ISNULL(OSE.NOMFUN, 'SEM CONFERENTE')  
    FROM OSEFUN OSE WITH(NOLOCK)  
    LEFT OUTER JOIN RODRMD RMD WITH(NOLOCK) ON  
    OSE.CODFUN = RMD.CODFUN  
    LEFT OUTER JOIN RODIRD IRD WITH(NOLOCK) ON  
    RMD.CODFIL = IRD.CODFIL  
    AND RMD.CODRMD = IRD.CODRMD  
    WHERE IRD.FILDOC = CON.CODFIL   
          AND IRD.SERDOC = CON.SERORD  
          AND IRD.CODDOC = CON.CODIGO  
    AND IRD.TIPDOC = 'O') AS CONF_ROM_DESCARGA,  
 (SELECT TOP 1 INTD.DATENV  
        FROM INTDOC INTD WITH(NOLOCK)   
          WHERE INTD.FILDOC = CON.CODFIL   
          AND INTD.SERDOC = CON.SERORD  
          AND INTD.CODDOC = CON.CODIGO  
    AND INTD.TIPDOC = 'OST') AS DT_AVERBACAO,  
 (SELECT TOP 1 INTD.PROTOC    
        FROM INTDOC INTD WITH(NOLOCK)   
          WHERE INTD.FILDOC = CON.CODFIL   
          AND INTD.SERDOC = CON.SERORD  
          AND INTD.CODDOC = CON.CODIGO  
    AND INTD.TIPDOC = 'OST') AS PROT_AVERBACAO,  
 (SELECT TOP 1 OCO.CODIGO  
        FROM RODOCO AS OCO WITH(NOLOCK)   
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODIOS AS NFC WITH(NOLOCK) ON  
  NFC.ID_IOS = OCH.ID_IOS  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)  
  ORDER BY OCH.ID_OCH DESC) AS  COD_ULT_OCORRENCIA,  
 (SELECT TOP 1 OCO.DESCRI  
        FROM RODOCO AS OCO WITH(NOLOCK)   
        LEFT OUTER JOIN RODOCH AS OCH WITH(NOLOCK) ON   
        OCO.CODIGO = OCH.CODOCO  
  LEFT OUTER JOIN RODIOS AS NFC WITH(NOLOCK) ON  
  NFC.ID_IOS = OCH.ID_IOS  
        WHERE (NFC.FILORD = CON.CODFIL)   
        AND (NFC.SERORD = CON.SERORD)   
        AND (NFC.CODORD = CON.CODIGO)  
  ORDER BY OCH.ID_OCH DESC) AS  ULT_OCORRENCIA,  
  S.DESCRI AS SETOR_ENTREGA,  
  G.CODGRO AS COD_GERENC_RISCO,  
  SITUACAO = CASE   
                WHEN G.SITUAC = 'C' THEN  
                       'CANCELADO'  
                WHEN G.SITUAC = 'D' THEN  
                       'CADASTRADO'  
       WHEN G.SITUAC = 'F' THEN  
                       'FINALIZADO'  
                END,  
  '' AS COMPROVANTE_ENTREGA,  
  (SELECT  DBO.F_SITUACAO_OCS(CON.CODIGO,CON.SERORD,CON.CODFIL,CREM.CODCLIFOR,NFC.SERIEN,NFC.NOTFIS,NULL)) AS SITUACAO_OS,  
  REDC.RAZSOC AS REDESPACHO_PARCEIRO
--  ,
--  coalesce((SELECT DISTINCT CAST(H1.CODOCO AS VARCHAR(003)) +'-' + O.DESCRI +'/' AS [text()]
--		from RODOCH H1,RODOCO O WHERE H1.ID_IOS = NFC.ID_IOS	
--		AND O.CODIGO = H1.CODOCO						
--		FOR XML PATH(''),TYPE).value('.[1]','Varchar(max)'),'') as Ocorrencias_da_NF  
FROM  
    dbo.RODORD AS CON WITH(NOLOCK)   
    INNER JOIN dbo.RODFIL AS FIL WITH(NOLOCK) ON 
    CON.CODFIL = FIL.CODFIL   
	INNER JOIN VW_RODORD_ESTNOT VW WITH(NOLOCK) ON
	VW.CODNOT = CON.CODNOT and VW.FILNOT = CON.FILNOT and VW.SERNOT = CON.SERNOT
    INNER JOIN dbo.RODLIN AS LIN WITH(NOLOCK) ON      
    CON.CODLIN = LIN.CODLIN  
    INNER JOIN dbo.RODCLI AS CPAG WITH(NOLOCK) ON   
    CON.CODPAG = CPAG.CODCLIFOR   
    INNER JOIN dbo.RODMUN AS MCPAG WITH(NOLOCK) ON   
    CPAG.CODMUN = MCPAG.CODMUN  
    LEFT OUTER JOIN dbo.RODCGR AS CGR WITH(NOLOCK) ON  
    CPAG.CODCGR = CGR.CODCGR  
    INNER JOIN dbo.RODCLI AS CREM WITH(NOLOCK) ON   
    CON.CODREM = CREM.CODCLIFOR   
    INNER JOIN RODMUN AS MREM WITH(NOLOCK) ON      
    CREM.CODMUN = MREM.CODMUN  
    LEFT OUTER JOIN dbo.RODMUN AS MUNORI WITH(NOLOCK) ON   
    CREM.CODMUN = MUNORI.CODMUN   
    INNER JOIN dbo.RODCLI AS CDES WITH(NOLOCK) ON   
    CON.CODDES = CDES.CODCLIFOR   
    INNER JOIN dbo.RODMUN AS MUNDES WITH(NOLOCK) ON   
    CDES.CODMUN = MUNDES.CODMUN   
    LEFT OUTER JOIN dbo.RODMOT AS MOT WITH(NOLOCK) ON   
    CON.CODMOT = MOT.CODMOT   
    LEFT OUTER JOIN dbo.RODVEI AS VEI_CAV WITH(NOLOCK) ON   
    CON.PLACA = VEI_CAV.CODVEI  
    LEFT OUTER JOIN dbo.RODFRO AS VEI_FRO WITH(NOLOCK) ON   
    VEI_CAV.CODFRO = VEI_FRO.CODFRO      
    LEFT OUTER JOIN dbo.RODVEI AS VEI_CR_1 WITH(NOLOCK) ON  
    CON.PLACA2 = VEI_CR_1.CODVEI  
    LEFT OUTER JOIN dbo.RODVEI AS VEI_CR_2 WITH(NOLOCK) ON      
    CON.PLACA3 = VEI_CR_2.CODVEI  
    LEFT OUTER JOIN dbo.RODFRA FRA WITH(NOLOCK) ON   
    CON.TABPAD = FRA.CODFRE   
    LEFT OUTER JOIN dbo.RODCMO CMO WITH(NOLOCK) ON  
 FRA.CODCMO = CMO.CODCMO  
 LEFT OUTER JOIN dbo.RODIIF IIF WITH(NOLOCK) ON  
 CON.ID_RODIIF = IIF.ID_RODIIF  
    LEFT OUTER JOIN dbo.RODCLI AS TCOL WITH(NOLOCK) ON   
    CON.TERCOL = TCOL.CODCLIFOR  
    LEFT OUTER JOIN dbo.RODMUN AS MTCOL WITH(NOLOCK) ON   
    TCOL.CODMUN = MTCOL.CODMUN      
    LEFT OUTER JOIN dbo.RODCLI AS TENT WITH(NOLOCK) ON   
    CON.TERENT = TENT.CODCLIFOR  
    LEFT OUTER JOIN dbo.RODMUN AS MTENT WITH(NOLOCK) ON   
    TENT.CODMUN = MTENT.CODMUN         
    LEFT OUTER JOIN RECVEN AS VEND WITH(NOLOCK) ON  
    CPAG.CODVEN = VEND.CODVEN  
 LEFT OUTER JOIN CRMREG AS REG_O WITH(NOLOCK) ON  
 CON.REGREM = REG_O.CODREG  
 LEFT OUTER JOIN CRMREG AS REG_D WITH(NOLOCK) ON  
 CON.CODREG = REG_D.CODREG  
 LEFT OUTER JOIN RODMAN MAN WITH(NOLOCK) ON  
 CON.FILMAN=MAN.CODFIL  
 AND CON.SERMAN=MAN.SERMAN  
 AND CON.CODMAN=MAN.CODMAN  
 LEFT OUTER JOIN dbo.RODCLI AS CRED WITH(NOLOCK) ON   
    CON.CODRED = CRED.CODCLIFOR   
 LEFT OUTER JOIN RECVEN DESV WITH(NOLOCK) ON  
 CREM.CODVEN = DESV.CODVEN  
 LEFT OUTER JOIN RECVEN CONSV WITH(NOLOCK) ON  
 CREM.CODVEN = CONSV.CODVEN  
 LEFT OUTER JOIN RODCLI CCONS WITH(NOLOCK) ON  
 CON.CODICO = CCONS.CODCLIFOR  
    LEFT OUTER JOIN RODCLI PROP WITH(NOLOCK) ON  
 VEI_CAV.CODPRO = PROP.CODCLIFOR    
 LEFT OUTER JOIN RODSET S WITH(NOLOCK) ON  
 CDES.CODSETCL = S.CODSETCL   
 LEFT OUTER JOIN RODGRO G WITH(NOLOCK) ON  
 CON.CODIGO=G.CODDOC  
 AND CON.CODFIL=G.FILDOC  
 AND CON.SERORD=G.SERDOC  
 LEFT OUTER JOIN RODDOP DOP WITH(NOLOCK) ON  
 CON.CODIGO = DOP.CODDOC  
 AND CON.SERORD = DOP.SERDOC  
 AND CON.CODFIL = DOP.FILDOC  
 AND DOP.TIPDOC = 'OST'  
 LEFT OUTER JOIN RODCPR CPR WITH(NOLOCK) ON  
 DOP.ID_CPR = CPR.ID_CPR  
    INNER JOIN RODIOS NFC WITH(NOLOCK) ON  
 CON.CODIGO = NFC.CODORD  
 AND CON.SERORD = NFC.SERORD  
 AND CON.CODFIL = NFC.FILORD  
 LEFT OUTER JOIN RODRED RED WITH(NOLOCK) ON  
 CON.CODFIL=RED.FILDOC  
 AND CON.SERORD=RED.SERDOC  
 AND CON.CODIGO=RED.CODDOC  
 AND RED.TIPDOC='OST'  
 LEFT OUTER JOIN RODCLI REDC WITH(NOLOCK) ON  
 ISNULL (RED.REDMU2,RED.REDMUN)=REDC.CODCLIFOR  
WHERE  
    (CPAG.CODCLIFOR = @PAGADOR OR @PAGADOR = 0)
    AND CON.SITUAC NOT IN ('C', 'I') 
   AND (CREM.CODCLIFOR = @REMETENTE OR @REMETENTE = 0)  
   AND (CDES.CODCLIFOR = @DESTINATARIO OR @DESTINATARIO = 0) 
	AND EXISTS (SELECT 1 FROM ESTNOT NF WITH(NOLOCK)
         WHERE  NF.CODFIL = CON.FILNOT AND  
                NF.SERSUB = CON.SERNOT AND  
                NF.CODIGO = CON.CODNOT   
                AND NF.SERSUB IN ('E', 'ND'))  
   AND (SELECT TOP 1 NF.DATEMI FROM ESTNOT NF WITH(NOLOCK)
         WHERE  NF.CODFIL = CON.FILNOT AND  
                NF.SERSUB = CON.SERNOT AND  
                NF.CODIGO = CON.CODNOT AND  
                NF.SERSUB IN ('E', 'ND')) >= @DATA_INI AND (SELECT TOP 1 NF.DATEMI FROM ESTNOT NF WITH(NOLOCK) 
         WHERE  NF.CODFIL = CON.FILNOT AND  
                NF.SERSUB = CON.SERNOT AND  
                NF.CODIGO = CON.CODNOT AND  
                NF.SERSUB IN ('E', 'ND')) < DATEADD(DAY,1,@DATA_FIM)     
   AND ('CTRC' = @TIPDOC OR @TIPDOC = '')  
   AND (CPAG.CODCGC LIKE @PAG_CNPJ OR @PAG_CNPJ = '')  
   AND (VEI_CAV.CODVEI = @CODVEI OR @CODVEI = '')  
   AND (IIF(CON.SITDUP IS NULL,'E',CON.SITDUP) = @FATURADOS OR @FATURADOS = '')  
   AND (CON.CODFIL = @FILIAL OR @FILIAL = 0)  
   AND (FRA.CODCMO = @MODAL OR @MODAL = 0)  
   AND (CON.FILDUP = @FILIAL_FATURA OR @FILIAL_FATURA = 0)  
   AND (CON.NUMDUP = @FATURA OR @FATURA = 0)  
   AND (ISNULL (RED.REDMU2,RED.REDMUN) = @REDESPACHO OR @REDESPACHO = 0)
UNION ALL   
SELECT    
    'NF' AS TIPDOC,  
    NF.TIPONF AS TIPCON,      
 NF.SITDUP,     
    NF.DATEMI AS DATA,  
    0 AS CODFIS,   
    NULL AS DIFERENCIAL,  
 --FIL.NOMEAB AS FILIAL,   
 FIL.CODCGC AS CNPJ_TRANSPORTADOR,  
 NF.CODFIL AS COD_FILIAL,  
    NF.SERSUB AS SERIE,   
    NF.CODIGO AS DOCUMENTO,  
    NULL AS COD_OCS,  
    NULL AS LINHA,  
    NULL AS CODVEI,  
 NULL AS CNPJ_PROPRIETARIO,  
 NULL AS CPF_PROPRIETATIO,  
 NULL AS NOME_PROPRIETATIO,  
 NULL AS FISJUR,  
    NULL  AS PLACA_CM,   
    NULL AS PLACA_CR_1,  
    NULL AS MOTORISTA,   
 NULL AS CPF_MOTORISTA,  
 NULL AS MOT_MANIFESTO,   
    CPAG.CODCLIFOR AS COD_PAGADOR,   
    CPAG.CODCGC AS PAG_CNPJ,  
    CPAG.RAZSOC AS PAGADOR,   
    CPAG.NOMEAB AS NOME_ABREVIADO,  
 VEND.NOMEVE AS NOME_VENDEDOR,  
 NULL AS COD_VENDEDOR_REM,  
 NULL AS COD_VENDEDOR_CONS,  
 NULL AS VENDEDOR_CONS,  
 NULL AS COD_VENDEDOR_DES,  
 NULL AS VENDEDOR_DES,   
    NULL AS COD_REMETENTE,  
    NULL AS REM_CNPJ,  
    NULL AS REM_INSCRI,  
    NULL AS REMETENTE,  
    NULL AS MUN_REMETENTE,  
    NULL AS EST_REMETENTE,  
    NULL AS COD_DESTINATARIO,  
    NULL AS DES_CNPJ,  
 NULL AS CEP_DESTINO,  
 NULL AS LOGRAD_DESTINO,  
 NULL AS NUMERO,  
 NULL AS END_DESTINO,  
 NULL AS BAIRRO_DESTINO,  
 NULL AS DESTINATARIO,  
    NULL AS MUN_DESTINATARIO,  
    NULL AS EST_DESTINATARIO,  
    NULL AS REDESPACHO,  
 NULL AS LOGRAD_REDESPACHO,  
 NULL AS NUM_REDESPACHO,  
 NULL AS END_REDESPACHO,   
    NULL AS TCOLETA,  
    NULL AS MUN_TCOLETA,  
    NULL AS EST_TCOLETA,  
    NULL AS TENTREGA,  
    NULL AS MUN_TENTREGA,  
    NULL AS EST_TENTREGA,  
    NULL AS RECEBEDOR,  
    (SELECT TOP 1 DUP.DATEMI  
        FROM dbo.RODDUP DUP WITH(NOLOCK)
             INNER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL  
                                  AND DUP.NUMDUP = IDU.NUMDUP  
         WHERE IDU.FILDOC = NF.CODFIL  
     AND IDU.SERDOC = NF.SERSUB   
     AND IDU.CODDOC = NF.CODIGO  
             ----INNER JOIN ESTNOT NF  ON IDU.FILDOC = NF.CODFIL   
             ----                                    AND IDU.SERDOC = NF.SERSUB            
             ----                                    AND IDU.CODDOC = NF.CODIGO  
             --     --INNER JOIN RODORN O  ON  O.FILNOT   = NF.CODFIL  
             --     --                    AND O.SERNOT   = NF.SERSUB  
             --     --                               AND O.CODNOT   = NF.CODIGO  
          AND DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'NF')   AS DT_EMISSAO_DUP,  
    (SELECT TOP 1 IDU.CODFIL  
            FROM dbo.RODDUP DUP WITH(NOLOCK)
             INNER JOIN RODIDU IDU WITH (NOLOCK) ON DUP.CODFIL = IDU.CODFIL  
                                  AND DUP.NUMDUP = IDU.NUMDUP  
      WHERE IDU.FILDOC = NF.CODFIL  
     AND IDU.SERDOC = NF.SERSUB   
     AND IDU.CODDOC = NF.CODIGO  
             --INNER JOIN ESTNOT NF  ON IDU.FILDOC = NF.CODFIL   
             --                                    AND IDU.SERDOC = NF.SERSUB            
             --                                    AND IDU.CODDOC = NF.CODIGO  
                  --INNER JOIN RODORN O  ON  O.FILNOT   = NF.CODFIL  
                  --                               AND O.SERNOT   = NF.SERSUB  
                  --                               AND O.CODNOT   = NF.CODIGO  
          AND DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'NF')  AS COD_FILIAL_DUP,      
    (SELECT TOP 1 IDU.NUMDUP  
         FROM dbo.RODDUP DUP WITH(NOLOCK)
             INNER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL  
                                  AND DUP.NUMDUP = IDU.NUMDUP  
      WHERE IDU.FILDOC = NF.CODFIL  
     AND IDU.SERDOC = NF.SERSUB   
     AND IDU.CODDOC = NF.CODIGO  
             --INNER JOIN ESTNOT NF  ON IDU.FILDOC = NF.CODFIL   
             --                                    AND IDU.SERDOC = NF.SERSUB            
             --                                    AND IDU.CODDOC = NF.CODIGO  
                  --INNER JOIN RODORN O  ON  O.FILNOT   = NF.CODFIL  
                  --                               AND O.SERNOT   = NF.SERSUB  
                  --                               AND O.CODNOT   = NF.CODIGO  
          AND DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'NF')   AS COD_FATURA,   
    (SELECT TOP 1 DUP.DATVEN  
         FROM dbo.RODDUP DUP WITH(NOLOCK)  
             INNER JOIN RODIDU IDU  WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL  
                                  AND DUP.NUMDUP = IDU.NUMDUP  
     WHERE IDU.FILDOC = NF.CODFIL  
       AND IDU.SERDOC = NF.SERSUB   
       AND IDU.CODDOC = NF.CODIGO  
             ----INNER JOIN ESTNOT NF  ON IDU.FILDOC = NF.CODFIL   
             ----                                    AND IDU.SERDOC = NF.SERSUB            
             ----                                    AND IDU.CODDOC = NF.CODIGO  
             --     --INNER JOIN RODORN O  ON  O.FILNOT   = NF.CODFIL  
             --     --                               AND O.SERNOT   = NF.SERSUB  
             --     --                               AND O.CODNOT   = NF.CODIGO  
          AND DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'NF') AS DT_VENC_DUP,  
    (SELECT TOP 1 M.DATLAN  
         FROM dbo.RODDUP DUP WITH(NOLOCK)   
             INNER JOIN RODIDU IDU WITH(NOLOCK) ON DUP.CODFIL = IDU.CODFIL  
                                  AND DUP.NUMDUP = IDU.NUMDUP  
  INNER JOIN RECMEN M WITH(NOLOCK) ON  DUP.CODFIL = M.CODFIL  
                                                 AND CAST(DUP.NUMDUP AS VARCHAR)=M.NUMDUP  
         WHERE IDU.FILDOC = NF.CODFIL  
     AND IDU.SERDOC = NF.SERSUB   
     AND IDU.CODDOC = NF.CODIGO  
             --INNER JOIN ESTNOT NF  ON IDU.FILDOC = NF.CODFIL   
             --                                  AND IDU.SERDOC = NF.SERSUB            
             --                                  AND IDU.CODDOC = NF.CODIGO  
                  --INNER JOIN RODORN O  ON  O.FILNOT   = NF.CODFIL  
                  --                               AND O.SERNOT   = NF.SERSUB  
                  --                               AND O.CODNOT   = NF.CODIGO  
                  --INNER JOIN RECMEN M  ON  DUP.CODFIL = M.CODFIL  
                  --                               AND CAST(DUP.NUMDUP AS VARCHAR)=M.NUMDUP  
          AND DUP.SITUAC NOT IN ('C', 'I')  
          AND IDU.TIPDOC = 'NF'  
          AND M.DEBCRE = 'C'  
          ORDER BY M.DATLAN DESC)   AS DT_REC_FATURA,   
          NULL AS REF_CLIENTE,  
          NULL AS NOSSA_REF,  
          NULL AS QTD_VOL,  
          NULL AS PESO,      
          NULL AS LARG_CUB,  
          NULL AS ALTURA_CUB,  
          NULL AS PROFUN_CUB,      
          NULL AS PESO_CUB,          
          NULL AS PESO_CALC,          
          NULL AS VLR_MERC,  
          NULL AS ESPECIE,  
          NULL AS PRODUTO,   
          NULL AS DATA_ENTREGA,  
    NULL AS FRETE_PESO,   
    NULL AS FRETE_VALOR,  
    NULL AS VLR_DESPACHO,  
    NULL AS VLR_PEDAGIO,  
 SNF.ALIISS,  
    NULL AS ALICOT,  
 SNF.VLRPIS AS PIS_COFINS,  
    NULL AS VLR_ICMS,  
 SNF.VLRISS AS VLR_ISS,   
    SNF.BASISS AS BASE_CALCULO,  
    NF.VLRBRU AS VLR_TOTAL_FRETE,   
    NULL AS VLR_AJUDANTE,  
    NULL AS PLAT_REF_CAR_CC,  
    NULL AS DGR_DEV_CC,  
    NULL AS VLR_CARGA,  
    NULL AS VLR_DESCARGA,  
    NULL AS VLR_TXDIF,  
    NULL AS VLR_SUFRAMA,  
    NULL AS VLR_SECCAT,  
    NULL AS VLR_GRIS,  
    NULL AS VLR_ESCOLTA,  
    NULL AS TX_ADICIONAL,   
    NF.OBSGER AS OBSERVACAO,  
    NULL AS TABPAD,  
 NULL AS ITEM_TARIFA,  
 NULL AS CODCMO,  
 NULL AS DESCRI,  
    NF.USUATU,  
    NULL AS DESC_HR_CHEGADA,  
    NULL AS DESC_RH_ENTRADA,  
    NULL AS DESSC_HR_SAIDA,  
    NULL AS CARG_HR_CHEGADA,  
    NULL AS CARG_HR_ENTRADA,  
    NULL AS CARG_HR_SAIDA,  
 NULL AS REGIAO_ORIGEM,  
 NULL AS REGIAO_DESTINO,  
 NULL AS MANIFESTO,   
 NULL AS FILIAL_MANIFESTO,  
 NULL AS SERIE_MANIFESTO,  
 NULL AS FILIAL_DESTINO,  
    NULL AS TIP0_MAN,  
 NULL AS MANIFESTO_TRANSF,   
 NULL AS FILIAL_MANIFESTO_TRANSF,  
 NULL AS SERIE_MANIFESTO_TRANSF,  
 NULL AS FILIAL_DESTINO_TRANSF,  
 'S' AS NFEAUT,  
 NF.ISS_ID AS CHAVE_CTE,  
 NF.ISSPRO AS PROTOC_CTE,  
 'N' AS FAT_BLOQUEADO,  
 0 AS ICM_INCENTIVADO,  
 'N' AS A_VISTA,  
 NULL AS FILIAL_COTACAO,  
 NULL AS COTACAO,  
 NULL AS PRAZO_ENTREGA,  
    NULL AS METDIA,  
 NF.PREFAT AS PREFAT,  
    NULL AS DIAS_ATRASOS,   
 NULL AS  COD_OCORRENCIA,  
 NULL AS  OCORRENCIA,  
 NULL AS  COD_OCO_FINALIZ,  
 NULL AS  OCORRENCIA_FINALIZ,  
 NULL AS CONF_ROM_CARREGTO,  
 NULL AS CONF_ROM_DESCARGA,  
 NULL AS DT_AVERBACAO,  
 NULL AS PROT_AVERBACAO,  
 NULL AS COD_ULT_OCORRENCIA,  
 NULL AS  ULT_OCORRENCIA,  
 NULL AS SETOR_ENTREGA,  
    NULL AS COD_GERENC_RISCO,  
 NULL AS SITUACAO,   
 '' AS COMPROVANTE_ENTREGA,  
 NULL AS SITUACAO_OS,  
 NULL AS REDESPACHO_PARCEIRO
-- ,
-- NULL AS Ocorrencias_da_NF 
FROM  
    dbo.ESTNOT AS NF  WITH(NOLOCK) 
    INNER JOIN dbo.RODFIL AS FIL WITH(NOLOCK) ON   
    NF.CODFIL = FIL.CODFIL   
 LEFT OUTER JOIN ESTSNF SNF WITH(NOLOCK) ON  
 NF.CODFIL = SNF.FILNOT  AND  
 NF.SERSUB = SNF.SERNOT  AND  
 NF.CODIGO = SNF.CODNOT  
    INNER JOIN dbo.RODCLI AS CPAG WITH(NOLOCK) ON   
    NF.CODCLIFOR = CPAG.CODCLIFOR   
    INNER JOIN dbo.RODMUN AS MCPAG WITH(NOLOCK) ON   
    CPAG.CODMUN = MCPAG.CODMUN  
    LEFT OUTER JOIN dbo.RODCGR AS CGR WITH(NOLOCK) ON  
    CPAG.CODCGR = CGR.CODCGR  
    LEFT OUTER JOIN RECVEN AS VEND WITH(NOLOCK) ON  
    CPAG.CODVEN = VEND.CODVEN  
WHERE       
    (CPAG.CODCLIFOR = @PAGADOR OR @PAGADOR = 0)  
	AND NF.DATEMI >@DATA_INI  AND NF.DATEMI <=DATEADD(DAY,1,@DATA_FIM)  
    AND NF.SITUAC NOT IN ('C', 'I')  
	AND NOT EXISTS (SELECT 1 FROM RODORN O WITH(NOLOCK) WHERE NF.CODFIL=O.FILNOT AND NF.SERSUB=O.SERNOT AND NF.CODIGO=O.CODNOT)  
    AND NF.SERSUB IN ('E', 'ND')  
   --AND (CREM.CODCLIFOR = @REMETENTE OR @REMETENTE = 0)  
   --AND (CDES.CODCLIFOR = @DESTINATARIO OR @DESTINATARIO = 0)  
   AND ('CTRC' = @TIPDOC OR @TIPDOC = '')  
   AND (CPAG.CODCGC LIKE @PAG_CNPJ OR @PAG_CNPJ = '')  
   --AND (VEI_CAV.CODVEI = @CODVEI OR @CODVEI = '')  
   AND (IIF(NF.SITDUP IS NULL,'E',NF.SITDUP) = @FATURADOS OR @FATURADOS = '')  
   AND (NF.CODFIL = @FILIAL OR @FILIAL = 0)  
   --AND (FRA.CODCMO = @MODAL OR @MODAL = '')  
   AND (NF.FILDUP = @FILIAL_FATURA OR @FILIAL_FATURA = 0)  
   AND (NF.NUMDUP = @FATURA OR @FATURA = 0)
GO


