CREATE VIEW [DBO].[VW_CARGA_AGILE_FROTA]
AS

/* INICIO DO SCRIPT 
 SCRIPT VISUAL RODOPAR  
 ## ID ......: 
 ## AUTOR ...: Kelsen Lima
 ## DATA ....: 06/07/2018 
 ## RESUMO ..: View para carga de dados de veiculo para o aplicativo agileprocess
 ## REVISAO..: 
 ## REVISAO..: 
*/

SELECT V.CODVEI AS CODIGO,
       V.DATINC AS DATA_INCLUSAO,
	   V.DATATU AS DATA_ALTERACAO,
       V.NUMVEI AS PLACA,
       V.QTDLIT AS QTD_LITROS_TANQUE,
       V.TARAKG AS TARA_KG,
       V.LOTACA AS CAP_CARGA_KG,
       V.PESBRU AS PESO_BRUTO,
       C.DESCRI AS MARCA,
       D.DESCRI AS MODELO,
       F.DESCRI AS DESCRICAO,
       V.COMPRI AS COMPRIMENTO,
       V.ALTURA AS ALTURA,
       V.LARGUR AS LARGURA,
       IIF(V.CODPRO IS NOT NULL,V.CODPRO,V.CODFIL) AS CODIGO_PROPRIETARIO,
       IIF(V.CODPRO IS NOT NULL,RODCLI.RAZSOC,'GAT LOGISTICA') AS PROPRIETARIO,
       M.CODMOT AS CODIGO_MOTORISTA_01,
       IIF(V.CODMOT IS NOT NULL,M.NOMMOT,'SEM MOTORISTA ASSOCIADO') AS MOTORISTA_FIXO01,
       M2.CODMOT AS CODIGO_MOTORISTA_02,
       IIF(V.CODMO2 IS NOT NULL,M2.NOMMOT,'SEM MOTORISTA ASSOCIADO') AS MOTORISTA_FIXO02       
  FROM RODVEI V  
 INNER JOIN RODMCV C on V.CODMCV = C.CODMCV  
 INNER JOIN RODMDV D on V.CODMDV = D.CODMDV 
 INNER JOIN RODFRO F on V.CODFRO = F.CODFRO 
  LEFT OUTER JOIN  RODCLI on V.CODPRO = RODCLI.CODCLIFOR 
  LEFT OUTER JOIN  RODMOT M on V.CODMOT = M.CODMOT
  LEFT OUTER JOIN  RODMOT M2 on V.CODMO2 = M2.CODMOT  
 WHERE V.CODPAD IN (1)
   AND V.SITUAC = '1' -- 1)Normal 2)Baixado 3)Inativo
   AND V.PROPRI IN('S','N')   --"S" Veiculo GAT / "N" Viculo Agrugado - Terceiro - Parceiro
   AND V.CODCMB IN(1,2,3,7,8) -- 1)Oleo Disel - 2)Gasolina - 3)Alcool - 4)Lubrificante - 5)Sem Combustivel - 6)GLP - 7)Oleo Disel Externo - 8)Alcool/Gasolina
   AND V.REGRTB <> 0 -- Registro ANTT   

GO

GRANT SELECT ON dbo.VW_CARGA_AGILE_FROTA TO agileprocess
GO
